/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\nimbus.o c:\users\owner\documents\nim\esfj\nimcache\nimbus.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <setjmp.h>

#include <stdio.h>
typedef struct TY13606 TY13606;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Slice88061 Slice88061;
typedef struct TY282131 TY282131;
typedef struct Profile282002 Profile282002;
typedef struct Tsocketimpl136607 Tsocketimpl136607;
typedef struct Tsqlite3165291 Tsqlite3165291;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct TY164210 TY164210;
typedef struct Mtstate273035 Mtstate273035;
typedef struct SslcontextHEX3Aobjecttype265375 SslcontextHEX3Aobjecttype265375;
typedef struct ProxyHEX3Aobjecttype265023 ProxyHEX3Aobjecttype265023;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
typedef struct Uri235012 Uri235012;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
struct  Slice88061  {
NI a;
NI b;
};
struct  Profile282002  {
NimStringDesc* name;
NI upvotes;
NI downvotes;
NimStringDesc* rank;
};
typedef NimStringDesc* TY161637[1];
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY15609;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY15609 raiseAction;
};
typedef NimStringDesc* TY167666[1];
typedef NimStringDesc* TY282225[2];
struct TY164210 {
NimStringDesc* Field0;
NI Field1;
};
typedef NU8 TY77659[32];
typedef NU32 TY273036[624];
struct  Mtstate273035  {
TY273036 mt;
NI mti;
};
typedef NI TY27820[8];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
typedef NIM_CHAR TY256208[4001];
struct  Tsocketimpl136607  {
NI fd;
NIM_BOOL isbuffered;
union{
struct {TY256208 buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NIM_BOOL nonblocking;
};
struct  Tsqlite3165291  {
char dummy;
};
struct  SslcontextHEX3Aobjecttype265375  {
char dummy;
};
struct  Uri235012  {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct  ProxyHEX3Aobjecttype265023  {
Uri235012 url;
NimStringDesc* auth;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct TY13606 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY282131 {
  TGenericSeq Sup;
  Profile282002 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, delete_282270)(TY13606** s, NI first, NI last);
N_NIMCALL(NimStringDesc*, version_282007)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, about_282013)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(TY13606*, chansplit_282019)(NimStringDesc* raw);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(NimStringDesc*, getnick_282076)(NimStringDesc* raw);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x);
static N_INLINE(Slice88061, HEX2EHEX2E_110273)(NI a, NI b);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_83404, TNimType* mt);
N_NIMCALL(Tsocketimpl136607*, socket_137604)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(Tsqlite3165291*, open_167645)(NimStringDesc* connection, NimStringDesc* user, NimStringDesc* password, NimStringDesc* database);
N_NIMCALL(void, exec_167155)(Tsqlite3165291* db, NimStringDesc* query, NimStringDesc** args, NI argsLen0);
static N_INLINE(NimStringDesc*, sql_167021)(NimStringDesc* query);
N_NIMCALL(void, connect_142083)(Tsocketimpl136607* socket, NimStringDesc* address, NU16 port, NU8 af);
N_NIMCALL(void, send_146407)(Tsocketimpl136607* socket, NimStringDesc* data);
N_NIMCALL(NimStringDesc*, inttoitem_282145)(NI itemid);
N_NIMCALL(NIM_BOOL, isloggedin_282152)(NimStringDesc* name);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NIM_BOOL, checkuser_282189)(NimStringDesc* name);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, getvalue_167577)(Tsqlite3165291* db, NimStringDesc* query, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_52622)(Tcell46746* c);
static N_INLINE(NIM_BOOL, canbecycleroot_50267)(Tcell46746* c);
static N_INLINE(void, rtladdcycleroot_51023)(Tcell46746* c);
N_NOINLINE(void, incl_47465)(Tcellset46758* s, Tcell46746* cell);
static N_INLINE(void, decref_52204)(Tcell46746* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, getquote_282200)(NI id);
N_NIMCALL(TY13606*, getrow_167472)(Tsqlite3165291* db, NimStringDesc* query, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NI, addquote_282210)(NimStringDesc* content);
N_NIMCALL(NI64, tryinsertid_167593)(Tsqlite3165291* db, NimStringDesc* query, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NI, adduser_282220)(NimStringDesc* name, NimStringDesc* pass);
N_NIMCALL(NI, getquotecount_282231)(void);
N_NIMCALL(NIM_BOOL, loginuser_282241)(NimStringDesc* name, NimStringDesc* pass);
N_NIMCALL(NIM_BOOL, logoutuser_282252)(NimStringDesc* name);
N_NIMCALL(NI, upvote_282360)(NimStringDesc* name);
N_NIMCALL(NI, downvote_282372)(NimStringDesc* name);
N_NIMCALL(NI, karma_282384)(NimStringDesc* name);
static N_INLINE(void, writeln_282416)(FILE* f, NimStringDesc** x, NI xLen0);
N_NIMCALL(void, write_13457)(FILE* f, NimStringDesc* s);
N_NIMCALL(void, readline_145045)(Tsocketimpl136607* socket, NimStringDesc** line, NI timeout);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, HEX24_282510)(TY13606* x);
N_NIMCALL(NimStringDesc*, collectiontostring_282518)(TY13606* x, NimStringDesc* b, NimStringDesc* e);
N_NIMCALL(TY13606*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
N_NIMCALL(FILE*, open_13217)(NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen0, NimStringDesc* sep);
N_NIMCALL(TY13606*, HEX5BHEX5D_133598)(TY13606* s, Slice88061 x);
N_NIMCALL(void, execcmdex_164204)(NimStringDesc* command, NU8 options, TY164210* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(TY13606*, nsuSplitCharSet)(NimStringDesc* s, TY77659 seps);
static N_INLINE(NI, randomint_279271)(NI min, NI max);
static N_INLINE(NI, randomint_279309)(Mtstate273035* rng, NI min, NI max);
static N_INLINE(NI, randomint_277853)(Mtstate273035* rng, NI max);
N_NIMCALL(NU, randomintimpl_277871)(Mtstate273035* rng, NU max);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NIM_BOOL, tryexec_167138)(Tsqlite3165291* db, NimStringDesc* query, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NimStringDesc*, nimBoolToStr)(NIM_BOOL x);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(void, nsuDelete)(NimStringDesc** s, NI first, NI last);
N_NIMCALL(NimStringDesc*, getcontent_266171)(NimStringDesc* url, NimStringDesc* extraheaders, NI maxredirects, SslcontextHEX3Aobjecttype265375* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype265023* proxy);
N_NIMCALL(NIM_BOOL, contains_101362)(NimStringDesc* s, NimStringDesc* sub);
N_NIMCALL(void, close_140462)(Tsocketimpl136607* socket);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_socketsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_socketsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3Init)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typeinfoInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typeinfoDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_marshalInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_marshalDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsexmlInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsexmlDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64Init)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_utilInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_utilDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_random_realInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_random_realDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_commonInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_commonDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mt19937arInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mt19937arDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mersenneInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mersenneDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_urandomInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_urandomDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_randomInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_randomDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimbusInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimbusDatInit)(void);
STRING_LITERAL(TMP2750, "v1.0.0", 6);
STRING_LITERAL(TMP2751, "ESFJ - By Cryptotoad (", 22);
STRING_LITERAL(TMP2752, ")", 1);
STRING_LITERAL(TMP2754, ",", 1);
STRING_LITERAL(TMP2757, "#", 1);
STRING_LITERAL(TMP2760, "irc.freenode.net", 16);
STRING_LITERAL(TMP2762, "", 0);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} CNSTSEQ2764 = {{1, 1}, {((NimStringDesc*) &TMP2762)}};
NIM_CONST TY13606* TMP2761 = ((TY13606*)&CNSTSEQ2764);
STRING_LITERAL(TMP2764, "FoxMcCloud", 10);
STRING_LITERAL(TMP2765, "ESFJ", 4);
STRING_LITERAL(TMP2767, "#reddit-intp", 12);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} CNSTSEQ2769 = {{1, 1}, {((NimStringDesc*) &TMP2767)}};
NIM_CONST TY13606* TMP2766 = ((TY13606*)&CNSTSEQ2769);
STRING_LITERAL(TMP2773, "ESFJ.db", 7);
STRING_LITERAL(TMP2774, "postgres", 8);
STRING_LITERAL(TMP2775, "nimforum", 8);
STRING_LITERAL(TMP2776, "create table if not exists quotes(\015\012  id integer primary key,\015\012"
"  content varchar(1024) not null);\015\012", 99);
STRING_LITERAL(TMP2777, "create table if not exists users(\015\012  id integer primary key,\015\012 "
" name varchar(20) not null,\015\012  upvotes integer not null,\015\012  down"
"votes integer not null,\015\012  rank integer not null,\015\012  pass varcha"
"r(30) not null,\015\012  loot varchar(300));\015\012", 231);
STRING_LITERAL(TMP2778, "create table if not exists users_loot(\015\012  id integer primary ke"
"y, \015\012  weapon integer, \015\012  armor integer, \015\012  shield integer, \015\012"
"  bag varchar(1024))", 147);
STRING_LITERAL(TMP2781, "NICK ", 5);
STRING_LITERAL(TMP2782, "\015\015\012", 3);
STRING_LITERAL(TMP2783, "USER ", 5);
STRING_LITERAL(TMP2784, " ", 1);
STRING_LITERAL(TMP2785, " :ESFJ IRC\015\015\012", 13);
STRING_LITERAL(TMP2786, "MODE ", 5);
STRING_LITERAL(TMP2787, " +i\015\015\012", 6);
STRING_LITERAL(TMP2788, "flaming", 7);
STRING_LITERAL(TMP2789, "none", 4);
STRING_LITERAL(TMP2792, "select id from users where upper(name) = ?", 42);
STRING_LITERAL(TMP2793, "select id, content from quotes where id = ?", 43);
STRING_LITERAL(TMP2794, "Quote #", 7);
STRING_LITERAL(TMP2795, " : ", 3);
STRING_LITERAL(TMP2796, "insert into quotes(id, content) values (null, ?)", 48);
STRING_LITERAL(TMP2797, "insert into users(id, name, upvotes, downvotes, rank, pass, loo"
"t) values (null, ?, 0, 0, 0, ?, \'\')", 98);
STRING_LITERAL(TMP2798, "select count(*) from quotes", 27);
STRING_LITERAL(TMP2799, "select id from users where upper(name) = ? and pass = ?", 55);
STRING_LITERAL(TMP2801, "  update users set upvotes = upvotes + 1 where upper(name) = ?;"
"\015\012  ", 67);
STRING_LITERAL(TMP2802, "select upvotes - downvotes from users where upper(name) = ?", 59);
STRING_LITERAL(TMP2803, "  update users set downvotes = downvotes + 1 where upper(name) "
"= ?;\015\012  ", 71);
STRING_LITERAL(TMP2805, "\015\012", 2);
STRING_LITERAL(TMP2836, ":", 1);
STRING_LITERAL(TMP2837, " MODE ", 6);
STRING_LITERAL(TMP2838, " :+i", 4);
STRING_LITERAL(TMP2839, "JOIN ", 5);
STRING_LITERAL(TMP2841, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TMP2845, "connection is closed", 20);
STRING_LITERAL(TMP2850, "PING", 4);
STRING_LITERAL(TMP2851, "PONG ", 5);
STRING_LITERAL(TMP2852, "QUIT", 4);
STRING_LITERAL(TMP2853, "PRIVMSG", 7);
STRING_LITERAL(TMP2854, ":!v", 3);
STRING_LITERAL(TMP2855, "PRIVMSG ", 8);
STRING_LITERAL(TMP2856, " :", 2);
STRING_LITERAL(TMP2857, ":!eval", 6);
STRING_LITERAL(TMP2858, "Cryptotoad", 10);
STRING_LITERAL(TMP2859, "cryptotoad", 10);
STRING_LITERAL(TMP2860, "eval.nim", 8);
STRING_LITERAL(TMP2862, "proc eval(): auto =", 19);
NIM_CONST TY167666 TMP2861 = {((NimStringDesc*) &TMP2862)}
;
STRING_LITERAL(TMP2864, ";", 1);
STRING_LITERAL(TMP2869, "when compiles(echo eval()): echo eval()", 39);
NIM_CONST TY167666 TMP2868 = {((NimStringDesc*) &TMP2869)}
;
STRING_LITERAL(TMP2871, "else: eval()", 12);
NIM_CONST TY167666 TMP2870 = {((NimStringDesc*) &TMP2871)}
;
STRING_LITERAL(TMP2872, "nim c --stackTrace:off --lineTrace:off --threads:off --checks:o"
"ff --fieldChecks:off --rangeChecks:on --boundChecks:on --overflo"
"wChecks:on --assertions:on --floatChecks:off --nanChecks:on --in"
"fChecks:off --opt:none --warnings:off --hints:off --threadanalys"
"is:off --verbosity:0 ", 276);
STRING_LITERAL(TMP2873, "./", 2);
STRING_LITERAL(TMP2876, "<no output>", 11);
STRING_LITERAL(TMP2877, ": ", 2);
STRING_LITERAL(TMP2878, ":!roll", 6);
STRING_LITERAL(TMP2879, "Please enter a formula (1d20) \015\015\012", 33);
static NIM_CONST TY77659 TMP2880 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP2882, " : Don\'t roll that many dice! Why would you need to?!??! \015\015\012", 60);
STRING_LITERAL(TMP2888, " rolled a ", 10);
STRING_LITERAL(TMP2889, "! \015\015\012", 5);
STRING_LITERAL(TMP2890, " : Please use smaller / positive / whole) numbers! \015\015\012", 54);
STRING_LITERAL(TMP2891, ":!upvote", 8);
STRING_LITERAL(TMP2892, " :You have upvoted ", 19);
STRING_LITERAL(TMP2893, " Bringing them to ", 18);
STRING_LITERAL(TMP2894, " karma.\015\015\012", 10);
STRING_LITERAL(TMP2895, " :You cannot upvote unless you are logged in, you cannot upvote"
" yourself, and you must specify a recipient!\015\015\012", 110);
STRING_LITERAL(TMP2896, ":!downvote", 10);
STRING_LITERAL(TMP2897, " :You have downvoted ", 21);
STRING_LITERAL(TMP2898, " :You cannot downvote unless you are logged in, you cannot down"
"vote yourself, and you must specify a recipient!\015\015\012", 114);
STRING_LITERAL(TMP2899, ":!karma", 7);
STRING_LITERAL(TMP2900, " has a total of ", 16);
STRING_LITERAL(TMP2901, ":!login", 7);
STRING_LITERAL(TMP2902, " : Please enter a password! \015\015\012", 31);
STRING_LITERAL(TMP2903, " : You have logged in successfully! \015\015\012", 39);
STRING_LITERAL(TMP2904, " : Invalid password! \015\015\012", 24);
STRING_LITERAL(TMP2905, ":!logout", 8);
STRING_LITERAL(TMP2906, ":!register", 10);
STRING_LITERAL(TMP2907, " : Your pass is ", 16);
STRING_LITERAL(TMP2908, " \015\015\012", 4);
STRING_LITERAL(TMP2909, " : Username is taken. \015\015\012", 25);
STRING_LITERAL(TMP2910, " : Your randomly generated pass is ", 35);
STRING_LITERAL(TMP2911, ":!help", 6);
STRING_LITERAL(TMP2912, " :!quote # - Retrieve quote / !addquote <quote> - adds a quote "
"to database\015\015\012", 77);
STRING_LITERAL(TMP2913, " :!roll <1d20> - Dice roller / !help - this menu\015\015\012", 51);
STRING_LITERAL(TMP2914, ":!quote", 7);
STRING_LITERAL(TMP2916, " :No... Bad human...\015\015\012", 23);
STRING_LITERAL(TMP2918, ":!addquote", 10);
STRING_LITERAL(TMP2919, " :Quote #", 9);
STRING_LITERAL(TMP2920, " added!\015\015\012", 10);
STRING_LITERAL(TMP2921, " :Please enter a quote.\015\015\012", 26);
STRING_LITERAL(TMP2922, ":!rawsql", 8);
STRING_LITERAL(TMP2923, " :Result: ", 10);
STRING_LITERAL(TMP2924, ":http", 5);
STRING_LITERAL(TMP2925, ":https", 6);
STRING_LITERAL(TMP2932, "Nim httpclient/0.1", 18);
STRING_LITERAL(TMP2933, "1", 1);
STRING_LITERAL(TMP2934, "<title>", 7);
STRING_LITERAL(TMP2935, "2", 1);
STRING_LITERAL(TMP2936, "</title>", 8);
STRING_LITERAL(TMP2937, " - ", 3);
STRING_LITERAL(TMP2938, " - URL Preview\015\015\012", 17);
STRING_LITERAL(TMP2939, "N/A", 3);
STRING_LITERAL(TMP2940, "err!", 4);
STRING_LITERAL(TMP2941, "meme", 4);
STRING_LITERAL(TMP2942, "newfag", 6);
STRING_LITERAL(TMP2943, "triforce", 8);
STRING_LITERAL(TMP2944, " : \342\226\262\015\015\012", 9);
STRING_LITERAL(TMP2945, " :\342\226\262 \342\226\262\015\015\012", 12);
extern TFrame* frameptr_17042;
extern TNimType NTI13606; /* seq[string] */
extern Tgcheap48616 gch_48644;
NimStringDesc* server_282093;
TY13606* loggedin_282108;
NU16 port_282110;
NimStringDesc* username_282111;
NimStringDesc* nick_282112;
TY13606* channels_282127;
FILE* log_282128;
NIM_BOOL islogging_282129;
NIM_BOOL outputting_282130;
TY282131* profiles_282132;
Tsocketimpl136607* sock_282133;
NimStringDesc* buffer_282134;
Tsqlite3165291* db_282135;
extern TSafePoint* exchandler_17043;
extern Exception* currexception_17045;
NimStringDesc* channel_282474;
NimStringDesc* line_282601;
NI i_282667;
extern Mtstate273035 mersennetwisterinst_277010;
extern SslcontextHEX3Aobjecttype265375* defaultsslcontext_265377;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NimStringDesc*, version_282007)(void) {
	NimStringDesc* result;
	nimfr("version", "usersystem.nim")
	result = 0;
	nimln(24, "usersystem.nim");
	result = copyString(((NimStringDesc*) &TMP2750));
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, about_282013)(void) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("about", "usersystem.nim")
	result = 0;
	nimln(27, "usersystem.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = version_282007();
	LOC1 = rawNewString(LOC2->Sup.len + 23);
appendString(LOC1, ((NimStringDesc*) &TMP2751));
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP2752));
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(TY13606*, chansplit_282019)(NimStringDesc* raw) {
	TY13606* result;
	nimfr("chansplit", "usersystem.nim")
	result = 0;
	nimln(31, "usersystem.nim");
	result = (TY13606*) newSeq((&NTI13606), 0);
	{
		NimStringDesc* channel_282040;
		NI last_282055;
		channel_282040 = 0;
		nimln(293, "strutils.nim");
		last_282055 = ((NI) 0);
		nimln(294, "strutils.nim");
		{
			if (!(((NI) 0) < (raw ? raw->Sup.len : 0))) goto LA4;
			{
				nimln(295, "strutils.nim");
				while (1) {
					NI first_282057;
					NI TMP2756;
					NimStringDesc* LOC13;
					NimStringDesc* LOC14;
					NI TMP2758;
					if (!(last_282055 <= (raw ? raw->Sup.len : 0))) goto LA7;
					nimln(296, "strutils.nim");
					first_282057 = last_282055;
					{
						nimln(297, "strutils.nim");
						while (1) {
							NIM_BOOL LOC10;
							NI TMP2753;
							NimStringDesc* LOC12;
							NI TMP2755;
							LOC10 = 0;
							LOC10 = (last_282055 < (raw ? raw->Sup.len : 0));
							if (!(LOC10)) goto LA11;
							TMP2753 = addInt(last_282055, ((NI) 0));
							LOC12 = 0;
							LOC12 = copyStrLast(raw, last_282055, (NI)(TMP2753));
							LOC10 = !(eqStrings(LOC12, ((NimStringDesc*) &TMP2754)));
							LA11: ;
							if (!LOC10) goto LA9;
							nimln(298, "strutils.nim");
							TMP2755 = addInt(last_282055, ((NI) 1));
							last_282055 = (NI)(TMP2755);
						} LA9: ;
					}
					nimln(299, "strutils.nim");
					TMP2756 = subInt(last_282055, ((NI) 1));
					channel_282040 = copyStrLast(raw, first_282057, (NI)(TMP2756));
					nimln(34, "usersystem.nim");
					LOC13 = 0;
					LOC13 = rawNewString(channel_282040->Sup.len + 1);
appendString(LOC13, ((NimStringDesc*) &TMP2757));
appendString(LOC13, channel_282040);
					result = (TY13606*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
					LOC14 = 0;
					LOC14 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(LOC13);
					if (LOC14) nimGCunrefNoCycle(LOC14);
					nimln(300, "strutils.nim");
					TMP2758 = addInt(last_282055, ((NI) 1));
					last_282055 = (NI)(TMP2758);
				} LA7: ;
			}
		}
		LA4: ;
	}
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x) {
	NimStringDesc* result;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2880, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice88061, HEX2EHEX2E_110273)(NI a, NI b) {
	Slice88061 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(234, "system.nim");
	result.a = a;
	nimln(235, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getnick_282076)(NimStringDesc* raw) {
	NimStringDesc* result;
	NI LOC1;
	NI TMP2759;
	Slice88061 LOC2;
	nimfr("getNick", "usersystem.nim")
	result = 0;
	nimln(38, "usersystem.nim");
	LOC1 = 0;
	LOC1 = nsuFindChar(raw, 33, ((NI) 0));
	TMP2759 = subInt(LOC1, ((NI) 1));
	LOC2 = HEX2EHEX2E_110273(((NI) 1), (NI)(TMP2759));
	result = HEX5BHEX5D_88054(raw, LOC2);
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NimStringDesc*, sql_167021)(NimStringDesc* query) {
	NimStringDesc* result;
	nimfr("sql", "db_sqlite.nim")
	result = 0;
	nimln(34, "db_sqlite.nim");
	result = copyString(query);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, inttoitem_282145)(NI itemid) {
	NimStringDesc* result;
	nimfr("intToItem", "usersystem.nim")
	result = 0;
	nimln(92, "usersystem.nim");
	switch (itemid) {
	case ((NI) 1):
	{
		nimln(94, "usersystem.nim");
		result = copyString(((NimStringDesc*) &TMP2788));
	}
	break;
	default:
	{
		nimln(96, "usersystem.nim");
		result = copyString(((NimStringDesc*) &TMP2789));
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isloggedin_282152)(NimStringDesc* name) {
	NIM_BOOL result;
	nimfr("isLoggedIn", "usersystem.nim")
{	result = 0;
	{
		NI i_282168;
		NI HEX3Atmp_282170;
		NI res_282173;
		i_282168 = 0;
		HEX3Atmp_282170 = 0;
		nimln(99, "usersystem.nim");
		HEX3Atmp_282170 = (loggedin_282108 ? (loggedin_282108->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_282173 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP2790;
				if (!(res_282173 <= HEX3Atmp_282170)) goto LA3;
				nimln(1600, "system.nim");
				i_282168 = res_282173;
				nimln(100, "usersystem.nim");
				{
					NI LOC6;
					if ((NU)(i_282168) >= (NU)(loggedin_282108->Sup.len)) raiseIndexError();
					LOC6 = 0;
					LOC6 = nsuCmpIgnoreCase(loggedin_282108->data[i_282168], name);
					if (!(LOC6 == ((NI) 0))) goto LA7;
					nimln(101, "usersystem.nim");
					result = NIM_TRUE;
					nimln(102, "usersystem.nim");
					goto BeforeRet;
				}
				LA7: ;
				nimln(1614, "system.nim");
				TMP2790 = addInt(res_282173, ((NI) 1));
				res_282173 = (NI)(TMP2790);
			} LA3: ;
		}
	}
	nimln(103, "usersystem.nim");
	result = NIM_FALSE;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_17043;
	exchandler_17043 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_17043 = (*exchandler_17043).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_17042 = s;
}

static N_INLINE(NIM_BOOL, canbecycleroot_50267)(Tcell46746* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_51023)(Tcell46746* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(139, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(191, "gc.nim");
		incl_47465((&gch_48644.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_52622)(Tcell46746* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_50267(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_51023(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_52204)(Tcell46746* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_51804(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_50267(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_51023(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		Tcell46746* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_50246(src);
		incref_52622(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		Tcell46746* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_50246((*dest));
		decref_52204(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_17045), (*currexception_17045).parent);
}

N_NIMCALL(NIM_BOOL, checkuser_282189)(NimStringDesc* name) {
	NIM_BOOL volatile result;
	TSafePoint TMP2791;
	nimfr("checkUser", "usersystem.nim")
	result = 0;
	nimln(106, "usersystem.nim");
	pushSafePoint(&TMP2791);
	TMP2791.status = setjmp(TMP2791.context);
	if (TMP2791.status == 0) {
		NimStringDesc* res;
		NimStringDesc* LOC2;
		TY167666 LOC3;
		nimln(107, "usersystem.nim");
		LOC2 = 0;
		LOC2 = sql_167021(((NimStringDesc*) &TMP2792));
		memset((void*)LOC3, 0, sizeof(LOC3));
		LOC3[0] = nsuToUpperStr(name);
		res = getvalue_167577(db_282135, LOC2, LOC3, 1);
		nimln(108, "usersystem.nim");
		{
			NI row;
			if (!!(((res) && (res)->Sup.len == 0))) goto LA6;
			nimln(109, "usersystem.nim");
			row = nsuParseInt(res);
			nimln(110, "usersystem.nim");
			{
				if (!(((NI) 0) < row)) goto LA10;
				nimln(111, "usersystem.nim");
				result = NIM_TRUE;
			}
			goto LA8;
			LA10: ;
			{
				nimln(113, "usersystem.nim");
				result = NIM_FALSE;
			}
			LA8: ;
		}
		LA6: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			TMP2791.status = 0;
			nimln(115, "usersystem.nim");
			result = NIM_FALSE;
			popCurrentException();
		}
	}
	if (TMP2791.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getquote_282200)(NI id) {
	NimStringDesc* result;
	TY13606* row;
	NimStringDesc* LOC1;
	TY167666 LOC2;
	NimStringDesc* LOC7;
	nimfr("getQuote", "usersystem.nim")
{	result = 0;
	nimln(118, "usersystem.nim");
	LOC1 = 0;
	LOC1 = sql_167021(((NimStringDesc*) &TMP2793));
	memset((void*)LOC2, 0, sizeof(LOC2));
	LOC2[0] = nimIntToStr(id);
	row = getrow_167472(db_282135, LOC1, LOC2, 1);
	nimln(119, "usersystem.nim");
	{
		if ((NU)(((NI) 0)) >= (NU)(row->Sup.len)) raiseIndexError();
		if (!((row->data[((NI) 0)]) && (row->data[((NI) 0)])->Sup.len == 0)) goto LA5;
		nimln(120, "usersystem.nim");
		result = copyString(((NimStringDesc*) &TMP2762));
		goto BeforeRet;
	}
	LA5: ;
	nimln(121, "usersystem.nim");
	LOC7 = 0;
	if ((NU)(((NI) 0)) >= (NU)(row->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)(row->Sup.len)) raiseIndexError();
	LOC7 = rawNewString(row->data[((NI) 0)]->Sup.len + row->data[((NI) 1)]->Sup.len + 10);
appendString(LOC7, ((NimStringDesc*) &TMP2794));
appendString(LOC7, row->data[((NI) 0)]);
appendString(LOC7, ((NimStringDesc*) &TMP2795));
appendString(LOC7, row->data[((NI) 1)]);
	result = LOC7;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, addquote_282210)(NimStringDesc* content) {
	NI result;
	NimStringDesc* LOC1;
	TY167666 LOC2;
	NI64 LOC3;
	nimfr("addQuote", "usersystem.nim")
	result = 0;
	nimln(124, "usersystem.nim");
	LOC1 = 0;
	LOC1 = sql_167021(((NimStringDesc*) &TMP2796));
	memset((void*)LOC2, 0, sizeof(LOC2));
	LOC2[0] = copyString(content);
	LOC3 = 0;
	LOC3 = tryinsertid_167593(db_282135, LOC1, LOC2, 1);
	result = ((NI) (LOC3));
	popFrame();
	return result;
}

N_NIMCALL(NI, adduser_282220)(NimStringDesc* name, NimStringDesc* pass) {
	NI result;
	nimfr("addUser", "usersystem.nim")
{	result = 0;
	nimln(127, "usersystem.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC6;
		TY282225 LOC7;
		NI64 LOC8;
		LOC3 = 0;
		LOC3 = checkuser_282189(name);
		if (!!(LOC3)) goto LA4;
		nimln(128, "usersystem.nim");
		LOC6 = 0;
		LOC6 = sql_167021(((NimStringDesc*) &TMP2797));
		memset((void*)LOC7, 0, sizeof(LOC7));
		LOC7[0] = copyString(name);
		LOC7[1] = copyString(pass);
		LOC8 = 0;
		LOC8 = tryinsertid_167593(db_282135, LOC6, LOC7, 2);
		result = ((NI) (LOC8));
	}
	goto LA1;
	LA4: ;
	{
		nimln(130, "usersystem.nim");
		result = ((NI) -1);
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, getquotecount_282231)(void) {
	NI result;
	NimStringDesc* LOC1;
	TY161637 LOC2;
	NimStringDesc* LOC3;
	nimfr("getQuoteCount", "usersystem.nim")
	result = 0;
	nimln(133, "usersystem.nim");
	LOC1 = 0;
	LOC1 = sql_167021(((NimStringDesc*) &TMP2798));
	memset((void*)LOC2, 0, sizeof(LOC2));
	LOC3 = 0;
	LOC3 = getvalue_167577(db_282135, LOC1, LOC2, 0);
	result = nsuParseInt(LOC3);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, loginuser_282241)(NimStringDesc* name, NimStringDesc* pass) {
	NIM_BOOL result;
	NI row;
	NimStringDesc* LOC1;
	TY282225 LOC2;
	NimStringDesc* LOC3;
	nimfr("loginUser", "usersystem.nim")
	result = 0;
	nimln(138, "usersystem.nim");
	LOC1 = 0;
	LOC1 = sql_167021(((NimStringDesc*) &TMP2799));
	memset((void*)LOC2, 0, sizeof(LOC2));
	LOC2[0] = nsuToUpperStr(name);
	LOC2[1] = copyString(pass);
	LOC3 = 0;
	LOC3 = getvalue_167577(db_282135, LOC1, LOC2, 2);
	row = nsuParseInt(LOC3);
	nimln(139, "usersystem.nim");
	{
		if (!(((NI) 0) < row)) goto LA6;
		nimln(140, "usersystem.nim");
		result = NIM_TRUE;
	}
	goto LA4;
	LA6: ;
	{
		nimln(142, "usersystem.nim");
		result = NIM_FALSE;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, logoutuser_282252)(NimStringDesc* name) {
	NIM_BOOL result;
	nimfr("logoutUser", "usersystem.nim")
{	result = 0;
	nimln(146, "usersystem.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isloggedin_282152(name);
		if (!LOC3) goto LA4;
		{
			NI i_282268;
			NI HEX3Atmp_282341;
			NI res_282344;
			i_282268 = 0;
			HEX3Atmp_282341 = 0;
			nimln(147, "usersystem.nim");
			HEX3Atmp_282341 = (loggedin_282108 ? (loggedin_282108->Sup.len-1) : -1);
			nimln(1598, "system.nim");
			res_282344 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP2800;
					if (!(res_282344 <= HEX3Atmp_282341)) goto LA8;
					nimln(1600, "system.nim");
					i_282268 = res_282344;
					nimln(148, "usersystem.nim");
					{
						NI LOC11;
						if ((NU)(i_282268) >= (NU)(loggedin_282108->Sup.len)) raiseIndexError();
						LOC11 = 0;
						LOC11 = nsuCmpIgnoreCase(loggedin_282108->data[i_282268], name);
						if (!(LOC11 == ((NI) 0))) goto LA12;
						nimln(149, "usersystem.nim");
						delete_282270((&loggedin_282108), i_282268, i_282268);
						nimln(150, "usersystem.nim");
						result = NIM_TRUE;
						nimln(151, "usersystem.nim");
						goto BeforeRet;
					}
					LA12: ;
					nimln(1614, "system.nim");
					TMP2800 = addInt(res_282344, ((NI) 1));
					res_282344 = (NI)(TMP2800);
				} LA8: ;
			}
		}
	}
	LA4: ;
	nimln(152, "usersystem.nim");
	result = NIM_FALSE;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, upvote_282360)(NimStringDesc* name) {
	NI result;
	NimStringDesc* LOC1;
	TY167666 LOC2;
	NimStringDesc* totalvotes;
	NimStringDesc* LOC3;
	TY167666 LOC4;
	nimfr("upvote", "usersystem.nim")
	result = 0;
	nimln(156, "usersystem.nim");
	LOC1 = 0;
	LOC1 = sql_167021(((NimStringDesc*) &TMP2801));
	memset((void*)LOC2, 0, sizeof(LOC2));
	nimln(158, "usersystem.nim");
	LOC2[0] = nsuToUpperStr(name);
	exec_167155(db_282135, LOC1, LOC2, 1);
	nimln(159, "usersystem.nim");
	LOC3 = 0;
	LOC3 = sql_167021(((NimStringDesc*) &TMP2802));
	memset((void*)LOC4, 0, sizeof(LOC4));
	LOC4[0] = nsuToUpperStr(name);
	totalvotes = getvalue_167577(db_282135, LOC3, LOC4, 1);
	nimln(160, "usersystem.nim");
	{
		if (!((totalvotes) && (totalvotes)->Sup.len == 0)) goto LA7;
		nimln(161, "usersystem.nim");
		result = ((NI) -1);
	}
	goto LA5;
	LA7: ;
	{
		nimln(163, "usersystem.nim");
		result = nsuParseInt(totalvotes);
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, downvote_282372)(NimStringDesc* name) {
	NI result;
	NimStringDesc* LOC1;
	TY167666 LOC2;
	NimStringDesc* totalvotes;
	NimStringDesc* LOC3;
	TY167666 LOC4;
	nimfr("downvote", "usersystem.nim")
	result = 0;
	nimln(167, "usersystem.nim");
	LOC1 = 0;
	LOC1 = sql_167021(((NimStringDesc*) &TMP2803));
	memset((void*)LOC2, 0, sizeof(LOC2));
	nimln(169, "usersystem.nim");
	LOC2[0] = nsuToUpperStr(name);
	exec_167155(db_282135, LOC1, LOC2, 1);
	nimln(170, "usersystem.nim");
	LOC3 = 0;
	LOC3 = sql_167021(((NimStringDesc*) &TMP2802));
	memset((void*)LOC4, 0, sizeof(LOC4));
	LOC4[0] = nsuToUpperStr(name);
	totalvotes = getvalue_167577(db_282135, LOC3, LOC4, 1);
	nimln(171, "usersystem.nim");
	{
		if (!((totalvotes) && (totalvotes)->Sup.len == 0)) goto LA7;
		nimln(172, "usersystem.nim");
		result = ((NI) -1);
	}
	goto LA5;
	LA7: ;
	{
		nimln(174, "usersystem.nim");
		result = nsuParseInt(totalvotes);
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, karma_282384)(NimStringDesc* name) {
	NI volatile result;
	TSafePoint TMP2804;
	nimfr("karma", "usersystem.nim")
	result = 0;
	nimln(177, "usersystem.nim");
	pushSafePoint(&TMP2804);
	TMP2804.status = setjmp(TMP2804.context);
	if (TMP2804.status == 0) {
		NimStringDesc* LOC2;
		TY167666 LOC3;
		NimStringDesc* LOC4;
		nimln(178, "usersystem.nim");
		LOC2 = 0;
		LOC2 = sql_167021(((NimStringDesc*) &TMP2802));
		memset((void*)LOC3, 0, sizeof(LOC3));
		LOC3[0] = nsuToUpperStr(name);
		LOC4 = 0;
		LOC4 = getvalue_167577(db_282135, LOC2, LOC3, 1);
		result = nsuParseInt(LOC4);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			TMP2804.status = 0;
			nimln(180, "usersystem.nim");
			result = ((NI) -1);
			popCurrentException();
		}
	}
	if (TMP2804.status != 0) reraiseException();
	popFrame();
	return result;
}

static N_INLINE(void, writeln_282416)(FILE* f, NimStringDesc** x, NI xLen0) {
	nimfr("writeln", "sysio.nim")
	{
		NimStringDesc* i_282432;
		NI i_282440;
		i_282432 = 0;
		nimln(1689, "system.nim");
		i_282440 = ((NI) 0);
		{
			nimln(1690, "system.nim");
			while (1) {
				if (!(i_282440 < xLen0)) goto LA3;
				nimln(1691, "system.nim");
				i_282432 = x[i_282440];
				nimln(212, "sysio.nim");
				write_13457(f, i_282432);
				nimln(1692, "system.nim");
				i_282440 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln(213, "sysio.nim");
	write_13457(f, ((NimStringDesc*) &TMP2805));
	popFrame();
}

static N_INLINE(NI, randomint_277853)(Mtstate273035* rng, NI max) {
	NI result;
	NU LOC1;
	nimfr("randomInt", "common.nim")
	result = 0;
	nimln(102, "common.nim");
	nimln(103, "common.nim");
	LOC1 = 0;
	LOC1 = randomintimpl_277871(rng, ((NU) (max)));
	result = ((NI) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, randomint_279309)(Mtstate273035* rng, NI min, NI max) {
	NI result;
	NI TMP2883;
	NI LOC1;
	NI TMP2884;
	nimfr("randomInt", "common.nim")
	result = 0;
	nimln(106, "common.nim");
	nimln(107, "common.nim");
	TMP2883 = subInt(max, min);
	LOC1 = 0;
	LOC1 = randomint_277853(rng, ((NI)chckRange((NI)(TMP2883), ((NI) 1), ((NI) IL64(9223372036854775807)))));
	TMP2884 = addInt(min, ((NI) (LOC1)));
	result = (NI)(TMP2884);
	popFrame();
	return result;
}

static N_INLINE(NI, randomint_279271)(NI min, NI max) {
	NI result;
	nimfr("randomInt", "macros.nim")
	result = 0;
	nimln(404, "macros.nim");
	result = randomint_279309((&mersennetwisterinst_277010), min, max);
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_winleanDatInit();
	stdlib_timesDatInit();
	stdlib_osDatInit();
	stdlib_parseopt2DatInit();
	stdlib_unsignedDatInit();
	stdlib_socketsDatInit();
	stdlib_hashesDatInit();
	stdlib_strtabsDatInit();
	stdlib_streamsDatInit();
	stdlib_cpuinfoDatInit();
	stdlib_osprocDatInit();
	stdlib_sqlite3DatInit();
	stdlib_db_sqliteDatInit();
	stdlib_lexbaseDatInit();
	stdlib_unicodeDatInit();
	stdlib_macrosDatInit();
	stdlib_jsonDatInit();
	stdlib_typeinfoDatInit();
	stdlib_mathDatInit();
	stdlib_intsetsDatInit();
	stdlib_tablesDatInit();
	stdlib_marshalDatInit();
	stdlib_parsexmlDatInit();
	stdlib_rawsocketsDatInit();
	stdlib_netDatInit();
	stdlib_uriDatInit();
	stdlib_base64DatInit();
	stdlib_mimetypesDatInit();
	stdlib_endiansDatInit();
	stdlib_oidsDatInit();
	stdlib_setsDatInit();
	stdlib_asyncdispatchDatInit();
	stdlib_asyncnetDatInit();
	stdlib_httpclientDatInit();
	random_utilDatInit();
	random_random_realDatInit();
	random_commonDatInit();
	random_mt19937arDatInit();
	random_mersenneDatInit();
	random_urandomDatInit();
	random_randomDatInit();
	stdlib_sequtilsDatInit();
	nimbusDatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_winleanInit();
	stdlib_timesInit();
	stdlib_osInit();
	stdlib_parseopt2Init();
	stdlib_unsignedInit();
	stdlib_socketsInit();
	stdlib_hashesInit();
	stdlib_strtabsInit();
	stdlib_streamsInit();
	stdlib_cpuinfoInit();
	stdlib_osprocInit();
	stdlib_sqlite3Init();
	stdlib_db_sqliteInit();
	stdlib_lexbaseInit();
	stdlib_unicodeInit();
	stdlib_macrosInit();
	stdlib_jsonInit();
	stdlib_typeinfoInit();
	stdlib_mathInit();
	stdlib_intsetsInit();
	stdlib_tablesInit();
	stdlib_marshalInit();
	stdlib_parsexmlInit();
	stdlib_rawsocketsInit();
	stdlib_netInit();
	stdlib_uriInit();
	stdlib_base64Init();
	stdlib_mimetypesInit();
	stdlib_endiansInit();
	stdlib_oidsInit();
	stdlib_setsInit();
	stdlib_asyncdispatchInit();
	stdlib_asyncnetInit();
	stdlib_httpclientInit();
	random_utilInit();
	random_random_realInit();
	random_commonInit();
	random_mt19937arInit();
	random_mersenneInit();
	random_urandomInit();
	random_randomInit();
	stdlib_sequtilsInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	nimbusInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, nimbusInit)(void) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	TY161637 LOC6;
	NimStringDesc* LOC7;
	TY161637 LOC8;
	NimStringDesc* LOC9;
	TY161637 LOC10;
	NimStringDesc* LOC11;
	NimStringDesc* LOC12;
	NimStringDesc* LOC13;
	nimfr("nimbus", "nimbus.nim")
	nimln(40, "usersystem.nim");
	LOC1 = 0;
	LOC1 = server_282093; server_282093 = copyStringRC1(((NimStringDesc*) &TMP2760));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(41, "usersystem.nim");
	genericSeqAssign((&loggedin_282108), TMP2761, (&NTI13606));
	nimln(42, "usersystem.nim");
	port_282110 = ((NU16) 6667);
	nimln(43, "usersystem.nim");
	LOC2 = 0;
	LOC2 = username_282111; username_282111 = copyStringRC1(((NimStringDesc*) &TMP2764));
	if (LOC2) nimGCunrefNoCycle(LOC2);
	nimln(44, "usersystem.nim");
	LOC3 = 0;
	LOC3 = nick_282112; nick_282112 = copyStringRC1(((NimStringDesc*) &TMP2765));
	if (LOC3) nimGCunrefNoCycle(LOC3);
	nimln(45, "usersystem.nim");
	genericSeqAssign((&channels_282127), TMP2766, (&NTI13606));
	nimln(47, "usersystem.nim");
	islogging_282129 = NIM_FALSE;
	nimln(48, "usersystem.nim");
	outputting_282130 = NIM_TRUE;
	nimln(51, "usersystem.nim");
	asgnRefNoCycle((void**) (&sock_282133), socket_137604(((NU8) 2), ((NU8) 1), ((NU8) 6), NIM_TRUE));
	nimln(52, "usersystem.nim");
	LOC4 = 0;
	LOC4 = buffer_282134; buffer_282134 = copyStringRC1(((NimStringDesc*) &TMP2762));
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(56, "usersystem.nim");
	db_282135 = open_167645(((NimStringDesc*) &TMP2773), ((NimStringDesc*) &TMP2774), ((NimStringDesc*) &TMP2762), ((NimStringDesc*) &TMP2775));
	nimln(59, "usersystem.nim");
	LOC5 = 0;
	LOC5 = sql_167021(((NimStringDesc*) &TMP2776));
	memset((void*)LOC6, 0, sizeof(LOC6));
	exec_167155(db_282135, LOC5, LOC6, 0);
	nimln(65, "usersystem.nim");
	LOC7 = 0;
	LOC7 = sql_167021(((NimStringDesc*) &TMP2777));
	memset((void*)LOC8, 0, sizeof(LOC8));
	exec_167155(db_282135, LOC7, LOC8, 0);
	nimln(76, "usersystem.nim");
	LOC9 = 0;
	LOC9 = sql_167021(((NimStringDesc*) &TMP2778));
	memset((void*)LOC10, 0, sizeof(LOC10));
	exec_167155(db_282135, LOC9, LOC10, 0);
	nimln(85, "usersystem.nim");
	connect_142083(sock_282133, server_282093, port_282110, ((NU8) 2));
	nimln(87, "usersystem.nim");
	LOC11 = 0;
	LOC11 = rawNewString(nick_282112->Sup.len + 8);
appendString(LOC11, ((NimStringDesc*) &TMP2781));
appendString(LOC11, nick_282112);
appendString(LOC11, ((NimStringDesc*) &TMP2782));
	send_146407(sock_282133, LOC11);
	nimln(88, "usersystem.nim");
	LOC12 = 0;
	LOC12 = rawNewString(nick_282112->Sup.len + nick_282112->Sup.len + nick_282112->Sup.len + 20);
appendString(LOC12, ((NimStringDesc*) &TMP2783));
appendString(LOC12, nick_282112);
appendString(LOC12, ((NimStringDesc*) &TMP2784));
appendString(LOC12, nick_282112);
appendString(LOC12, ((NimStringDesc*) &TMP2784));
appendString(LOC12, nick_282112);
appendString(LOC12, ((NimStringDesc*) &TMP2785));
	send_146407(sock_282133, LOC12);
	nimln(89, "usersystem.nim");
	LOC13 = 0;
	LOC13 = rawNewString(nick_282112->Sup.len + 11);
appendString(LOC13, ((NimStringDesc*) &TMP2786));
appendString(LOC13, nick_282112);
appendString(LOC13, ((NimStringDesc*) &TMP2787));
	send_146407(sock_282133, LOC13);
	{
		nimln(13, "nimbus.nim");
		while (1) {
			nimln(14, "nimbus.nim");
			readline_145045(sock_282133, (&buffer_282134), ((NI) -1));
			nimln(16, "nimbus.nim");
			{
				TY167666 LOC20;
				if (!islogging_282129) goto LA18;
				nimln(17, "nimbus.nim");
				memset((void*)LOC20, 0, sizeof(LOC20));
				LOC20[0] = copyString(buffer_282134);
				writeln_282416(log_282128, LOC20, 1);
			}
			LA18: ;
			nimln(19, "nimbus.nim");
			{
				if (!outputting_282130) goto LA23;
				nimln(20, "nimbus.nim");
				printf("%s\015\012", buffer_282134? (buffer_282134)->data:"nil");
			}
			LA23: ;
			nimln(22, "nimbus.nim");
			{
				NimStringDesc* LOC27;
				LOC27 = 0;
				LOC27 = rawNewString(nick_282112->Sup.len + nick_282112->Sup.len + 11);
appendString(LOC27, ((NimStringDesc*) &TMP2836));
appendString(LOC27, nick_282112);
appendString(LOC27, ((NimStringDesc*) &TMP2837));
appendString(LOC27, nick_282112);
appendString(LOC27, ((NimStringDesc*) &TMP2838));
				if (!eqStrings(buffer_282134, LOC27)) goto LA28;
				nimln(23, "nimbus.nim");
				goto LA14;
			}
			LA28: ;
		}
	} LA14: ;
	{
		NI i_282478;
		NI L_282480;
		nimln(3084, "system.nim");
		i_282478 = ((NI) 0);
		nimln(3085, "system.nim");
		L_282480 = (channels_282127 ? channels_282127->Sup.len : 0);
		{
			nimln(3086, "system.nim");
			while (1) {
				NimStringDesc* LOC33;
				NimStringDesc* LOC34;
				NI TMP2840;
				if (!(i_282478 < L_282480)) goto LA32;
				nimln(3087, "system.nim");
				if ((NU)(i_282478) >= (NU)(channels_282127->Sup.len)) raiseIndexError();
				LOC33 = 0;
				LOC33 = channel_282474; channel_282474 = copyStringRC1(channels_282127->data[i_282478]);
				if (LOC33) nimGCunrefNoCycle(LOC33);
				nimln(26, "nimbus.nim");
				LOC34 = 0;
				LOC34 = rawNewString(channel_282474->Sup.len + 8);
appendString(LOC34, ((NimStringDesc*) &TMP2839));
appendString(LOC34, channel_282474);
appendString(LOC34, ((NimStringDesc*) &TMP2782));
				send_146407(sock_282133, LOC34);
				nimln(3088, "system.nim");
				TMP2840 = addInt(i_282478, ((NI) 1));
				i_282478 = (NI)(TMP2840);
				nimln(3089, "system.nim");
				{
					if (!!(((channels_282127 ? channels_282127->Sup.len : 0) == L_282480))) goto LA37;
					failedassertimpl_88817(((NimStringDesc*) &TMP2841));
				}
				LA37: ;
			} LA32: ;
		}
	}
	{
		nimln(28, "nimbus.nim");
		while (1) {
			TY13606* ircmsg;
			nimln(29, "nimbus.nim");
			readline_145045(sock_282133, (&buffer_282134), ((NI) -1));
			nimln(31, "nimbus.nim");
			{
				if (!((buffer_282134) && (buffer_282134)->Sup.len == 0)) goto LA43;
				nimln(32, "nimbus.nim");
				printf("%s\015\012", ((NimStringDesc*) &TMP2845)? (((NimStringDesc*) &TMP2845))->data:"nil");
				nimln(33, "nimbus.nim");
				goto LA39;
			}
			LA43: ;
			nimln(35, "nimbus.nim");
			{
				TY167666 LOC49;
				if (!islogging_282129) goto LA47;
				nimln(36, "nimbus.nim");
				memset((void*)LOC49, 0, sizeof(LOC49));
				LOC49[0] = copyString(buffer_282134);
				writeln_282416(log_282128, LOC49, 1);
			}
			LA47: ;
			nimln(38, "nimbus.nim");
			ircmsg = nsuSplitString(buffer_282134, ((NimStringDesc*) &TMP2784));
			nimln(40, "nimbus.nim");
			{
				NimStringDesc* LOC54;
				if (!outputting_282130) goto LA52;
				nimln(41, "nimbus.nim");
				LOC54 = 0;
				LOC54 = HEX24_282510(ircmsg);
				printf("%s\015\012", LOC54? (LOC54)->data:"nil");
			}
			LA52: ;
			nimln(43, "nimbus.nim");
			{
				NimStringDesc* LOC59;
				if ((NU)(((NI) 0)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
				if (!eqStrings(ircmsg->data[((NI) 0)], ((NimStringDesc*) &TMP2850))) goto LA57;
				nimln(44, "nimbus.nim");
				LOC59 = 0;
				if ((NU)(((NI) 1)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
				LOC59 = rawNewString(ircmsg->data[((NI) 1)]->Sup.len + 8);
appendString(LOC59, ((NimStringDesc*) &TMP2851));
appendString(LOC59, ircmsg->data[((NI) 1)]);
appendString(LOC59, ((NimStringDesc*) &TMP2782));
				send_146407(sock_282133, LOC59);
			}
			goto LA55;
			LA57: ;
			{
				NimStringDesc* nick;
				nimln(46, "nimbus.nim");
				if ((NU)(((NI) 1)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
				if (!eqStrings(ircmsg->data[((NI) 1)], ((NimStringDesc*) &TMP2852))) goto LA61;
				nimln(47, "nimbus.nim");
				if ((NU)(((NI) 0)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
				nick = getnick_282076(ircmsg->data[((NI) 0)]);
				nimln(48, "nimbus.nim");
				{
					NIM_BOOL LOC65;
					NIM_BOOL LOC68;
					LOC65 = 0;
					LOC65 = isloggedin_282152(nick);
					if (!LOC65) goto LA66;
					nimln(49, "nimbus.nim");
					LOC68 = 0;
					LOC68 = logoutuser_282252(nick);
				}
				LA66: ;
			}
			goto LA55;
			LA61: ;
			{
				NimStringDesc* nick;
				nimln(51, "nimbus.nim");
				if ((NU)(((NI) 1)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
				if (!eqStrings(ircmsg->data[((NI) 1)], ((NimStringDesc*) &TMP2853))) goto LA70;
				nimln(52, "nimbus.nim");
				if ((NU)(((NI) 0)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
				nick = getnick_282076(ircmsg->data[((NI) 0)]);
				nimln(56, "nimbus.nim");
				{
					NimStringDesc* LOC76;
					NimStringDesc* LOC77;
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2854))) goto LA74;
					nimln(57, "nimbus.nim");
					LOC76 = 0;
					if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC77 = 0;
					LOC77 = about_282013();
					LOC76 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + LOC77->Sup.len + 13);
appendString(LOC76, ((NimStringDesc*) &TMP2855));
appendString(LOC76, ircmsg->data[((NI) 2)]);
appendString(LOC76, ((NimStringDesc*) &TMP2856));
appendString(LOC76, LOC77);
appendString(LOC76, ((NimStringDesc*) &TMP2782));
					send_146407(sock_282133, LOC76);
				}
				LA74: ;
				nimln(60, "nimbus.nim");
				{
					NIM_BOOL LOC80;
					NIM_BOOL LOC81;
					NimStringDesc* LOC84;
					NimStringDesc* filename;
					FILE* outhandle;
					NimStringDesc* result;
					TY164210 resultinitial;
					NimStringDesc* LOC103;
					NimStringDesc* LOC117;
					LOC80 = 0;
					LOC81 = 0;
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC81 = eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2857));
					if (!(LOC81)) goto LA82;
					LOC81 = isloggedin_282152(((NimStringDesc*) &TMP2858));
					LA82: ;
					LOC80 = LOC81;
					if (!(LOC80)) goto LA83;
					LOC84 = 0;
					LOC84 = nsuToLowerStr(nick);
					LOC80 = eqStrings(LOC84, ((NimStringDesc*) &TMP2859));
					LA83: ;
					if (!LOC80) goto LA85;
					nimln(61, "nimbus.nim");
					filename = copyString(((NimStringDesc*) &TMP2860));
					nimln(62, "nimbus.nim");
					outhandle = open_13217(filename, ((NU8) 1), ((NI) -1));
					result = 0;
					nimln(65, "nimbus.nim");
					writeln_282416(outhandle, TMP2861, 1);
					{
						NimStringDesc* HEX3Atmp_282884;
						Slice88061 LOC88;
						TY13606* LOC89;
						NI last_282888;
						asgnRefNoCycle((void**) (&line_282601), NIM_NIL);
						HEX3Atmp_282884 = 0;
						nimln(66, "nimbus.nim");
						LOC88 = HEX2EHEX2E_110273(((NI) 4), (ircmsg ? (ircmsg->Sup.len-1) : -1));
						LOC89 = 0;
						LOC89 = HEX5BHEX5D_133598(ircmsg, LOC88);
						HEX3Atmp_282884 = nsuJoinSep(LOC89->data, LOC89->Sup.len, ((NimStringDesc*) &TMP2784));
						nimln(293, "strutils.nim");
						last_282888 = ((NI) 0);
						nimln(294, "strutils.nim");
						{
							if (!(((NI) 0) < (HEX3Atmp_282884 ? HEX3Atmp_282884->Sup.len : 0))) goto LA92;
							{
								nimln(295, "strutils.nim");
								while (1) {
									NI first_282890;
									NI TMP2866;
									TY167666 LOC101;
									NimStringDesc* LOC102;
									NI TMP2867;
									if (!(last_282888 <= (HEX3Atmp_282884 ? HEX3Atmp_282884->Sup.len : 0))) goto LA95;
									nimln(296, "strutils.nim");
									first_282890 = last_282888;
									{
										nimln(297, "strutils.nim");
										while (1) {
											NIM_BOOL LOC98;
											NI TMP2863;
											NimStringDesc* LOC100;
											NI TMP2865;
											LOC98 = 0;
											LOC98 = (last_282888 < (HEX3Atmp_282884 ? HEX3Atmp_282884->Sup.len : 0));
											if (!(LOC98)) goto LA99;
											TMP2863 = addInt(last_282888, ((NI) 0));
											LOC100 = 0;
											LOC100 = copyStrLast(HEX3Atmp_282884, last_282888, (NI)(TMP2863));
											LOC98 = !(eqStrings(LOC100, ((NimStringDesc*) &TMP2864)));
											LA99: ;
											if (!LOC98) goto LA97;
											nimln(298, "strutils.nim");
											TMP2865 = addInt(last_282888, ((NI) 1));
											last_282888 = (NI)(TMP2865);
										} LA97: ;
									}
									nimln(299, "strutils.nim");
									TMP2866 = subInt(last_282888, ((NI) 1));
									asgnRefNoCycle((void**) (&line_282601), copyStrLast(HEX3Atmp_282884, first_282890, (NI)(TMP2866)));
									nimln(67, "nimbus.nim");
									memset((void*)LOC101, 0, sizeof(LOC101));
									LOC102 = 0;
									LOC102 = rawNewString(line_282601->Sup.len + 1);
appendString(LOC102, ((NimStringDesc*) &TMP2784));
appendString(LOC102, line_282601);
									LOC101[0] = LOC102;
									writeln_282416(outhandle, LOC101, 1);
									nimln(300, "strutils.nim");
									TMP2867 = addInt(last_282888, ((NI) 1));
									last_282888 = (NI)(TMP2867);
								} LA95: ;
							}
						}
						LA92: ;
					}
					nimln(68, "nimbus.nim");
					writeln_282416(outhandle, TMP2868, 1);
					nimln(69, "nimbus.nim");
					writeln_282416(outhandle, TMP2870, 1);
					nimln(70, "nimbus.nim");
					fclose(outhandle);
					memset((void*)(&resultinitial), 0, sizeof(resultinitial));
					nimln(72, "nimbus.nim");
					LOC103 = 0;
					LOC103 = rawNewString(filename->Sup.len + 276);
appendString(LOC103, ((NimStringDesc*) &TMP2872));
appendString(LOC103, filename);
					chckNil((void*)(&resultinitial));
					memset((void*)(&resultinitial), 0, sizeof(resultinitial));
					execcmdex_164204(LOC103, 10, (&resultinitial));
					nimln(74, "nimbus.nim");
					{
						TY164210 resultsecond;
						NimStringDesc* LOC108;
						NI TMP2874;
						NI TMP2875;
						Slice88061 LOC109;
						NimStringDesc* LOC110;
						if (!((resultinitial.Field0) && (resultinitial.Field0)->Sup.len == 0)) goto LA106;
						memset((void*)(&resultsecond), 0, sizeof(resultsecond));
						nimln(75, "nimbus.nim");
						LOC108 = 0;
						TMP2874 = subInt((filename ? filename->Sup.len : 0), ((NI) 4));
						TMP2875 = subInt((NI)(TMP2874), ((NI) 1));
						LOC109 = HEX2EHEX2E_110273(((NI) 0), (NI)(TMP2875));
						LOC110 = 0;
						LOC110 = HEX5BHEX5D_88054(filename, LOC109);
						LOC108 = rawNewString(LOC110->Sup.len + 2);
appendString(LOC108, ((NimStringDesc*) &TMP2873));
appendString(LOC108, LOC110);
						chckNil((void*)(&resultsecond));
						memset((void*)(&resultsecond), 0, sizeof(resultsecond));
						execcmdex_164204(LOC108, 10, (&resultsecond));
						nimln(77, "nimbus.nim");
						{
							if (!((resultsecond.Field0) && (resultsecond.Field0)->Sup.len == 0)) goto LA113;
							nimln(78, "nimbus.nim");
							result = copyString(((NimStringDesc*) &TMP2876));
						}
						goto LA111;
						LA113: ;
						{
							nimln(81, "nimbus.nim");
							result = copyString(resultsecond.Field0);
						}
						LA111: ;
					}
					goto LA104;
					LA106: ;
					{
						nimln(84, "nimbus.nim");
						result = copyString(resultinitial.Field0);
					}
					LA104: ;
					nimln(86, "nimbus.nim");
					LOC117 = 0;
					if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC117 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + nick->Sup.len + result->Sup.len + 15);
appendString(LOC117, ((NimStringDesc*) &TMP2855));
appendString(LOC117, ircmsg->data[((NI) 2)]);
appendString(LOC117, ((NimStringDesc*) &TMP2856));
appendString(LOC117, nick);
appendString(LOC117, ((NimStringDesc*) &TMP2877));
appendString(LOC117, result);
appendString(LOC117, ((NimStringDesc*) &TMP2782));
					send_146407(sock_282133, LOC117);
				}
				LA85: ;
				nimln(88, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2878))) goto LA120;
					nimln(89, "nimbus.nim");
					{
						NimStringDesc* LOC126;
						if (!((ircmsg ? (ircmsg->Sup.len-1) : -1) < ((NI) 4))) goto LA124;
						nimln(90, "nimbus.nim");
						LOC126 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC126 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 41);
appendString(LOC126, ((NimStringDesc*) &TMP2855));
appendString(LOC126, ircmsg->data[((NI) 2)]);
appendString(LOC126, ((NimStringDesc*) &TMP2879));
						send_146407(sock_282133, LOC126);
					}
					goto LA122;
					LA124: ;
					{
						NimStringDesc* formula;
						TY13606* formula2;
						TSafePoint TMP2881;
						nimln(92, "nimbus.nim");
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						formula = copyString(ircmsg->data[((NI) 4)]);
						nimln(93, "nimbus.nim");
						formula2 = nsuSplitCharSet(formula, TMP2880);
						nimln(94, "nimbus.nim");
						pushSafePoint(&TMP2881);
						TMP2881.status = setjmp(TMP2881.context);
						if (TMP2881.status == 0) {
							NI volatile diceresult;
							diceresult = 0;
							nimln(96, "nimbus.nim");
							diceresult = ((NI) 0);
							nimln(97, "nimbus.nim");
							{
								NI LOC131;
								NimStringDesc* LOC134;
								if ((NU)(((NI) 0)) >= (NU)(formula2->Sup.len)) raiseIndexError();
								LOC131 = 0;
								LOC131 = nsuParseInt(formula2->data[((NI) 0)]);
								if (!(((NI) 200) < LOC131)) goto LA132;
								nimln(98, "nimbus.nim");
								LOC134 = 0;
								if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
								LOC134 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 68);
appendString(LOC134, ((NimStringDesc*) &TMP2855));
appendString(LOC134, ircmsg->data[((NI) 2)]);
appendString(LOC134, ((NimStringDesc*) &TMP2882));
								send_146407(sock_282133, LOC134);
							}
							goto LA129;
							LA132: ;
							{
								NimStringDesc* LOC141;
								NimStringDesc* LOC142;
								{
									NI HEX3Atmp_282893;
									NI res_282896;
									i_282667 = 0;
									HEX3Atmp_282893 = 0;
									nimln(100, "nimbus.nim");
									if ((NU)(((NI) 0)) >= (NU)(formula2->Sup.len)) raiseIndexError();
									HEX3Atmp_282893 = nsuParseInt(formula2->data[((NI) 0)]);
									nimln(1598, "system.nim");
									res_282896 = ((NI) 1);
									{
										nimln(1599, "system.nim");
										while (1) {
											NI LOC139;
											NI TMP2885;
											NI LOC140;
											NI TMP2886;
											NI TMP2887;
											if (!(res_282896 <= HEX3Atmp_282893)) goto LA138;
											nimln(1600, "system.nim");
											i_282667 = res_282896;
											nimln(101, "nimbus.nim");
											if ((NU)(((NI) 1)) >= (NU)(formula2->Sup.len)) raiseIndexError();
											LOC139 = 0;
											LOC139 = nsuParseInt(formula2->data[((NI) 1)]);
											TMP2885 = addInt(LOC139, ((NI) 1));
											LOC140 = 0;
											LOC140 = randomint_279271(((NI) 1), (NI)(TMP2885));
											TMP2886 = addInt(diceresult, LOC140);
											diceresult = (NI)(TMP2886);
											nimln(1614, "system.nim");
											TMP2887 = addInt(res_282896, ((NI) 1));
											res_282896 = (NI)(TMP2887);
										} LA138: ;
									}
								}
								nimln(102, "nimbus.nim");
								LOC141 = 0;
								if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
								LOC142 = 0;
								LOC142 = nimIntToStr(diceresult);
								LOC141 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + nick->Sup.len + LOC142->Sup.len + 25);
appendString(LOC141, ((NimStringDesc*) &TMP2855));
appendString(LOC141, ircmsg->data[((NI) 2)]);
appendString(LOC141, ((NimStringDesc*) &TMP2856));
appendString(LOC141, nick);
appendString(LOC141, ((NimStringDesc*) &TMP2888));
appendString(LOC141, LOC142);
appendString(LOC141, ((NimStringDesc*) &TMP2889));
								send_146407(sock_282133, LOC141);
							}
							LA129: ;
							popSafePoint();
						}
						else {
							popSafePoint();
							setFrame((TFrame*)&FR);
							{
								NimStringDesc* LOC145;
								TMP2881.status = 0;
								nimln(104, "nimbus.nim");
								LOC145 = 0;
								if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
								LOC145 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 62);
appendString(LOC145, ((NimStringDesc*) &TMP2855));
appendString(LOC145, ircmsg->data[((NI) 2)]);
appendString(LOC145, ((NimStringDesc*) &TMP2890));
								send_146407(sock_282133, LOC145);
								popCurrentException();
							}
						}
						if (TMP2881.status != 0) reraiseException();
					}
					LA122: ;
				}
				LA120: ;
				nimln(107, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2891))) goto LA148;
					nimln(108, "nimbus.nim");
					{
						NIM_BOOL LOC152;
						NIM_BOOL LOC153;
						NimStringDesc* LOC156;
						NimStringDesc* LOC157;
						NimStringDesc* LOC160;
						NI LOC161;
						NimStringDesc* LOC162;
						LOC152 = 0;
						LOC153 = 0;
						LOC153 = (((NI) 4) <= (ircmsg ? (ircmsg->Sup.len-1) : -1));
						if (!(LOC153)) goto LA154;
						LOC153 = isloggedin_282152(nick);
						LA154: ;
						LOC152 = LOC153;
						if (!(LOC152)) goto LA155;
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC156 = 0;
						LOC156 = nsuToUpperStr(ircmsg->data[((NI) 4)]);
						LOC157 = 0;
						LOC157 = nsuToUpperStr(nick);
						LOC152 = !(eqStrings(LOC156, LOC157));
						LA155: ;
						if (!LOC152) goto LA158;
						nimln(109, "nimbus.nim");
						LOC160 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC161 = 0;
						LOC161 = upvote_282360(ircmsg->data[((NI) 4)]);
						LOC162 = 0;
						LOC162 = nimIntToStr(LOC161);
						LOC160 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + ircmsg->data[((NI) 4)]->Sup.len + LOC162->Sup.len + 55);
appendString(LOC160, ((NimStringDesc*) &TMP2855));
appendString(LOC160, ircmsg->data[((NI) 2)]);
appendString(LOC160, ((NimStringDesc*) &TMP2892));
appendString(LOC160, ircmsg->data[((NI) 4)]);
appendString(LOC160, ((NimStringDesc*) &TMP2893));
appendString(LOC160, LOC162);
appendString(LOC160, ((NimStringDesc*) &TMP2894));
						send_146407(sock_282133, LOC160);
					}
					goto LA150;
					LA158: ;
					{
						NimStringDesc* LOC164;
						nimln(111, "nimbus.nim");
						LOC164 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC164 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 118);
appendString(LOC164, ((NimStringDesc*) &TMP2855));
appendString(LOC164, ircmsg->data[((NI) 2)]);
appendString(LOC164, ((NimStringDesc*) &TMP2895));
						send_146407(sock_282133, LOC164);
					}
					LA150: ;
				}
				LA148: ;
				nimln(114, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2896))) goto LA167;
					nimln(115, "nimbus.nim");
					{
						NIM_BOOL LOC171;
						NIM_BOOL LOC172;
						NimStringDesc* LOC175;
						NimStringDesc* LOC176;
						NimStringDesc* LOC179;
						NI LOC180;
						NimStringDesc* LOC181;
						LOC171 = 0;
						LOC172 = 0;
						LOC172 = (((NI) 4) <= (ircmsg ? (ircmsg->Sup.len-1) : -1));
						if (!(LOC172)) goto LA173;
						LOC172 = isloggedin_282152(nick);
						LA173: ;
						LOC171 = LOC172;
						if (!(LOC171)) goto LA174;
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC175 = 0;
						LOC175 = nsuToUpperStr(ircmsg->data[((NI) 4)]);
						LOC176 = 0;
						LOC176 = nsuToUpperStr(nick);
						LOC171 = !(eqStrings(LOC175, LOC176));
						LA174: ;
						if (!LOC171) goto LA177;
						nimln(116, "nimbus.nim");
						LOC179 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC180 = 0;
						LOC180 = downvote_282372(ircmsg->data[((NI) 4)]);
						LOC181 = 0;
						LOC181 = nimIntToStr(LOC180);
						LOC179 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + ircmsg->data[((NI) 4)]->Sup.len + LOC181->Sup.len + 57);
appendString(LOC179, ((NimStringDesc*) &TMP2855));
appendString(LOC179, ircmsg->data[((NI) 2)]);
appendString(LOC179, ((NimStringDesc*) &TMP2897));
appendString(LOC179, ircmsg->data[((NI) 4)]);
appendString(LOC179, ((NimStringDesc*) &TMP2893));
appendString(LOC179, LOC181);
appendString(LOC179, ((NimStringDesc*) &TMP2894));
						send_146407(sock_282133, LOC179);
					}
					goto LA169;
					LA177: ;
					{
						NimStringDesc* LOC183;
						nimln(118, "nimbus.nim");
						LOC183 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC183 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 122);
appendString(LOC183, ((NimStringDesc*) &TMP2855));
appendString(LOC183, ircmsg->data[((NI) 2)]);
appendString(LOC183, ((NimStringDesc*) &TMP2898));
						send_146407(sock_282133, LOC183);
					}
					LA169: ;
				}
				LA167: ;
				nimln(121, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2899))) goto LA186;
					nimln(122, "nimbus.nim");
					{
						NIM_BOOL LOC190;
						NimStringDesc* LOC194;
						NI LOC195;
						NimStringDesc* LOC196;
						LOC190 = 0;
						LOC190 = (((NI) 4) <= (ircmsg ? (ircmsg->Sup.len-1) : -1));
						if (!(LOC190)) goto LA191;
						LOC190 = isloggedin_282152(nick);
						LA191: ;
						if (!LOC190) goto LA192;
						nimln(123, "nimbus.nim");
						LOC194 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC195 = 0;
						LOC195 = karma_282384(ircmsg->data[((NI) 4)]);
						LOC196 = 0;
						LOC196 = nimIntToStr(LOC195);
						LOC194 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + ircmsg->data[((NI) 4)]->Sup.len + LOC196->Sup.len + 36);
appendString(LOC194, ((NimStringDesc*) &TMP2855));
appendString(LOC194, ircmsg->data[((NI) 2)]);
appendString(LOC194, ((NimStringDesc*) &TMP2856));
appendString(LOC194, ircmsg->data[((NI) 4)]);
appendString(LOC194, ((NimStringDesc*) &TMP2900));
appendString(LOC194, LOC196);
appendString(LOC194, ((NimStringDesc*) &TMP2894));
						send_146407(sock_282133, LOC194);
					}
					LA192: ;
				}
				LA186: ;
				nimln(126, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2901))) goto LA199;
					nimln(127, "nimbus.nim");
					{
						NimStringDesc* LOC205;
						if (!((ircmsg ? (ircmsg->Sup.len-1) : -1) < ((NI) 4))) goto LA203;
						nimln(128, "nimbus.nim");
						LOC205 = 0;
						LOC205 = rawNewString(nick->Sup.len + 39);
appendString(LOC205, ((NimStringDesc*) &TMP2855));
appendString(LOC205, nick);
appendString(LOC205, ((NimStringDesc*) &TMP2902));
						send_146407(sock_282133, LOC205);
					}
					goto LA201;
					LA203: ;
					{
						nimln(130, "nimbus.nim");
						{
							NIM_BOOL LOC209;
							NimStringDesc* LOC212;
							NimStringDesc* LOC213;
							if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
							LOC209 = 0;
							LOC209 = loginuser_282241(nick, ircmsg->data[((NI) 4)]);
							if (!LOC209) goto LA210;
							nimln(131, "nimbus.nim");
							loggedin_282108 = (TY13606*) incrSeq(&(loggedin_282108)->Sup, sizeof(NimStringDesc*));
							LOC212 = 0;
							LOC212 = loggedin_282108->data[loggedin_282108->Sup.len-1]; loggedin_282108->data[loggedin_282108->Sup.len-1] = copyStringRC1(nick);
							if (LOC212) nimGCunrefNoCycle(LOC212);
							nimln(132, "nimbus.nim");
							LOC213 = 0;
							LOC213 = rawNewString(nick->Sup.len + 47);
appendString(LOC213, ((NimStringDesc*) &TMP2855));
appendString(LOC213, nick);
appendString(LOC213, ((NimStringDesc*) &TMP2903));
							send_146407(sock_282133, LOC213);
						}
						goto LA207;
						LA210: ;
						{
							NimStringDesc* LOC215;
							nimln(134, "nimbus.nim");
							LOC215 = 0;
							LOC215 = rawNewString(nick->Sup.len + 32);
appendString(LOC215, ((NimStringDesc*) &TMP2855));
appendString(LOC215, nick);
appendString(LOC215, ((NimStringDesc*) &TMP2904));
							send_146407(sock_282133, LOC215);
						}
						LA207: ;
					}
					LA201: ;
				}
				LA199: ;
				nimln(137, "nimbus.nim");
				{
					NIM_BOOL LOC220;
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2905))) goto LA218;
					nimln(138, "nimbus.nim");
					LOC220 = 0;
					LOC220 = logoutuser_282252(nick);
				}
				LA218: ;
				nimln(141, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2906))) goto LA223;
					nimln(142, "nimbus.nim");
					{
						if (!((ircmsg ? (ircmsg->Sup.len-1) : -1) == ((NI) 4))) goto LA227;
						nimln(143, "nimbus.nim");
						{
							NI LOC231;
							NimStringDesc* LOC234;
							if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
							LOC231 = 0;
							LOC231 = adduser_282220(nick, ircmsg->data[((NI) 4)]);
							if (!(((NI) 0) < LOC231)) goto LA232;
							nimln(144, "nimbus.nim");
							LOC234 = 0;
							if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
							LOC234 = rawNewString(nick->Sup.len + ircmsg->data[((NI) 4)]->Sup.len + 28);
appendString(LOC234, ((NimStringDesc*) &TMP2855));
appendString(LOC234, nick);
appendString(LOC234, ((NimStringDesc*) &TMP2907));
appendString(LOC234, ircmsg->data[((NI) 4)]);
appendString(LOC234, ((NimStringDesc*) &TMP2908));
							send_146407(sock_282133, LOC234);
						}
						goto LA229;
						LA232: ;
						{
							NimStringDesc* LOC236;
							nimln(146, "nimbus.nim");
							LOC236 = 0;
							LOC236 = rawNewString(nick->Sup.len + 33);
appendString(LOC236, ((NimStringDesc*) &TMP2855));
appendString(LOC236, nick);
appendString(LOC236, ((NimStringDesc*) &TMP2909));
							send_146407(sock_282133, LOC236);
						}
						LA229: ;
					}
					goto LA225;
					LA227: ;
					{
						NI pass;
						nimln(148, "nimbus.nim");
						pass = randomint_279271(((NI) 10000), ((NI) 99999));
						nimln(149, "nimbus.nim");
						{
							NimStringDesc* LOC240;
							NI LOC241;
							NimStringDesc* LOC244;
							NimStringDesc* LOC245;
							LOC240 = 0;
							LOC240 = nimIntToStr(pass);
							LOC241 = 0;
							LOC241 = adduser_282220(nick, LOC240);
							if (!(((NI) 0) < LOC241)) goto LA242;
							nimln(150, "nimbus.nim");
							LOC244 = 0;
							LOC245 = 0;
							LOC245 = nimIntToStr(pass);
							LOC244 = rawNewString(nick->Sup.len + LOC245->Sup.len + 47);
appendString(LOC244, ((NimStringDesc*) &TMP2855));
appendString(LOC244, nick);
appendString(LOC244, ((NimStringDesc*) &TMP2910));
appendString(LOC244, LOC245);
appendString(LOC244, ((NimStringDesc*) &TMP2908));
							send_146407(sock_282133, LOC244);
						}
						goto LA238;
						LA242: ;
						{
							NimStringDesc* LOC247;
							nimln(152, "nimbus.nim");
							LOC247 = 0;
							LOC247 = rawNewString(nick->Sup.len + 33);
appendString(LOC247, ((NimStringDesc*) &TMP2855));
appendString(LOC247, nick);
appendString(LOC247, ((NimStringDesc*) &TMP2909));
							send_146407(sock_282133, LOC247);
						}
						LA238: ;
					}
					LA225: ;
				}
				LA223: ;
				nimln(155, "nimbus.nim");
				{
					NimStringDesc* LOC252;
					NimStringDesc* LOC253;
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2911))) goto LA250;
					nimln(156, "nimbus.nim");
					LOC252 = 0;
					if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC252 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 85);
appendString(LOC252, ((NimStringDesc*) &TMP2855));
appendString(LOC252, ircmsg->data[((NI) 2)]);
appendString(LOC252, ((NimStringDesc*) &TMP2912));
					send_146407(sock_282133, LOC252);
					nimln(157, "nimbus.nim");
					LOC253 = 0;
					if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC253 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 59);
appendString(LOC253, ((NimStringDesc*) &TMP2855));
appendString(LOC253, ircmsg->data[((NI) 2)]);
appendString(LOC253, ((NimStringDesc*) &TMP2913));
					send_146407(sock_282133, LOC253);
				}
				LA250: ;
				nimln(160, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2914))) goto LA256;
					nimln(161, "nimbus.nim");
					{
						TSafePoint TMP2915;
						if (!(((NI) 4) <= (ircmsg ? (ircmsg->Sup.len-1) : -1))) goto LA260;
						nimln(162, "nimbus.nim");
						pushSafePoint(&TMP2915);
						TMP2915.status = setjmp(TMP2915.context);
						if (TMP2915.status == 0) {
							NimStringDesc* LOC263;
							NI LOC264;
							NimStringDesc* LOC265;
							nimln(163, "nimbus.nim");
							LOC263 = 0;
							if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
							if ((NU)(((NI) 4)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
							LOC264 = 0;
							LOC264 = nsuParseInt(ircmsg->data[((NI) 4)]);
							LOC265 = 0;
							LOC265 = getquote_282200(LOC264);
							LOC263 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + LOC265->Sup.len + 13);
appendString(LOC263, ((NimStringDesc*) &TMP2855));
appendString(LOC263, ircmsg->data[((NI) 2)]);
appendString(LOC263, ((NimStringDesc*) &TMP2856));
appendString(LOC263, LOC265);
appendString(LOC263, ((NimStringDesc*) &TMP2782));
							send_146407(sock_282133, LOC263);
							popSafePoint();
						}
						else {
							popSafePoint();
							setFrame((TFrame*)&FR);
							{
								NimStringDesc* LOC268;
								TMP2915.status = 0;
								nimln(165, "nimbus.nim");
								LOC268 = 0;
								if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
								LOC268 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 31);
appendString(LOC268, ((NimStringDesc*) &TMP2855));
appendString(LOC268, ircmsg->data[((NI) 2)]);
appendString(LOC268, ((NimStringDesc*) &TMP2916));
								send_146407(sock_282133, LOC268);
								popCurrentException();
							}
						}
						if (TMP2915.status != 0) reraiseException();
					}
					goto LA258;
					LA260: ;
					{
						NimStringDesc* LOC270;
						NI LOC271;
						NI TMP2917;
						NI LOC272;
						NimStringDesc* LOC273;
						nimln(167, "nimbus.nim");
						LOC270 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC271 = 0;
						LOC271 = getquotecount_282231();
						TMP2917 = addInt(LOC271, ((NI) 1));
						LOC272 = 0;
						LOC272 = randomint_279271(((NI) 1), (NI)(TMP2917));
						LOC273 = 0;
						LOC273 = getquote_282200(LOC272);
						LOC270 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + LOC273->Sup.len + 13);
appendString(LOC270, ((NimStringDesc*) &TMP2855));
appendString(LOC270, ircmsg->data[((NI) 2)]);
appendString(LOC270, ((NimStringDesc*) &TMP2856));
appendString(LOC270, LOC273);
appendString(LOC270, ((NimStringDesc*) &TMP2782));
						send_146407(sock_282133, LOC270);
					}
					LA258: ;
				}
				LA256: ;
				nimln(170, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2918))) goto LA276;
					nimln(171, "nimbus.nim");
					{
						NI id;
						Slice88061 LOC282;
						TY13606* LOC283;
						NimStringDesc* LOC284;
						NimStringDesc* LOC285;
						NimStringDesc* LOC286;
						if (!(((NI) 4) <= (ircmsg ? (ircmsg->Sup.len-1) : -1))) goto LA280;
						nimln(172, "nimbus.nim");
						LOC282 = HEX2EHEX2E_110273(((NI) 4), (ircmsg ? (ircmsg->Sup.len-1) : -1));
						LOC283 = 0;
						LOC283 = HEX5BHEX5D_133598(ircmsg, LOC282);
						LOC284 = 0;
						LOC284 = nsuJoinSep(LOC283->data, LOC283->Sup.len, ((NimStringDesc*) &TMP2784));
						id = addquote_282210(LOC284);
						nimln(173, "nimbus.nim");
						LOC285 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC286 = 0;
						LOC286 = nimIntToStr(id);
						LOC285 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + LOC286->Sup.len + 27);
appendString(LOC285, ((NimStringDesc*) &TMP2855));
appendString(LOC285, ircmsg->data[((NI) 2)]);
appendString(LOC285, ((NimStringDesc*) &TMP2919));
appendString(LOC285, LOC286);
appendString(LOC285, ((NimStringDesc*) &TMP2920));
						send_146407(sock_282133, LOC285);
					}
					goto LA278;
					LA280: ;
					{
						NimStringDesc* LOC288;
						nimln(175, "nimbus.nim");
						LOC288 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC288 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 34);
appendString(LOC288, ((NimStringDesc*) &TMP2855));
appendString(LOC288, ircmsg->data[((NI) 2)]);
appendString(LOC288, ((NimStringDesc*) &TMP2921));
						send_146407(sock_282133, LOC288);
					}
					LA278: ;
				}
				LA276: ;
				nimln(178, "nimbus.nim");
				{
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					if (!eqStrings(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2922))) goto LA291;
					nimln(179, "nimbus.nim");
					{
						NIM_BOOL LOC295;
						NIM_BOOL LOC296;
						NimStringDesc* LOC299;
						NimStringDesc* LOC302;
						Slice88061 LOC303;
						TY13606* LOC304;
						NimStringDesc* LOC305;
						NimStringDesc* LOC306;
						TY161637 LOC307;
						NIM_BOOL LOC308;
						NimStringDesc* LOC309;
						LOC295 = 0;
						LOC296 = 0;
						LOC296 = (((NI) 4) <= (ircmsg ? (ircmsg->Sup.len-1) : -1));
						if (!(LOC296)) goto LA297;
						LOC296 = isloggedin_282152(((NimStringDesc*) &TMP2858));
						LA297: ;
						LOC295 = LOC296;
						if (!(LOC295)) goto LA298;
						LOC299 = 0;
						LOC299 = nsuToLowerStr(nick);
						LOC295 = eqStrings(LOC299, ((NimStringDesc*) &TMP2859));
						LA298: ;
						if (!LOC295) goto LA300;
						nimln(180, "nimbus.nim");
						LOC302 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC303 = HEX2EHEX2E_110273(((NI) 4), (ircmsg ? (ircmsg->Sup.len-1) : -1));
						LOC304 = 0;
						LOC304 = HEX5BHEX5D_133598(ircmsg, LOC303);
						LOC305 = 0;
						LOC305 = nsuJoinSep(LOC304->data, LOC304->Sup.len, ((NimStringDesc*) &TMP2784));
						LOC306 = 0;
						LOC306 = sql_167021(LOC305);
						memset((void*)LOC307, 0, sizeof(LOC307));
						LOC308 = 0;
						LOC308 = tryexec_167138(db_282135, LOC306, LOC307, 0);
						LOC309 = 0;
						LOC309 = nimBoolToStr(LOC308);
						LOC302 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + LOC309->Sup.len + 21);
appendString(LOC302, ((NimStringDesc*) &TMP2855));
appendString(LOC302, ircmsg->data[((NI) 2)]);
appendString(LOC302, ((NimStringDesc*) &TMP2923));
appendString(LOC302, LOC309);
appendString(LOC302, ((NimStringDesc*) &TMP2782));
						send_146407(sock_282133, LOC302);
					}
					LA300: ;
				}
				LA291: ;
				nimln(191, "nimbus.nim");
				{
					NIM_BOOL LOC312;
					NimStringDesc* volatile linktitle;
					TSafePoint TMP2926;
					LOC312 = 0;
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC312 = nsuStartsWith(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2924));
					if (LOC312) goto LA313;
					if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC312 = nsuStartsWith(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2925));
					LA313: ;
					if (!LOC312) goto LA314;
					linktitle = 0;
					nimln(193, "nimbus.nim");
					pushSafePoint(&TMP2926);
					TMP2926.status = setjmp(TMP2926.context);
					if (TMP2926.status == 0) {
						TY13606* LOC317;
						TY13606* LOC318;
						NimStringDesc* LOC319;
						nimln(194, "nimbus.nim");
						if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						nsuDelete((&ircmsg->data[((NI) 3)]), ((NI) 0), ((NI) 0));
						nimln(195, "nimbus.nim");
						if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						printf("%s\015\012", ircmsg->data[((NI) 3)]? (ircmsg->data[((NI) 3)])->data:"nil");
						nimln(196, "nimbus.nim");
						if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						linktitle = getcontent_266171(ircmsg->data[((NI) 3)], ((NimStringDesc*) &TMP2762), ((NI) 5), defaultsslcontext_265377, ((NI) -1), ((NimStringDesc*) &TMP2932), NIM_NIL);
						nimln(197, "nimbus.nim");
						printf("%s\015\012", ((NimStringDesc*) &TMP2933)? (((NimStringDesc*) &TMP2933))->data:"nil");
						nimln(198, "nimbus.nim");
						LOC317 = 0;
						LOC317 = nsuSplitString(linktitle, ((NimStringDesc*) &TMP2934));
						if ((NU)(((NI) 1)) >= (NU)(LOC317->Sup.len)) raiseIndexError();
						linktitle = copyString(LOC317->data[((NI) 1)]);
						nimln(199, "nimbus.nim");
						printf("%s\015\012", ((NimStringDesc*) &TMP2935)? (((NimStringDesc*) &TMP2935))->data:"nil");
						nimln(200, "nimbus.nim");
						LOC318 = 0;
						LOC318 = nsuSplitString(linktitle, ((NimStringDesc*) &TMP2936));
						if ((NU)(((NI) 0)) >= (NU)(LOC318->Sup.len)) raiseIndexError();
						linktitle = copyString(LOC318->data[((NI) 0)]);
						nimln(201, "nimbus.nim");
						printf("%s\015\012", linktitle? (linktitle)->data:"nil");
						nimln(202, "nimbus.nim");
						LOC319 = 0;
						if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						if ((NU)(((NI) 3)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
						LOC319 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + linktitle->Sup.len + ircmsg->data[((NI) 3)]->Sup.len + 30);
appendString(LOC319, ((NimStringDesc*) &TMP2855));
appendString(LOC319, ircmsg->data[((NI) 2)]);
appendString(LOC319, ((NimStringDesc*) &TMP2856));
appendString(LOC319, linktitle);
appendString(LOC319, ((NimStringDesc*) &TMP2937));
appendString(LOC319, ircmsg->data[((NI) 3)]);
appendString(LOC319, ((NimStringDesc*) &TMP2938));
						send_146407(sock_282133, LOC319);
						popSafePoint();
					}
					else {
						popSafePoint();
						setFrame((TFrame*)&FR);
						{
							TMP2926.status = 0;
							nimln(204, "nimbus.nim");
							linktitle = copyString(((NimStringDesc*) &TMP2939));
							nimln(205, "nimbus.nim");
							printf("%s\015\012", ((NimStringDesc*) &TMP2940)? (((NimStringDesc*) &TMP2940))->data:"nil");
							popCurrentException();
						}
					}
					if (TMP2926.status != 0) reraiseException();
				}
				LA314: ;
				nimln(208, "nimbus.nim");
				{
					NIM_BOOL LOC324;
					NIM_BOOL LOC325;
					Slice88061 LOC326;
					TY13606* LOC327;
					NimStringDesc* LOC328;
					Slice88061 LOC330;
					TY13606* LOC331;
					NimStringDesc* LOC332;
					Slice88061 LOC334;
					TY13606* LOC335;
					NimStringDesc* LOC336;
					NimStringDesc* LOC339;
					NimStringDesc* LOC340;
					LOC324 = 0;
					LOC325 = 0;
					LOC326 = HEX2EHEX2E_110273(((NI) 3), (ircmsg ? (ircmsg->Sup.len-1) : -1));
					LOC327 = 0;
					LOC327 = HEX5BHEX5D_133598(ircmsg, LOC326);
					LOC328 = 0;
					LOC328 = nsuJoinSep(LOC327->data, LOC327->Sup.len, ((NimStringDesc*) &TMP2784));
					LOC325 = contains_101362(LOC328, ((NimStringDesc*) &TMP2941));
					if (LOC325) goto LA329;
					LOC330 = HEX2EHEX2E_110273(((NI) 3), (ircmsg ? (ircmsg->Sup.len-1) : -1));
					LOC331 = 0;
					LOC331 = HEX5BHEX5D_133598(ircmsg, LOC330);
					LOC332 = 0;
					LOC332 = nsuJoinSep(LOC331->data, LOC331->Sup.len, ((NimStringDesc*) &TMP2784));
					LOC325 = contains_101362(LOC332, ((NimStringDesc*) &TMP2942));
					LA329: ;
					LOC324 = LOC325;
					if (LOC324) goto LA333;
					LOC334 = HEX2EHEX2E_110273(((NI) 3), (ircmsg ? (ircmsg->Sup.len-1) : -1));
					LOC335 = 0;
					LOC335 = HEX5BHEX5D_133598(ircmsg, LOC334);
					LOC336 = 0;
					LOC336 = nsuJoinSep(LOC335->data, LOC335->Sup.len, ((NimStringDesc*) &TMP2784));
					LOC324 = contains_101362(LOC336, ((NimStringDesc*) &TMP2943));
					LA333: ;
					if (!LOC324) goto LA337;
					nimln(209, "nimbus.nim");
					LOC339 = 0;
					if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC339 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 17);
appendString(LOC339, ((NimStringDesc*) &TMP2855));
appendString(LOC339, ircmsg->data[((NI) 2)]);
appendString(LOC339, ((NimStringDesc*) &TMP2944));
					send_146407(sock_282133, LOC339);
					nimln(210, "nimbus.nim");
					LOC340 = 0;
					if ((NU)(((NI) 2)) >= (NU)(ircmsg->Sup.len)) raiseIndexError();
					LOC340 = rawNewString(ircmsg->data[((NI) 2)]->Sup.len + 20);
appendString(LOC340, ((NimStringDesc*) &TMP2855));
appendString(LOC340, ircmsg->data[((NI) 2)]);
appendString(LOC340, ((NimStringDesc*) &TMP2945));
					send_146407(sock_282133, LOC340);
				}
				LA337: ;
			}
			goto LA55;
			LA70: ;
			LA55: ;
		}
	} LA39: ;
	nimln(216, "nimbus.nim");
	fclose(log_282128);
	nimln(217, "nimbus.nim");
	close_140462(sock_282133);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimbusDatInit)(void) {
}

