/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\random_mt19937ar.o c:\users\owner\documents\nim\esfj\nimcache\random_mt19937ar.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct Mtstate127035 Mtstate127035;
typedef NU32 TY127036[624];
struct  Mtstate127035  {
TY127036 mt;
NI mti;
};
typedef NU32 TY127330[2];
N_NIMCALL(Mtstate127035, initmtstate_127043)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, initgenrand_127053)(Mtstate127035* s, NU32 seed);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, initbyarray_127116)(Mtstate127035* s, NU32* initkey, NI initkeyLen0);
N_NIMCALL(NU32, genrandint32_127324)(Mtstate127035* s);
N_NIMCALL(NI32, genrandint31_127714)(Mtstate127035* s);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NF, genrandreal1_127734)(Mtstate127035* s);
N_NIMCALL(NF, genrandreal2_127749)(Mtstate127035* s);
N_NIMCALL(NF, genrandreal3_127764)(Mtstate127035* s);
N_NIMCALL(NF, genrandres53_127780)(Mtstate127035* s);
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(Mtstate127035, initmtstate_127043)(void) {
	Mtstate127035 result;
	nimfr("init_MTState", "mt19937ar.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(72, "mt19937ar.nim");
	result.mti = ((NI) 625);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, initgenrand_127053)(Mtstate127035* s, NU32 seed) {
	nimfr("init_genrand", "mt19937ar.nim")
	nimln(76, "mt19937ar.nim");
	(*s).mt[(((NI) 0))- 0] = seed;
	nimln(77, "mt19937ar.nim");
	(*s).mti = ((NI) 1);
	{
		nimln(78, "mt19937ar.nim");
		while (1) {
			NI TMP532;
			NI TMP533;
			NI TMP534;
			if (!((*s).mti < ((NI) 624))) goto LA2;
			nimln(79, "mt19937ar.nim");
			if ((NU)((*s).mti) > (NU)(623)) raiseIndexError();
			nimln(80, "mt19937ar.nim");
			TMP532 = subInt((*s).mti, ((NI) 1));
			if ((NU)((NI)(TMP532)) > (NU)(623)) raiseIndexError();
			TMP533 = subInt((*s).mti, ((NI) 1));
			if ((NU)((NI)(TMP533)) > (NU)(623)) raiseIndexError();
			(*s).mt[((*s).mti)- 0] = (NU32)((NU32)((NU32)((NU32)(((NU32) 1812433253)) * (NU32)((NU32)((*s).mt[((NI)(TMP532))- 0] ^ (NU32)((NU64)((*s).mt[((NI)(TMP533))- 0]) >> (NU64)(((NI) 30))))))) + (NU32)(((NU32) ((*s).mti))));
			nimln(87, "mt19937ar.nim");
			TMP534 = addInt((*s).mti, ((NI) 1));
			(*s).mti = (NI)(TMP534);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, initbyarray_127116)(Mtstate127035* s, NU32* initkey, NI initkeyLen0) {
	NI keylength;
	NI i;
	NI j;
	nimfr("init_by_array", "mt19937ar.nim")
	nimln(93, "mt19937ar.nim");
	keylength = initkeyLen0;
	nimln(94, "mt19937ar.nim");
	initgenrand_127053(s, ((NU32) 19650218));
	nimln(95, "mt19937ar.nim");
	i = ((NI) 1);
	nimln(96, "mt19937ar.nim");
	j = ((NI) 0);
	{
		NI k_127143;
		NI HEX3Atmp_127286;
		NI res_127289;
		k_127143 = 0;
		HEX3Atmp_127286 = 0;
		nimln(98, "mt19937ar.nim");
		{
			if (!(keylength < ((NI) 624))) goto LA4;
			HEX3Atmp_127286 = ((NI) 624);
		}
		goto LA2;
		LA4: ;
		{
			HEX3Atmp_127286 = keylength;
		}
		LA2: ;
		nimln(1586, "system.nim");
		res_127289 = HEX3Atmp_127286;
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP535;
				NI TMP536;
				NI TMP537;
				NI TMP538;
				NI TMP539;
				if (!(((NI) 1) <= res_127289)) goto LA8;
				nimln(1588, "system.nim");
				k_127143 = res_127289;
				nimln(99, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				nimln(101, "mt19937ar.nim");
				nimln(100, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				TMP535 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TMP535)) > (NU)(623)) raiseIndexError();
				TMP536 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TMP536)) > (NU)(623)) raiseIndexError();
				if ((NU)(j) >= (NU)(initkeyLen0)) raiseIndexError();
				(*s).mt[(i)- 0] = (NU32)((NU32)((NU32)((NU32)((NU32)((*s).mt[(i)- 0] ^ (NU32)((NU32)((NU32)((*s).mt[((NI)(TMP535))- 0] ^ (NU32)((NU64)((*s).mt[((NI)(TMP536))- 0]) >> (NU64)(((NI) 30))))) * (NU32)(((NU32) 1664525))))) + (NU32)(initkey[j]))) + (NU32)(((NU32) (j))));
				nimln(102, "mt19937ar.nim");
				TMP537 = addInt(i, ((NI) 1));
				i = (NI)(TMP537);
				nimln(103, "mt19937ar.nim");
				TMP538 = addInt(j, ((NI) 1));
				j = (NI)(TMP538);
				nimln(104, "mt19937ar.nim");
				{
					if (!(((NI) 624) <= i)) goto LA11;
					nimln(105, "mt19937ar.nim");
					(*s).mt[(((NI) 0))- 0] = (*s).mt[(((NI) 623))- 0];
					nimln(106, "mt19937ar.nim");
					i = ((NI) 1);
				}
				LA11: ;
				nimln(107, "mt19937ar.nim");
				{
					if (!(keylength <= j)) goto LA15;
					nimln(108, "mt19937ar.nim");
					j = ((NI) 0);
				}
				LA15: ;
				nimln(1589, "system.nim");
				TMP539 = subInt(res_127289, ((NI) 1));
				res_127289 = (NI)(TMP539);
			} LA8: ;
		}
	}
	{
		NI k_127229;
		NI res_127296;
		k_127229 = 0;
		nimln(1586, "system.nim");
		res_127296 = ((NI) 623);
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP540;
				NI TMP541;
				NI TMP542;
				NI TMP543;
				if (!(((NI) 1) <= res_127296)) goto LA19;
				nimln(1588, "system.nim");
				k_127229 = res_127296;
				nimln(111, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				nimln(112, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				TMP540 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TMP540)) > (NU)(623)) raiseIndexError();
				TMP541 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TMP541)) > (NU)(623)) raiseIndexError();
				(*s).mt[(i)- 0] = (NU32)((NU32)((NU32)((*s).mt[(i)- 0] ^ (NU32)((NU32)((NU32)((*s).mt[((NI)(TMP540))- 0] ^ (NU32)((NU64)((*s).mt[((NI)(TMP541))- 0]) >> (NU64)(((NI) 30))))) * (NU32)(((NU32) 1566083941))))) - (NU32)(((NU32) (i))));
				nimln(114, "mt19937ar.nim");
				TMP542 = addInt(i, ((NI) 1));
				i = (NI)(TMP542);
				nimln(115, "mt19937ar.nim");
				{
					if (!(((NI) 624) <= i)) goto LA22;
					nimln(116, "mt19937ar.nim");
					(*s).mt[(((NI) 0))- 0] = (*s).mt[(((NI) 623))- 0];
					nimln(117, "mt19937ar.nim");
					i = ((NI) 1);
				}
				LA22: ;
				nimln(1589, "system.nim");
				TMP543 = subInt(res_127296, ((NI) 1));
				res_127296 = (NI)(TMP543);
			} LA19: ;
		}
	}
	nimln(119, "mt19937ar.nim");
	(*s).mt[(((NI) 0))- 0] = ((NU32) (-2147483647 -1));
	popFrame();
}

N_NIMCALL(NU32, genrandint32_127324)(Mtstate127035* s) {
	NU32 result;
	NU32 y;
	TY127330 mag01;
	NI TMP550;
	nimfr("genrand_int32", "mt19937ar.nim")
{	result = 0;
	y = 0;
	memset((void*)mag01, 0, sizeof(mag01));
	nimln(124, "mt19937ar.nim");
	mag01[0] = ((NU32) 0);
	mag01[1] = ((NU32) -1727483681);
	nimln(127, "mt19937ar.nim");
	{
		if (!(((NI) 624) <= (*s).mti)) goto LA3;
		nimln(128, "mt19937ar.nim");
		{
			if (!((*s).mti == ((NI) 625))) goto LA7;
			nimln(129, "mt19937ar.nim");
			initgenrand_127053(s, ((NU32) 5489));
		}
		LA7: ;
		{
			NI kk_127354;
			NI res_127679;
			kk_127354 = 0;
			nimln(1598, "system.nim");
			res_127679 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP544;
					NI TMP545;
					NI TMP546;
					if (!(res_127679 <= ((NI) 226))) goto LA11;
					nimln(1600, "system.nim");
					kk_127354 = res_127679;
					nimln(132, "mt19937ar.nim");
					if ((NU)(kk_127354) > (NU)(623)) raiseIndexError();
					TMP544 = addInt(kk_127354, ((NI) 1));
					if ((NU)((NI)(TMP544)) > (NU)(623)) raiseIndexError();
					y = (NU32)((NU32)((*s).mt[(kk_127354)- 0] & ((NU32) (-2147483647 -1))) | ((NU32) ((NU32)((*s).mt[((NI)(TMP544))- 0] & ((NU32) 2147483647)))));
					nimln(133, "mt19937ar.nim");
					if ((NU)(kk_127354) > (NU)(623)) raiseIndexError();
					TMP545 = addInt(kk_127354, ((NI) 397));
					if ((NU)((NI)(TMP545)) > (NU)(623)) raiseIndexError();
					(*s).mt[(kk_127354)- 0] = (NU32)((NU32)((*s).mt[((NI)(TMP545))- 0] ^ (NU32)((NU64)(y) >> (NU64)(((NI) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
					nimln(1619, "system.nim");
					TMP546 = addInt(res_127679, ((NI) 1));
					res_127679 = (NI)(TMP546);
				} LA11: ;
			}
		}
		{
			NI kk_127441;
			NI res_127686;
			kk_127441 = 0;
			nimln(1598, "system.nim");
			res_127686 = ((NI) 227);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP547;
					NI TMP548;
					NI TMP549;
					if (!(res_127686 <= ((NI) 622))) goto LA14;
					nimln(1600, "system.nim");
					kk_127441 = res_127686;
					nimln(136, "mt19937ar.nim");
					if ((NU)(kk_127441) > (NU)(623)) raiseIndexError();
					TMP547 = addInt(kk_127441, ((NI) 1));
					if ((NU)((NI)(TMP547)) > (NU)(623)) raiseIndexError();
					y = (NU32)((NU32)((*s).mt[(kk_127441)- 0] & ((NU32) (-2147483647 -1))) | ((NU32) ((NU32)((*s).mt[((NI)(TMP547))- 0] & ((NU32) 2147483647)))));
					nimln(137, "mt19937ar.nim");
					if ((NU)(kk_127441) > (NU)(623)) raiseIndexError();
					TMP548 = addInt(kk_127441, ((NI) -227));
					if ((NU)((NI)(TMP548)) > (NU)(623)) raiseIndexError();
					(*s).mt[(kk_127441)- 0] = (NU32)((NU32)((*s).mt[((NI)(TMP548))- 0] ^ (NU32)((NU64)(y) >> (NU64)(((NI) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
					nimln(1619, "system.nim");
					TMP549 = addInt(res_127686, ((NI) 1));
					res_127686 = (NI)(TMP549);
				} LA14: ;
			}
		}
		nimln(139, "mt19937ar.nim");
		y = (NU32)((NU32)((*s).mt[(((NI) 623))- 0] & ((NU32) (-2147483647 -1))) | ((NU32) ((NU32)((*s).mt[(((NI) 0))- 0] & ((NU32) 2147483647)))));
		nimln(140, "mt19937ar.nim");
		(*s).mt[(((NI) 623))- 0] = (NU32)((NU32)((*s).mt[(((NI) 396))- 0] ^ (NU32)((NU64)(y) >> (NU64)(((NI) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
		nimln(142, "mt19937ar.nim");
		(*s).mti = ((NI) 0);
	}
	LA3: ;
	nimln(144, "mt19937ar.nim");
	if ((NU)((*s).mti) > (NU)(623)) raiseIndexError();
	y = (*s).mt[((*s).mti)- 0];
	nimln(145, "mt19937ar.nim");
	TMP550 = addInt((*s).mti, ((NI) 1));
	(*s).mti = (NI)(TMP550);
	nimln(148, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU64)(y) >> (NU64)(((NI) 11))));
	nimln(149, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU32)((NU64)(y) << (NU64)(((NI) 7))) & ((NU32) -1658038656)));
	nimln(150, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU32)((NU64)(y) << (NU64)(((NI) 15))) & ((NU32) -272236544)));
	nimln(151, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU64)(y) >> (NU64)(((NI) 18))));
	nimln(153, "mt19937ar.nim");
	result = y;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI32, genrandint31_127714)(Mtstate127035* s) {
	NI32 result;
	NU32 LOC1;
	nimfr("genrand_int31", "mt19937ar.nim")
{	result = 0;
	nimln(157, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_127324(s);
	result = ((NI32)chckRange((NU32)((NU64)(LOC1) >> (NU64)(((NI) 1))), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandreal1_127734)(Mtstate127035* s) {
	NF result;
	NU32 LOC1;
	nimfr("genrand_real1", "mt19937ar.nim")
{	result = 0;
	nimln(161, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_127324(s);
	result = ((NF)(((NF) (LOC1))) * (NF)(2.3283064370807974e-010));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandreal2_127749)(Mtstate127035* s) {
	NF result;
	NU32 LOC1;
	nimfr("genrand_real2", "mt19937ar.nim")
{	result = 0;
	nimln(166, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_127324(s);
	result = ((NF)(((NF) (LOC1))) * (NF)(2.3283064365386963e-010));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandreal3_127764)(Mtstate127035* s) {
	NF result;
	NU32 LOC1;
	nimfr("genrand_real3", "mt19937ar.nim")
{	result = 0;
	nimln(171, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_127324(s);
	result = ((NF)(((NF)(((NF) (LOC1))) + (NF)(5.0000000000000000e-001))) * (NF)(2.3283064365386963e-010));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandres53_127780)(Mtstate127035* s) {
	NF result;
	NU32 a;
	NU32 LOC1;
	NU32 b;
	NU32 LOC2;
	nimfr("genrand_res53", "mt19937ar.nim")
{	result = 0;
	nimln(177, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_127324(s);
	a = (NU32)((NU64)(LOC1) >> (NU64)(((NI) 5)));
	nimln(178, "mt19937ar.nim");
	LOC2 = 0;
	LOC2 = genrandint32_127324(s);
	b = (NU32)((NU64)(LOC2) >> (NU64)(((NI) 6)));
	nimln(179, "mt19937ar.nim");
	result = ((NF)(((NF)(((NF)(((NF) (a))) * (NF)(6.7108864000000000e+007))) + (NF)(((NF) (b))))) * (NF)(1.1102230246251565e-016));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, random_mt19937arInit)(void) {
	nimfr("mt19937ar", "mt19937ar.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, random_mt19937arDatInit)(void) {
}

