/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\random_urandom.o c:\users\owner\documents\nim\esfj\nimcache\random_urandom.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <windows.h>

#include <string.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Oserror3433 Oserror3433;
typedef struct Systemerror3429 Systemerror3429;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct TY276432 TY276432;
typedef struct Systemrandom276656 Systemrandom276656;
typedef struct TY276823 TY276823;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, TY276202) (NI* phprov, NI16* pszcontainer, NI16* pszprovider, NI32 dwprovtype, NI32 dwflags);
typedef N_STDCALL_PTR(NI32, TY276210) (NI hprov, NI32 dwlen, void* pbbuffer);
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3429  {
  Exception Sup;
};
struct  Oserror3433  {
  Systemerror3429 Sup;
NI32 errorcode;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef struct {
N_NIMCALL_PTR(NU8, ClPrc) (Systemrandom276656* self, void* ClEnv);
void* ClEnv;
} TY276657;
struct  Systemrandom276656  {
TY276657 bytesit;
};
typedef N_CLOSURE_PTR(NU8, TMP2718) (Systemrandom276656* self);
struct  TY276823  {
NI HEX3Astate;
NU8 b276811;
TY276432* HEX3Atmp276814;
NI i276817;
NI L276819;
};
typedef NI TY27820[8];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct TY276432 {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(void, urandominit_276215)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(TY276432*, urandom_276429)(NI size);
N_NIMCALL(void, TMP2716)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NU8, randomuint8_276835)(Systemrandom276656* self);
N_NIMCALL(void, initsystemrandom_276846)(Systemrandom276656* Result);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP2720)(void* p, NI op);
N_CLOSURE(NU8, sysrandombytes_276665)(Systemrandom276656* self, void* ClEnv);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
STRING_LITERAL(TMP2713, "Advapi32.dll", 12);
STRING_LITERAL(TMP2714, "Advapi32.dll", 12);
STRING_LITERAL(TMP2715, "Call to CryptAcquireContext failed", 34);
STRING_LITERAL(TMP2717, "Call to CryptGenRandom failed", 29);
STRING_LITERAL(TMP2722, "len(a) == L seq modified while iterating over it", 48);
static void* TMP2712;
TY276202 Dl_276201;
TY276210 Dl_276209;
NI cryptprov_276214;
extern TNimType NTI115433; /* ref OSError */
extern TNimType NTI3433; /* OSError */
extern TFrame* frameptr_17042;
extern Tgcheap48616 gch_48644;
extern TNimType NTI120; /* uint8 */
TNimType NTI276432; /* seq[uint8] */
TNimType NTI276823; /* object */
extern TNimType NTI257412; /* range -1..1(int) */
extern TNimType NTI108; /* int */
TNimType NTI276827; /* ref object */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, urandominit_276215)(void) {
	NI32 success;
	nimfr("urandomInit", "urandom.nim")
	nimln(58, "urandom.nim");
	success = Dl_276201((&cryptprov_276214), NIM_NIL, NIM_NIL, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT);
	nimln(61, "urandom.nim");
	{
		Oserror3433* e_276221;
		NimStringDesc* LOC5;
		if (!(success == ((NI32) 0))) goto LA3;
		e_276221 = 0;
		nimln(2265, "system.nim");
		e_276221 = (Oserror3433*) newObj((&NTI115433), sizeof(Oserror3433));
		(*e_276221).Sup.Sup.Sup.m_type = (&NTI3433);
		nimln(2266, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_276221).Sup.Sup.message; (*e_276221).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP2715));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(62, "urandom.nim");
		raiseException((Exception*)e_276221, "OSError");
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP2716)(void* p, NI op) {
	TY276432* a;
	NI LOC1;
	a = (TY276432*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TY276432*, urandom_276429)(NI size) {
	TY276432* result;
	NI32 success_276445;
	nimfr("urandom", "urandom.nim")
	result = 0;
	nimln(96, "urandom.nim");
	result = (TY276432*) newSeq((&NTI276432), size);
	nimln(66, "urandom.nim");
	{
		if (!(cryptprov_276214 == ((NI) 0))) goto LA3;
		nimln(67, "urandom.nim");
		urandominit_276215();
	}
	LA3: ;
	nimln(69, "urandom.nim");
	if ((NU)(((NI) 0)) >= (NU)(result->Sup.len)) raiseIndexError();
	success_276445 = Dl_276209(cryptprov_276214, ((NI32)chckRange(size, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((void*) ((&result->data[((NI) 0)]))));
	nimln(70, "urandom.nim");
	{
		Oserror3433* e_276603;
		NimStringDesc* LOC9;
		if (!(success_276445 == ((NI32) 0))) goto LA7;
		e_276603 = 0;
		nimln(2265, "system.nim");
		e_276603 = (Oserror3433*) newObj((&NTI115433), sizeof(Oserror3433));
		(*e_276603).Sup.Sup.Sup.m_type = (&NTI3433);
		nimln(2266, "system.nim");
		LOC9 = 0;
		LOC9 = (*e_276603).Sup.Sup.message; (*e_276603).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP2717));
		if (LOC9) nimGCunrefNoCycle(LOC9);
		nimln(71, "urandom.nim");
		raiseException((Exception*)e_276603, "OSError");
	}
	LA7: ;
	popFrame();
	return result;
}

static N_INLINE(NU8, randomuint8_276835)(Systemrandom276656* self) {
	NU8 result;
	nimfr("randomUint8", "urandom.nim")
	result = 0;
	nimln(121, "urandom.nim");
	result = (*self).bytesit.ClPrc(self, (*self).bytesit.ClEnv);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP2720)(void* p, NI op) {
	TY276823* a;
	a = (TY276823*)p;
	nimGCvisit((void*)(*a).HEX3Atmp276814, op);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_CLOSURE(NU8, sysrandombytes_276665)(Systemrandom276656* self, void* ClEnv) {
	NU8 result;
	TY276823* HEX3Aenvp_276826;
	nimfr("sysRandomBytes", "urandom.nim")
{	result = 0;
	HEX3Aenvp_276826 = (TY276823*) ClEnv;
	switch ((*HEX3Aenvp_276826).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	{
		nimln(116, "urandom.nim");
		while (1) {
			{
				nimln(117, "urandom.nim");
				asgnRefNoCycle((void**) (&(*HEX3Aenvp_276826).HEX3Atmp276814), urandom_276429(((NI) 128)));
				nimln(3084, "system.nim");
				(*HEX3Aenvp_276826).i276817 = ((NI) 0);
				nimln(3085, "system.nim");
				(*HEX3Aenvp_276826).L276819 = ((*HEX3Aenvp_276826).HEX3Atmp276814 ? (*HEX3Aenvp_276826).HEX3Atmp276814->Sup.len : 0);
				{
					nimln(3086, "system.nim");
					while (1) {
						NI TMP2721;
						if (!((*HEX3Aenvp_276826).i276817 < (*HEX3Aenvp_276826).L276819)) goto LA5;
						nimln(3087, "system.nim");
						if ((NU)((*HEX3Aenvp_276826).i276817) >= (NU)((*HEX3Aenvp_276826).HEX3Atmp276814->Sup.len)) raiseIndexError();
						(*HEX3Aenvp_276826).b276811 = (*HEX3Aenvp_276826).HEX3Atmp276814->data[(*HEX3Aenvp_276826).i276817];
						nimln(118, "urandom.nim");
						(*HEX3Aenvp_276826).HEX3Astate = ((NI) 1);
						result = (*HEX3Aenvp_276826).b276811;
						goto BeforeRet;
						STATE1: ;
						nimln(3088, "system.nim");
						TMP2721 = addInt((*HEX3Aenvp_276826).i276817, ((NI) 1));
						(*HEX3Aenvp_276826).i276817 = (NI)(TMP2721);
						nimln(3089, "system.nim");
						{
							if (!!((((*HEX3Aenvp_276826).HEX3Atmp276814 ? (*HEX3Aenvp_276826).HEX3Atmp276814->Sup.len : 0) == (*HEX3Aenvp_276826).L276819))) goto LA8;
							failedassertimpl_88817(((NimStringDesc*) &TMP2722));
						}
						LA8: ;
					} LA5: ;
				}
			}
		}
	}
	nimln(113, "urandom.nim");
	(*HEX3Aenvp_276826).HEX3Astate = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, initsystemrandom_276846)(Systemrandom276656* Result) {
	TY276823* sysrandombytes_276852;
	TY276657 LOC1;
	nimfr("initSystemRandom", "urandom.nim")
	nimln(125, "urandom.nim");
	sysrandombytes_276852 = 0;
	nimln(180, "system.nim");
	sysrandombytes_276852 = (TY276823*) newObj((&NTI276827), sizeof(TY276823));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = sysrandombytes_276665; LOC1.ClEnv = sysrandombytes_276852;
	unsureAsgnRef((void**) (&(*Result).bytesit.ClEnv), LOC1.ClEnv);
	(*Result).bytesit.ClPrc = LOC1.ClPrc;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, random_urandomInit)(void) {
	nimfr("urandom", "urandom.nim")
	nimln(55, "urandom.nim");
	cryptprov_276214 = ((NI) 0);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, random_urandomDatInit)(void) {
static TNimNode* TMP2719[5];
static TNimNode TMP2710[6];
NTI276432.size = sizeof(TY276432*);
NTI276432.kind = 24;
NTI276432.base = (&NTI120);
NTI276432.flags = 2;
NTI276432.marker = TMP2716;
NTI276823.size = sizeof(TY276823);
NTI276823.kind = 18;
NTI276823.base = 0;
NTI276823.flags = 2;
TMP2719[0] = &TMP2710[1];
TMP2710[1].kind = 1;
TMP2710[1].offset = offsetof(TY276823, HEX3Astate);
TMP2710[1].typ = (&NTI257412);
TMP2710[1].name = ":state";
TMP2719[1] = &TMP2710[2];
TMP2710[2].kind = 1;
TMP2710[2].offset = offsetof(TY276823, b276811);
TMP2710[2].typ = (&NTI120);
TMP2710[2].name = "b276811";
TMP2719[2] = &TMP2710[3];
TMP2710[3].kind = 1;
TMP2710[3].offset = offsetof(TY276823, HEX3Atmp276814);
TMP2710[3].typ = (&NTI276432);
TMP2710[3].name = ":tmp276814";
TMP2719[3] = &TMP2710[4];
TMP2710[4].kind = 1;
TMP2710[4].offset = offsetof(TY276823, i276817);
TMP2710[4].typ = (&NTI108);
TMP2710[4].name = "i276817";
TMP2719[4] = &TMP2710[5];
TMP2710[5].kind = 1;
TMP2710[5].offset = offsetof(TY276823, L276819);
TMP2710[5].typ = (&NTI108);
TMP2710[5].name = "L276819";
TMP2710[0].len = 5; TMP2710[0].kind = 2; TMP2710[0].sons = &TMP2719[0];
NTI276823.node = &TMP2710[0];
NTI276827.size = sizeof(TY276823*);
NTI276827.kind = 22;
NTI276827.base = (&NTI276823);
NTI276827.flags = 2;
NTI276827.marker = TMP2720;
if (!((TMP2712 = nimLoadLibrary((NimStringDesc*) &TMP2713))
)) nimLoadLibraryError((NimStringDesc*) &TMP2714);
	Dl_276201 = (TY276202) nimGetProcAddr(TMP2712, "CryptAcquireContextW");
	Dl_276209 = (TY276210) nimGetProcAddr(TMP2712, "CryptGenRandom");
}

