/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\stdlib_strutils.o c:\users\owner\documents\nim\esfj\nimcache\stdlib_strutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Valueerror3449 Valueerror3449;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct TY13606 TY13606;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3449  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef NU8 TY77659[32];
typedef NI Skiptable100721[256];
typedef NimStringDesc* TY167666[1];
typedef NI TY27820[8];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct TY13606 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
N_NIMCALL(NIM_CHAR, nsuToUpperChar)(NIM_CHAR c);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, TY77659 chars, NI start);
N_NIMCALL(void, preprocesssub_100727)(NimStringDesc* sub, NI* a);
N_NIMCALL(NI, findaux_100795)(NimStringDesc* s, NimStringDesc* sub, NI start, Skiptable100721 a);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
N_NIMCALL(NI, npuParseFloat)(NimStringDesc* s, NF* number, NI start);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, invalidformatstring_102760)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, findnormalized_102731)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
STRING_LITERAL(TMP295, "invalid integer: ", 17);
STRING_LITERAL(TMP491, "not contains(seps, \'\\0\') ", 25);
STRING_LITERAL(TMP521, "", 0);
STRING_LITERAL(TMP623, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TMP795, "invalid float: ", 15);
STRING_LITERAL(TMP799, "invalid format string", 21);
STRING_LITERAL(TMP952, "0123456789ABCDEF", 16);
extern TFrame* frameptr_17042;
extern TNimType NTI22801; /* ref ValueError */
extern TNimType NTI3449; /* ValueError */
extern Tgcheap48616 gch_48644;
extern TNimType NTI13606; /* seq[string] */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	nimfr("intToStr", "strutils.nim")
	result = 0;
	nimln(412, "strutils.nim");
	if (x == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
	result = nimIntToStr((x > 0? (x) : -(x)));
	{
		NI i_99462;
		NI HEX3Atmp_99464;
		NI TMP194;
		NI res_99467;
		i_99462 = 0;
		HEX3Atmp_99464 = 0;
		nimln(413, "strutils.nim");
		TMP194 = subInt(((NI) (minchars)), (result ? result->Sup.len : 0));
		HEX3Atmp_99464 = (NI)(TMP194);
		nimln(1598, "system.nim");
		res_99467 = ((NI) 1);
		{
			nimln(1599, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NI TMP195;
				if (!(res_99467 <= HEX3Atmp_99464)) goto LA3;
				nimln(1600, "system.nim");
				i_99462 = res_99467;
				nimln(414, "strutils.nim");
				LOC4 = 0;
				LOC4 = rawNewString(result->Sup.len + 1);
appendChar(LOC4, 48);
appendString(LOC4, result);
				result = LOC4;
				nimln(1619, "system.nim");
				TMP195 = addInt(res_99467, ((NI) 1));
				res_99467 = (NI)(TMP195);
			} LA3: ;
		}
	}
	nimln(415, "strutils.nim");
	{
		NimStringDesc* LOC9;
		if (!(x < ((NI) 0))) goto LA7;
		nimln(416, "strutils.nim");
		LOC9 = 0;
		LOC9 = rawNewString(result->Sup.len + 1);
appendChar(LOC9, 45);
appendString(LOC9, result);
		result = LOC9;
	}
	LA7: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count) {
	NimStringDesc* result;
	nimfr("repeat", "strutils.nim")
	result = 0;
	nimln(514, "strutils.nim");
	result = mnewString(count);
	{
		NI i_99773;
		NI HEX3Atmp_99775;
		NI TMP254;
		NI res_99778;
		i_99773 = 0;
		HEX3Atmp_99775 = 0;
		nimln(515, "strutils.nim");
		TMP254 = subInt(((NI) (count)), ((NI) 1));
		HEX3Atmp_99775 = (NI)(TMP254);
		nimln(1598, "system.nim");
		res_99778 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP255;
				if (!(res_99778 <= ((NI) (HEX3Atmp_99775)))) goto LA3;
				nimln(1600, "system.nim");
				i_99773 = ((NI)chckRange(res_99778, ((NI) -1), ((NI) IL64(9223372036854775806))));
				nimln(515, "strutils.nim");
				if ((NU)(i_99773) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[i_99773] = c;
				nimln(1619, "system.nim");
				TMP255 = addInt(res_99778, ((NI) 1));
				res_99778 = (NI)(TMP255);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s) {
	NI result;
	NI L;
	nimfr("parseInt", "strutils.nim")
	result = 0;
	nimln(423, "strutils.nim");
	L = npuParseInt(s, (&result), ((NI) 0));
	nimln(424, "strutils.nim");
	{
		NIM_BOOL LOC3;
		Valueerror3449* e_99494;
		NimStringDesc* LOC7;
		LOC3 = 0;
		LOC3 = !((L == (s ? s->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_99494 = 0;
		nimln(2265, "system.nim");
		e_99494 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
		(*e_99494).Sup.Sup.m_type = (&NTI3449);
		nimln(2266, "system.nim");
		nimln(425, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP295));
appendString(LOC7, s);
		asgnRefNoCycle((void**) (&(*e_99494).Sup.message), LOC7);
		raiseException((Exception*)e_99494, "ValueError");
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(69, "strutils.nim");
	{
		NI TMP299;
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(70, "strutils.nim");
		TMP299 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
		result = ((NIM_CHAR) (((NI)chckRange((NI)(TMP299), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(72, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(81, "strutils.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_98091;
		NI HEX3Atmp_98093;
		NI TMP298;
		NI res_98096;
		i_98091 = 0;
		HEX3Atmp_98093 = 0;
		nimln(82, "strutils.nim");
		TMP298 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_98093 = (NI)(TMP298);
		nimln(1598, "system.nim");
		res_98096 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP300;
				if (!(res_98096 <= HEX3Atmp_98093)) goto LA3;
				nimln(1600, "system.nim");
				i_98091 = res_98096;
				nimln(83, "strutils.nim");
				if ((NU)(i_98091) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)(i_98091) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i_98091] = nsuToLowerChar(s->data[i_98091]);
				nimln(1619, "system.nim");
				TMP300 = addInt(res_98096, ((NI) 1));
				res_98096 = (NI)(TMP300);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI m;
	NI TMP314;
	nimfr("cmpIgnoreCase", "strutils.nim")
{	result = 0;
	nimln(139, "strutils.nim");
	i = ((NI) 0);
	nimln(140, "strutils.nim");
	m = (((a ? a->Sup.len : 0) <= (b ? b->Sup.len : 0)) ? (a ? a->Sup.len : 0) : (b ? b->Sup.len : 0));
	{
		nimln(141, "strutils.nim");
		while (1) {
			NIM_CHAR LOC3;
			NIM_CHAR LOC4;
			NI TMP312;
			NI TMP313;
			if (!(i < m)) goto LA2;
			nimln(142, "strutils.nim");
			if ((NU)(i) > (NU)(a->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = nsuToLowerChar(a->data[i]);
			if ((NU)(i) > (NU)(b->Sup.len)) raiseIndexError();
			LOC4 = 0;
			LOC4 = nsuToLowerChar(b->data[i]);
			TMP312 = subInt(((NI) (((NU8)(LOC3)))), ((NI) (((NU8)(LOC4)))));
			result = (NI)(TMP312);
			nimln(143, "strutils.nim");
			{
				if (!!((result == ((NI) 0)))) goto LA7;
				goto BeforeRet;
			}
			LA7: ;
			nimln(144, "strutils.nim");
			TMP313 = addInt(i, ((NI) 1));
			i = (NI)(TMP313);
		} LA2: ;
	}
	nimln(145, "strutils.nim");
	TMP314 = subInt((a ? a->Sup.len : 0), (b ? b->Sup.len : 0));
	result = (NI)(TMP314);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, nsuToUpperChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toUpper", "strutils.nim")
	result = 0;
	nimln(92, "strutils.nim");
	{
		NI TMP452;
		if (!(((NU8)(c)) >= ((NU8)(97)) && ((NU8)(c)) <= ((NU8)(122)))) goto LA3;
		nimln(93, "strutils.nim");
		TMP452 = subInt(((NI) (((NU8)(c)))), ((NI) 32));
		result = ((NIM_CHAR) (((NI)chckRange((NI)(TMP452), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(95, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("toUpper", "strutils.nim")
	result = 0;
	nimln(104, "strutils.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_98177;
		NI HEX3Atmp_98179;
		NI TMP451;
		NI res_98182;
		i_98177 = 0;
		HEX3Atmp_98179 = 0;
		nimln(105, "strutils.nim");
		TMP451 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_98179 = (NI)(TMP451);
		nimln(1598, "system.nim");
		res_98182 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP453;
				if (!(res_98182 <= HEX3Atmp_98179)) goto LA3;
				nimln(1600, "system.nim");
				i_98177 = res_98182;
				nimln(106, "strutils.nim");
				if ((NU)(i_98177) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)(i_98177) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i_98177] = nsuToUpperChar(s->data[i_98177]);
				nimln(1619, "system.nim");
				TMP453 = addInt(res_98182, ((NI) 1));
				res_98182 = (NI)(TMP453);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(TY13606*, nsuSplitCharSet)(NimStringDesc* s, TY77659 seps) {
	TY13606* result;
	nimfr("split", "strutils.nim")
	result = 0;
	nimln(2157, "system.nim");
	result = (TY13606*) newSeq((&NTI13606), 0);
	{
		NimStringDesc* x_99089;
		NI last_99121;
		x_99089 = 0;
		nimln(244, "strutils.nim");
		last_99121 = ((NI) 0);
		nimln(245, "strutils.nim");
		{
			if (!!(!(((seps[((NU8)(0))/8] &(1<<(((NU8)(0))%8)))!=0)))) goto LA4;
			failedassertimpl_88817(((NimStringDesc*) &TMP491));
		}
		LA4: ;
		{
			nimln(246, "strutils.nim");
			while (1) {
				NI first_99123;
				if (!(last_99121 < (s ? s->Sup.len : 0))) goto LA7;
				{
					nimln(247, "strutils.nim");
					while (1) {
						NI TMP492;
						if ((NU)(last_99121) > (NU)(s->Sup.len)) raiseIndexError();
						if (!((seps[((NU8)(s->data[last_99121]))/8] &(1<<(((NU8)(s->data[last_99121]))%8)))!=0)) goto LA9;
						TMP492 = addInt(last_99121, ((NI) 1));
						last_99121 = (NI)(TMP492);
					} LA9: ;
				}
				nimln(248, "strutils.nim");
				first_99123 = last_99121;
				{
					nimln(249, "strutils.nim");
					while (1) {
						NIM_BOOL LOC12;
						NI TMP493;
						LOC12 = 0;
						LOC12 = (last_99121 < (s ? s->Sup.len : 0));
						if (!(LOC12)) goto LA13;
						if ((NU)(last_99121) > (NU)(s->Sup.len)) raiseIndexError();
						LOC12 = !(((seps[((NU8)(s->data[last_99121]))/8] &(1<<(((NU8)(s->data[last_99121]))%8)))!=0));
						LA13: ;
						if (!LOC12) goto LA11;
						TMP493 = addInt(last_99121, ((NI) 1));
						last_99121 = (NI)(TMP493);
					} LA11: ;
				}
				nimln(250, "strutils.nim");
				{
					NI TMP494;
					NI TMP495;
					NimStringDesc* LOC18;
					TMP494 = subInt(last_99121, ((NI) 1));
					if (!(first_99123 <= (NI)(TMP494))) goto LA16;
					nimln(251, "strutils.nim");
					TMP495 = subInt(last_99121, ((NI) 1));
					x_99089 = copyStrLast(s, first_99123, (NI)(TMP495));
					nimln(2158, "system.nim");
					result = (TY13606*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
					LOC18 = 0;
					LOC18 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(x_99089);
					if (LOC18) nimGCunrefNoCycle(LOC18);
				}
				LA16: ;
			} LA7: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start) {
	NI result;
	nimfr("find", "strutils.nim")
{	result = 0;
	{
		NI i_101024;
		NI HEX3Atmp_101026;
		NI TMP498;
		NI res_101029;
		i_101024 = 0;
		HEX3Atmp_101026 = 0;
		nimln(801, "strutils.nim");
		TMP498 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_101026 = (NI)(TMP498);
		nimln(1598, "system.nim");
		res_101029 = ((NI) (start));
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP499;
				if (!(res_101029 <= HEX3Atmp_101026)) goto LA3;
				nimln(1600, "system.nim");
				i_101024 = res_101029;
				nimln(802, "strutils.nim");
				{
					if ((NU)(i_101024) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NU8)(sub) == (NU8)(s->data[i_101024]))) goto LA6;
					result = i_101024;
					goto BeforeRet;
				}
				LA6: ;
				nimln(1619, "system.nim");
				TMP499 = addInt(res_101029, ((NI) 1));
				res_101029 = (NI)(TMP499);
			} LA3: ;
		}
	}
	nimln(803, "strutils.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_101351)(NimStringDesc* s, NIM_CHAR c) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "strutils.nim")
{	result = 0;
	nimln(882, "strutils.nim");
	LOC1 = 0;
	LOC1 = nsuFindChar(s, c, ((NI) 0));
	result = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix) {
	NIM_BOOL result;
	NI i;
	nimfr("startsWith", "strutils.nim")
{	result = 0;
	nimln(667, "strutils.nim");
	i = ((NI) 0);
	{
		nimln(668, "strutils.nim");
		while (1) {
			NI TMP507;
			nimln(669, "strutils.nim");
			{
				if ((NU)(i) > (NU)(prefix->Sup.len)) raiseIndexError();
				if (!((NU8)(prefix->data[i]) == (NU8)(0))) goto LA5;
				result = NIM_TRUE;
				goto BeforeRet;
			}
			LA5: ;
			nimln(670, "strutils.nim");
			{
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if ((NU)(i) > (NU)(prefix->Sup.len)) raiseIndexError();
				if (!!(((NU8)(s->data[i]) == (NU8)(prefix->data[i])))) goto LA9;
				result = NIM_FALSE;
				goto BeforeRet;
			}
			LA9: ;
			nimln(671, "strutils.nim");
			TMP507 = addInt(i, ((NI) 1));
			i = (NI)(TMP507);
		}
	}
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen0, NimStringDesc* sep) {
	NimStringDesc* result;
	nimfr("join", "strutils.nim")
	result = 0;
	nimln(742, "strutils.nim");
	{
		NI L;
		NI TMP516;
		NI TMP517;
		if (!(((NI) 0) < aLen0)) goto LA3;
		nimln(743, "strutils.nim");
		TMP516 = subInt(aLen0, ((NI) 1));
		TMP517 = mulInt((sep ? sep->Sup.len : 0), (NI)(TMP516));
		L = (NI)(TMP517);
		{
			NI i_100575;
			NI HEX3Atmp_100597;
			NI res_100600;
			i_100575 = 0;
			HEX3Atmp_100597 = 0;
			nimln(744, "strutils.nim");
			HEX3Atmp_100597 = (aLen0-1);
			nimln(1598, "system.nim");
			res_100600 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP518;
					NI TMP519;
					if (!(res_100600 <= HEX3Atmp_100597)) goto LA7;
					nimln(1600, "system.nim");
					i_100575 = res_100600;
					nimln(744, "strutils.nim");
					if ((NU)(i_100575) >= (NU)(aLen0)) raiseIndexError();
					TMP518 = addInt(L, (a[i_100575] ? a[i_100575]->Sup.len : 0));
					L = (NI)(TMP518);
					nimln(1619, "system.nim");
					TMP519 = addInt(res_100600, ((NI) 1));
					res_100600 = (NI)(TMP519);
				} LA7: ;
			}
		}
		nimln(745, "strutils.nim");
		result = rawNewString(((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(746, "strutils.nim");
		if ((NU)(((NI) 0)) >= (NU)(aLen0)) raiseIndexError();
		result = resizeString(result, a[((NI) 0)]->Sup.len + 0);
appendString(result, a[((NI) 0)]);
		{
			NI i_100595;
			NI HEX3Atmp_100605;
			NI res_100608;
			i_100595 = 0;
			HEX3Atmp_100605 = 0;
			nimln(747, "strutils.nim");
			HEX3Atmp_100605 = (aLen0-1);
			nimln(1598, "system.nim");
			res_100608 = ((NI) 1);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP520;
					if (!(res_100608 <= HEX3Atmp_100605)) goto LA10;
					nimln(1600, "system.nim");
					i_100595 = res_100608;
					nimln(748, "strutils.nim");
					result = resizeString(result, sep->Sup.len + 0);
appendString(result, sep);
					nimln(749, "strutils.nim");
					if ((NU)(i_100595) >= (NU)(aLen0)) raiseIndexError();
					result = resizeString(result, a[i_100595]->Sup.len + 0);
appendString(result, a[i_100595]);
					nimln(1619, "system.nim");
					TMP520 = addInt(res_100608, ((NI) 1));
					res_100608 = (NI)(TMP520);
				} LA10: ;
			}
		}
	}
	goto LA1;
	LA3: ;
	{
		nimln(751, "strutils.nim");
		result = copyString(((NimStringDesc*) &TMP521));
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	nimfr("cmpIgnoreStyle", "strutils.nim")
	result = 0;
	i = ((NI) 0);
	j = ((NI) 0);
	{
		while (1) {
			NIM_CHAR aa;
			NIM_CHAR bb;
			{
				while (1) {
					if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA4;
					i += ((NI) 1);
				} LA4: ;
			}
			{
				while (1) {
					if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA6;
					j += ((NI) 1);
				} LA6: ;
			}
			aa = nsuToLowerChar(a->data[i]);
			bb = nsuToLowerChar(b->data[j]);
			result = (NI)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = !((result == ((NI) 0)));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(aa) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				goto LA1;
			}
			LA11: ;
			i += ((NI) 1);
			j += ((NI) 1);
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, TY77659 chars, NI start) {
	NI result;
	nimfr("find", "strutils.nim")
{	result = 0;
	{
		NI i_101065;
		NI HEX3Atmp_101077;
		NI TMP613;
		NI res_101080;
		i_101065 = 0;
		HEX3Atmp_101077 = 0;
		nimln(810, "strutils.nim");
		TMP613 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_101077 = (NI)(TMP613);
		nimln(1598, "system.nim");
		res_101080 = ((NI) (start));
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP614;
				if (!(res_101080 <= HEX3Atmp_101077)) goto LA3;
				nimln(1600, "system.nim");
				i_101065 = res_101080;
				nimln(811, "strutils.nim");
				{
					if ((NU)(i_101065) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((chars[((NU8)(s->data[i_101065]))/8] &(1<<(((NU8)(s->data[i_101065]))%8)))!=0)) goto LA6;
					result = i_101065;
					goto BeforeRet;
				}
				LA6: ;
				nimln(1619, "system.nim");
				TMP614 = addInt(res_101080, ((NI) 1));
				res_101080 = (NI)(TMP614);
			} LA3: ;
		}
	}
	nimln(812, "strutils.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_101373)(NimStringDesc* s, TY77659 chars) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "strutils.nim")
{	result = 0;
	nimln(890, "strutils.nim");
	LOC1 = 0;
	LOC1 = nsuFindCharSet(s, chars, ((NI) 0));
	result = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, allcharsinset_100459)(NimStringDesc* s, TY77659 theset) {
	NIM_BOOL result;
	nimfr("allCharsInSet", "strutils.nim")
{	result = 0;
	{
		NIM_CHAR c_100465;
		NI i_100479;
		NI L_100481;
		c_100465 = 0;
		nimln(3102, "system.nim");
		i_100479 = ((NI) 0);
		nimln(3103, "system.nim");
		L_100481 = (s ? s->Sup.len : 0);
		{
			nimln(3104, "system.nim");
			while (1) {
				NI TMP622;
				if (!(i_100479 < L_100481)) goto LA3;
				nimln(3105, "system.nim");
				if ((NU)(i_100479) > (NU)(s->Sup.len)) raiseIndexError();
				c_100465 = s->data[i_100479];
				nimln(721, "strutils.nim");
				{
					if (!!(((theset[((NU8)(c_100465))/8] &(1<<(((NU8)(c_100465))%8)))!=0))) goto LA6;
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA6: ;
				nimln(3106, "system.nim");
				TMP622 = addInt(i_100479, ((NI) 1));
				i_100479 = (NI)(TMP622);
				nimln(3107, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_100481))) goto LA10;
					failedassertimpl_88817(((NimStringDesc*) &TMP623));
				}
				LA10: ;
			} LA3: ;
		}
	}
	nimln(722, "strutils.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, preprocesssub_100727)(NimStringDesc* sub, NI* a) {
	NI m;
	nimfr("preprocessSub", "strutils.nim")
	nimln(768, "strutils.nim");
	m = (sub ? sub->Sup.len : 0);
	{
		NI i_100744;
		NI res_100759;
		i_100744 = 0;
		nimln(1598, "system.nim");
		res_100759 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP626;
				NI TMP627;
				if (!(res_100759 <= ((NI) 255))) goto LA3;
				nimln(1600, "system.nim");
				i_100744 = res_100759;
				nimln(769, "strutils.nim");
				TMP626 = addInt(m, ((NI) 1));
				a[(((NU8)(((NIM_CHAR) (((NI)chckRange(i_100744, ((NI) 0), ((NI) 255))))))))- 0] = (NI)(TMP626);
				nimln(1619, "system.nim");
				TMP627 = addInt(res_100759, ((NI) 1));
				res_100759 = (NI)(TMP627);
			} LA3: ;
		}
	}
	{
		NI i_100755;
		NI HEX3Atmp_100764;
		NI TMP628;
		NI res_100767;
		i_100755 = 0;
		HEX3Atmp_100764 = 0;
		nimln(770, "strutils.nim");
		TMP628 = subInt(m, ((NI) 1));
		HEX3Atmp_100764 = (NI)(TMP628);
		nimln(1598, "system.nim");
		res_100767 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP629;
				NI TMP630;
				if (!(res_100767 <= HEX3Atmp_100764)) goto LA6;
				nimln(1600, "system.nim");
				i_100755 = res_100767;
				nimln(770, "strutils.nim");
				if ((NU)(i_100755) > (NU)(sub->Sup.len)) raiseIndexError();
				TMP629 = subInt(m, i_100755);
				a[(((NU8)(sub->data[i_100755])))- 0] = (NI)(TMP629);
				nimln(1619, "system.nim");
				TMP630 = addInt(res_100767, ((NI) 1));
				res_100767 = (NI)(TMP630);
			} LA6: ;
		}
	}
	popFrame();
}

N_NIMCALL(NI, findaux_100795)(NimStringDesc* s, NimStringDesc* sub, NI start, Skiptable100721 a) {
	NI result;
	NI m;
	NI n;
	NI j;
	nimfr("findAux", "strutils.nim")
{	result = 0;
	nimln(775, "strutils.nim");
	m = (sub ? sub->Sup.len : 0);
	nimln(776, "strutils.nim");
	n = (s ? s->Sup.len : 0);
	nimln(778, "strutils.nim");
	j = start;
	{
		nimln(779, "strutils.nim");
		while (1) {
			NI TMP631;
			NI TMP635;
			NI TMP636;
			TMP631 = subInt(n, m);
			if (!(j <= (NI)(TMP631))) goto LA2;
			{
				{
					NI k_100816;
					NI HEX3Atmp_100828;
					NI TMP632;
					NI res_100831;
					k_100816 = 0;
					HEX3Atmp_100828 = 0;
					nimln(781, "strutils.nim");
					TMP632 = subInt(m, ((NI) 1));
					HEX3Atmp_100828 = (NI)(TMP632);
					nimln(1598, "system.nim");
					res_100831 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP634;
							if (!(res_100831 <= HEX3Atmp_100828)) goto LA6;
							nimln(1600, "system.nim");
							k_100816 = res_100831;
							nimln(782, "strutils.nim");
							{
								NI TMP633;
								if ((NU)(k_100816) > (NU)(sub->Sup.len)) raiseIndexError();
								TMP633 = addInt(k_100816, j);
								if ((NU)((NI)(TMP633)) > (NU)(s->Sup.len)) raiseIndexError();
								if (!!(((NU8)(sub->data[k_100816]) == (NU8)(s->data[(NI)(TMP633)])))) goto LA9;
								goto LA3;
							}
							LA9: ;
							nimln(1619, "system.nim");
							TMP634 = addInt(res_100831, ((NI) 1));
							res_100831 = (NI)(TMP634);
						} LA6: ;
					}
				}
				nimln(783, "strutils.nim");
				result = j;
				goto BeforeRet;
			} LA3: ;
			nimln(784, "strutils.nim");
			TMP635 = addInt(j, m);
			if ((NU)((NI)(TMP635)) > (NU)(s->Sup.len)) raiseIndexError();
			TMP636 = addInt(j, a[(((NU8)(s->data[(NI)(TMP635)])))- 0]);
			j = (NI)(TMP636);
		} LA2: ;
	}
	nimln(785, "strutils.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by) {
	NimStringDesc* result;
	Skiptable100721 a;
	NI i;
	NimStringDesc* LOC8;
	nimfr("replace", "strutils.nim")
	result = 0;
	nimln(896, "strutils.nim");
	result = copyString(((NimStringDesc*) &TMP521));
	nimln(897, "strutils.nim");
	preprocesssub_100727(sub, a);
	nimln(898, "strutils.nim");
	i = ((NI) 0);
	{
		nimln(899, "strutils.nim");
		while (1) {
			NI j;
			NI TMP637;
			NimStringDesc* LOC7;
			NI TMP638;
			nimln(900, "strutils.nim");
			j = findaux_100795(s, sub, i, a);
			nimln(901, "strutils.nim");
			{
				if (!(j < ((NI) 0))) goto LA5;
				goto LA1;
			}
			LA5: ;
			nimln(902, "strutils.nim");
			TMP637 = subInt(j, ((NI) 1));
			LOC7 = 0;
			LOC7 = copyStrLast(s, i, (NI)(TMP637));
			result = resizeString(result, LOC7->Sup.len + 0);
appendString(result, LOC7);
			nimln(903, "strutils.nim");
			result = resizeString(result, by->Sup.len + 0);
appendString(result, by);
			nimln(904, "strutils.nim");
			TMP638 = addInt(j, (sub ? sub->Sup.len : 0));
			i = (NI)(TMP638);
		}
	} LA1: ;
	nimln(906, "strutils.nim");
	LOC8 = 0;
	LOC8 = copyStr(s, i);
	result = resizeString(result, LOC8->Sup.len + 0);
appendString(result, LOC8);
	popFrame();
	return result;
}

N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringDesc* s) {
	NI64 result;
	NI L;
	nimfr("parseBiggestInt", "strutils.nim")
	result = 0;
	nimln(432, "strutils.nim");
	L = npuParseBiggestInt(s, (&result), ((NI) 0));
	nimln(433, "strutils.nim");
	{
		NIM_BOOL LOC3;
		Valueerror3449* e_99519;
		NimStringDesc* LOC7;
		LOC3 = 0;
		LOC3 = !((L == (s ? s->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_99519 = 0;
		nimln(2265, "system.nim");
		e_99519 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
		(*e_99519).Sup.Sup.m_type = (&NTI3449);
		nimln(2266, "system.nim");
		nimln(434, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP295));
appendString(LOC7, s);
		asgnRefNoCycle((void**) (&(*e_99519).Sup.message), LOC7);
		raiseException((Exception*)e_99519, "ValueError");
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s) {
	NF result;
	NI L;
	nimfr("parseFloat", "strutils.nim")
	result = 0;
	nimln(441, "strutils.nim");
	L = npuParseFloat(s, (&result), ((NI) 0));
	nimln(442, "strutils.nim");
	{
		NIM_BOOL LOC3;
		Valueerror3449* e_99544;
		NimStringDesc* LOC7;
		LOC3 = 0;
		LOC3 = !((L == (s ? s->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_99544 = 0;
		nimln(2265, "system.nim");
		e_99544 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
		(*e_99544).Sup.Sup.m_type = (&NTI3449);
		nimln(2266, "system.nim");
		nimln(443, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 15);
appendString(LOC7, ((NimStringDesc*) &TMP795));
appendString(LOC7, s);
		asgnRefNoCycle((void**) (&(*e_99544).Sup.message), LOC7);
		raiseException((Exception*)e_99544, "ValueError");
	}
	LA5: ;
	popFrame();
	return result;
}

N_NOINLINE(void, invalidformatstring_102760)(void) {
	Valueerror3449* e_102764;
	NimStringDesc* LOC1;
	nimfr("invalidFormatString", "strutils.nim")
	e_102764 = 0;
	nimln(2265, "system.nim");
	e_102764 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
	(*e_102764).Sup.Sup.m_type = (&NTI3449);
	nimln(2266, "system.nim");
	LOC1 = 0;
	LOC1 = (*e_102764).Sup.message; (*e_102764).Sup.message = copyStringRC1(((NimStringDesc*) &TMP799));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(1289, "strutils.nim");
	raiseException((Exception*)e_102764, "ValueError");
	popFrame();
}

N_NIMCALL(NI, findnormalized_102731)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	nimfr("findNormalized", "strutils.nim")
{	result = 0;
	nimln(1281, "strutils.nim");
	i = ((NI) 0);
	{
		nimln(1282, "strutils.nim");
		while (1) {
			NI TMP813;
			if (!(i < (inarrayLen0-1))) goto LA2;
			nimln(1283, "strutils.nim");
			{
				NI LOC5;
				if ((NU)(i) >= (NU)(inarrayLen0)) raiseIndexError();
				LOC5 = 0;
				LOC5 = nsuCmpIgnoreStyle(x, inarray[i]);
				if (!(LOC5 == ((NI) 0))) goto LA6;
				result = i;
				goto BeforeRet;
			}
			LA6: ;
			nimln(1284, "strutils.nim");
			TMP813 = addInt(i, ((NI) 2));
			i = (NI)(TMP813);
		} LA2: ;
	}
	nimln(1286, "strutils.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	nimfr("addf", "strutils.nim")
	nimln(1295, "strutils.nim");
	i = ((NI) 0);
	nimln(1296, "strutils.nim");
	num = ((NI) 0);
	{
		nimln(1297, "strutils.nim");
		while (1) {
			if (!(i < (formatstr ? formatstr->Sup.len : 0))) goto LA2;
			nimln(1298, "strutils.nim");
			{
				NI TMP798;
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA5;
				nimln(1299, "strutils.nim");
				TMP798 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TMP798)) > (NU)(formatstr->Sup.len)) raiseIndexError();
				switch (((NU8)(formatstr->data[(NI)(TMP798)]))) {
				case 35:
				{
					NI TMP800;
					NI TMP801;
					nimln(1302, "strutils.nim");
					{
						if (!((NU64)((aLen0-1)) < (NU64)(num))) goto LA10;
						invalidformatstring_102760();
					}
					LA10: ;
					nimln(1303, "strutils.nim");
					if ((NU)(num) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
					nimln(1304, "strutils.nim");
					TMP800 = addInt(i, ((NI) 2));
					i = (NI)(TMP800);
					nimln(1305, "strutils.nim");
					TMP801 = addInt(num, ((NI) 1));
					num = (NI)(TMP801);
				}
				break;
				case 36:
				{
					NI TMP802;
					nimln(1307, "strutils.nim");
					(*s) = addChar((*s), 36);
					nimln(1308, "strutils.nim");
					TMP802 = addInt(i, ((NI) 2));
					i = (NI)(TMP802);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI j;
					NI TMP803;
					NIM_BOOL negative;
					NI idx;
					nimln(1310, "strutils.nim");
					j = ((NI) 0);
					nimln(1311, "strutils.nim");
					TMP803 = addInt(i, ((NI) 1));
					i = (NI)(TMP803);
					nimln(1312, "strutils.nim");
					if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
					negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
					nimln(1313, "strutils.nim");
					{
						NI TMP804;
						if (!negative) goto LA16;
						TMP804 = addInt(i, ((NI) 1));
						i = (NI)(TMP804);
					}
					LA16: ;
					{
						nimln(1314, "strutils.nim");
						while (1) {
							NI TMP805;
							NI TMP806;
							NI TMP807;
							NI TMP808;
							if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA19;
							nimln(1315, "strutils.nim");
							TMP805 = mulInt(j, ((NI) 10));
							if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
							TMP806 = addInt((NI)(TMP805), ((NI) (((NU8)(formatstr->data[i])))));
							TMP807 = subInt((NI)(TMP806), ((NI) 48));
							j = (NI)(TMP807);
							nimln(1316, "strutils.nim");
							TMP808 = addInt(i, ((NI) 1));
							i = (NI)(TMP808);
						} LA19: ;
					}
					nimln(1317, "strutils.nim");
					{
						NI TMP809;
						if (!!(negative)) goto LA22;
						TMP809 = subInt(j, ((NI) 1));
						idx = (NI)(TMP809);
					}
					goto LA20;
					LA22: ;
					{
						NI TMP810;
						TMP810 = subInt(aLen0, j);
						idx = (NI)(TMP810);
					}
					LA20: ;
					nimln(1318, "strutils.nim");
					{
						if (!((NU64)((aLen0-1)) < (NU64)(idx))) goto LA27;
						invalidformatstring_102760();
					}
					LA27: ;
					nimln(1319, "strutils.nim");
					if ((NU)(idx) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
				}
				break;
				case 123:
				{
					NI j;
					NI TMP811;
					NI x;
					NI TMP814;
					NI TMP815;
					NimStringDesc* LOC32;
					NI TMP817;
					nimln(1321, "strutils.nim");
					TMP811 = addInt(i, ((NI) 1));
					j = (NI)(TMP811);
					{
						nimln(1322, "strutils.nim");
						while (1) {
							NI TMP812;
							if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA31;
							TMP812 = addInt(j, ((NI) 1));
							j = (NI)(TMP812);
						} LA31: ;
					}
					nimln(1323, "strutils.nim");
					TMP814 = addInt(i, ((NI) 2));
					TMP815 = subInt(j, ((NI) 1));
					LOC32 = 0;
					LOC32 = copyStrLast(formatstr, (NI)(TMP814), (NI)(TMP815));
					x = findnormalized_102731(LOC32, a, aLen0);
					nimln(1324, "strutils.nim");
					{
						NIM_BOOL LOC35;
						NI TMP816;
						LOC35 = 0;
						LOC35 = (((NI) 0) <= x);
						if (!(LOC35)) goto LA36;
						LOC35 = (x < (aLen0-1));
						LA36: ;
						if (!LOC35) goto LA37;
						TMP816 = addInt(x, ((NI) 1));
						if ((NU)((NI)(TMP816)) >= (NU)(aLen0)) raiseIndexError();
						(*s) = resizeString((*s), a[(NI)(TMP816)]->Sup.len + 0);
appendString((*s), a[(NI)(TMP816)]);
					}
					goto LA33;
					LA37: ;
					{
						nimln(1325, "strutils.nim");
						invalidformatstring_102760();
					}
					LA33: ;
					nimln(1326, "strutils.nim");
					TMP817 = addInt(j, ((NI) 1));
					i = (NI)(TMP817);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j;
					NI TMP818;
					NI x;
					NI TMP820;
					NI TMP821;
					NimStringDesc* LOC43;
					nimln(1328, "strutils.nim");
					TMP818 = addInt(i, ((NI) 1));
					j = (NI)(TMP818);
					{
						nimln(1329, "strutils.nim");
						while (1) {
							NI TMP819;
							if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA42;
							TMP819 = addInt(j, ((NI) 1));
							j = (NI)(TMP819);
						} LA42: ;
					}
					nimln(1330, "strutils.nim");
					TMP820 = addInt(i, ((NI) 1));
					TMP821 = subInt(j, ((NI) 1));
					LOC43 = 0;
					LOC43 = copyStrLast(formatstr, (NI)(TMP820), (NI)(TMP821));
					x = findnormalized_102731(LOC43, a, aLen0);
					nimln(1331, "strutils.nim");
					{
						NIM_BOOL LOC46;
						NI TMP822;
						LOC46 = 0;
						LOC46 = (((NI) 0) <= x);
						if (!(LOC46)) goto LA47;
						LOC46 = (x < (aLen0-1));
						LA47: ;
						if (!LOC46) goto LA48;
						TMP822 = addInt(x, ((NI) 1));
						if ((NU)((NI)(TMP822)) >= (NU)(aLen0)) raiseIndexError();
						(*s) = resizeString((*s), a[(NI)(TMP822)]->Sup.len + 0);
appendString((*s), a[(NI)(TMP822)]);
					}
					goto LA44;
					LA48: ;
					{
						nimln(1332, "strutils.nim");
						invalidformatstring_102760();
					}
					LA44: ;
					nimln(1333, "strutils.nim");
					i = j;
				}
				break;
				default:
				{
					nimln(1335, "strutils.nim");
					invalidformatstring_102760();
				}
				break;
				}
			}
			goto LA3;
			LA5: ;
			{
				NI TMP823;
				nimln(1337, "strutils.nim");
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				(*s) = addChar((*s), formatstr->data[i]);
				nimln(1338, "strutils.nim");
				TMP823 = addInt(i, ((NI) 1));
				i = (NI)(TMP823);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NimStringDesc* result;
	NI TMP797;
	nimfr("%", "strutils.nim")
	result = 0;
	nimln(1382, "strutils.nim");
	TMP797 = addInt((formatstr ? formatstr->Sup.len : 0), (NI)((NU64)(aLen0) << (NU64)(((NI) 4))));
	result = rawNewString(((NI)chckRange((NI)(TMP797), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(1383, "strutils.nim");
	nsuAddf((&result), formatstr, a, aLen0);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len) {
	NimStringDesc* result;
	NI64 n;
	nimfr("toHex", "strutils.nim")
	result = 0;
	nimln(398, "strutils.nim");
	n = x;
	nimln(399, "strutils.nim");
	result = mnewString(((NI) (len)));
	{
		NI j_99423;
		NI HEX3Atmp_99426;
		NI TMP951;
		NI res_99429;
		j_99423 = 0;
		HEX3Atmp_99426 = 0;
		nimln(400, "strutils.nim");
		TMP951 = subInt(((NI) (len)), ((NI) 1));
		HEX3Atmp_99426 = (NI)(TMP951);
		nimln(1586, "system.nim");
		res_99429 = ((NI) (HEX3Atmp_99426));
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP953;
				if (!(((NI) 0) <= res_99429)) goto LA3;
				nimln(1588, "system.nim");
				j_99423 = ((NI)chckRange(res_99429, ((NI) 0), ((NI) IL64(9223372036854775806))));
				nimln(401, "strutils.nim");
				if ((NU)(j_99423) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)((NI64)(n & IL64(15))) > (NU)(((NimStringDesc*) &TMP952)->Sup.len)) raiseIndexError();
				result->data[j_99423] = ((NimStringDesc*) &TMP952)->data[(NI64)(n & IL64(15))];
				nimln(402, "strutils.nim");
				n = (NI64)((NU64)(n) >> (NU64)(IL64(4)));
				nimln(404, "strutils.nim");
				{
					NIM_BOOL LOC6;
					LOC6 = 0;
					LOC6 = (n == IL64(0));
					if (!(LOC6)) goto LA7;
					LOC6 = (x < IL64(0));
					LA7: ;
					if (!LOC6) goto LA8;
					n = IL64(-1);
				}
				LA8: ;
				nimln(1589, "system.nim");
				TMP953 = subInt(res_99429, ((NI) 1));
				res_99429 = (NI)(TMP953);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a) {
	NimStringDesc* result;
	NI TMP1177;
	TY167666 LOC1;
	nimfr("%", "strutils.nim")
	result = 0;
	nimln(1388, "strutils.nim");
	TMP1177 = addInt((formatstr ? formatstr->Sup.len : 0), (a ? a->Sup.len : 0));
	result = rawNewString(((NI)chckRange((NI)(TMP1177), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(1389, "strutils.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString(a);
	nsuAddf((&result), formatstr, LOC1, 1);
	popFrame();
	return result;
}

N_NIMCALL(NI, rfind_101099)(NimStringDesc* s, NimStringDesc* sub, NI start) {
	NI result;
	NI realstart;
	nimfr("rfind", "strutils.nim")
{	result = 0;
	nimln(819, "strutils.nim");
	{
		if (!(start == ((NI) -1))) goto LA3;
		realstart = (s ? s->Sup.len : 0);
	}
	goto LA1;
	LA3: ;
	{
		realstart = start;
	}
	LA1: ;
	{
		NI i_101117;
		NI HEX3Atmp_101138;
		NI TMP1328;
		NI res_101141;
		i_101117 = 0;
		HEX3Atmp_101138 = 0;
		nimln(820, "strutils.nim");
		TMP1328 = subInt(realstart, (sub ? sub->Sup.len : 0));
		HEX3Atmp_101138 = (NI)(TMP1328);
		nimln(1586, "system.nim");
		res_101141 = HEX3Atmp_101138;
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP1332;
				if (!(((NI) 0) <= res_101141)) goto LA8;
				nimln(1588, "system.nim");
				i_101117 = res_101141;
				{
					NI j_101128;
					NI HEX3Atmp_101131;
					NI TMP1329;
					NI res_101134;
					j_101128 = 0;
					HEX3Atmp_101131 = 0;
					nimln(821, "strutils.nim");
					TMP1329 = subInt((sub ? sub->Sup.len : 0), ((NI) 1));
					HEX3Atmp_101131 = (NI)(TMP1329);
					nimln(1598, "system.nim");
					res_101134 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP1331;
							if (!(res_101134 <= HEX3Atmp_101131)) goto LA11;
							nimln(1600, "system.nim");
							j_101128 = res_101134;
							nimln(822, "strutils.nim");
							result = i_101117;
							nimln(823, "strutils.nim");
							{
								NI TMP1330;
								if ((NU)(j_101128) > (NU)(sub->Sup.len)) raiseIndexError();
								TMP1330 = addInt(i_101117, j_101128);
								if ((NU)((NI)(TMP1330)) > (NU)(s->Sup.len)) raiseIndexError();
								if (!!(((NU8)(sub->data[j_101128]) == (NU8)(s->data[(NI)(TMP1330)])))) goto LA14;
								nimln(824, "strutils.nim");
								result = ((NI) -1);
								nimln(825, "strutils.nim");
								goto LA9;
							}
							LA14: ;
							nimln(1619, "system.nim");
							TMP1331 = addInt(res_101134, ((NI) 1));
							res_101134 = (NI)(TMP1331);
						} LA11: ;
					}
				} LA9: ;
				nimln(826, "strutils.nim");
				{
					if (!!((result == ((NI) -1)))) goto LA18;
					goto BeforeRet;
				}
				LA18: ;
				nimln(1589, "system.nim");
				TMP1332 = subInt(res_101141, ((NI) 1));
				res_101141 = (NI)(TMP1332);
			} LA8: ;
		}
	}
	nimln(827, "strutils.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing) {
	NimStringDesc* result;
	NI first;
	NI last;
	NI TMP2518;
	nimfr("strip", "strutils.nim")
	result = 0;
	nimln(181, "strutils.nim");
	first = ((NI) 0);
	nimln(182, "strutils.nim");
	TMP2518 = subInt((s ? s->Sup.len : 0), ((NI) 1));
	last = (NI)(TMP2518);
	nimln(183, "strutils.nim");
	{
		if (!leading) goto LA3;
		{
			nimln(184, "strutils.nim");
			while (1) {
				NI TMP2519;
				if ((NU)(first) > (NU)(s->Sup.len)) raiseIndexError();
				if (!(((NU8)(s->data[first])) == ((NU8)(32)) || ((NU8)(s->data[first])) == ((NU8)(9)) || ((NU8)(s->data[first])) == ((NU8)(11)) || ((NU8)(s->data[first])) == ((NU8)(13)) || ((NU8)(s->data[first])) == ((NU8)(10)) || ((NU8)(s->data[first])) == ((NU8)(12)))) goto LA6;
				TMP2519 = addInt(first, ((NI) 1));
				first = (NI)(TMP2519);
			} LA6: ;
		}
	}
	LA3: ;
	nimln(185, "strutils.nim");
	{
		if (!trailing) goto LA9;
		{
			nimln(186, "strutils.nim");
			while (1) {
				NIM_BOOL LOC13;
				NI TMP2520;
				LOC13 = 0;
				LOC13 = (((NI) 0) <= last);
				if (!(LOC13)) goto LA14;
				if ((NU)(last) > (NU)(s->Sup.len)) raiseIndexError();
				LOC13 = (((NU8)(s->data[last])) == ((NU8)(32)) || ((NU8)(s->data[last])) == ((NU8)(9)) || ((NU8)(s->data[last])) == ((NU8)(11)) || ((NU8)(s->data[last])) == ((NU8)(13)) || ((NU8)(s->data[last])) == ((NU8)(10)) || ((NU8)(s->data[last])) == ((NU8)(12)));
				LA14: ;
				if (!LOC13) goto LA12;
				TMP2520 = subInt(last, ((NI) 1));
				last = (NI)(TMP2520);
			} LA12: ;
		}
	}
	LA9: ;
	nimln(187, "strutils.nim");
	result = copyStrLast(s, first, last);
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start) {
	NI result;
	Skiptable100721 a;
	nimfr("find", "strutils.nim")
	result = 0;
	nimln(793, "strutils.nim");
	preprocesssub_100727(sub, a);
	nimln(794, "strutils.nim");
	result = findaux_100795(s, sub, ((NI) (start)), a);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_101362)(NimStringDesc* s, NimStringDesc* sub) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "strutils.nim")
{	result = 0;
	nimln(886, "strutils.nim");
	LOC1 = 0;
	LOC1 = nsuFindStr(s, sub, ((NI) 0));
	result = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix) {
	NIM_BOOL result;
	NI i;
	NI j;
	NI TMP2580;
	nimfr("endsWith", "strutils.nim")
{	result = 0;
	nimln(678, "strutils.nim");
	i = ((NI) 0);
	nimln(679, "strutils.nim");
	TMP2580 = subInt((s ? s->Sup.len : 0), (suffix ? suffix->Sup.len : 0));
	j = (NI)(TMP2580);
	{
		nimln(680, "strutils.nim");
		while (1) {
			NI TMP2581;
			NI TMP2583;
			TMP2581 = addInt(i, j);
			if (!((NU64)((NI)(TMP2581)) < (NU64)((s ? s->Sup.len : 0)))) goto LA2;
			nimln(681, "strutils.nim");
			{
				NI TMP2582;
				TMP2582 = addInt(i, j);
				if ((NU)((NI)(TMP2582)) > (NU)(s->Sup.len)) raiseIndexError();
				if ((NU)(i) > (NU)(suffix->Sup.len)) raiseIndexError();
				if (!!(((NU8)(s->data[(NI)(TMP2582)]) == (NU8)(suffix->data[i])))) goto LA5;
				result = NIM_FALSE;
				goto BeforeRet;
			}
			LA5: ;
			nimln(682, "strutils.nim");
			TMP2583 = addInt(i, ((NI) 1));
			i = (NI)(TMP2583);
		} LA2: ;
	}
	nimln(683, "strutils.nim");
	{
		if ((NU)(i) > (NU)(suffix->Sup.len)) raiseIndexError();
		if (!((NU8)(suffix->data[i]) == (NU8)(0))) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA9: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TY13606*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep) {
	TY13606* result;
	nimfr("split", "strutils.nim")
	result = 0;
	nimln(2157, "system.nim");
	result = (TY13606*) newSeq((&NTI13606), 0);
	{
		NimStringDesc* x_99220;
		NI last_99251;
		x_99220 = 0;
		nimln(293, "strutils.nim");
		last_99251 = ((NI) 0);
		nimln(294, "strutils.nim");
		{
			if (!(((NI) 0) < (s ? s->Sup.len : 0))) goto LA4;
			{
				nimln(295, "strutils.nim");
				while (1) {
					NI first_99253;
					NI TMP2837;
					NimStringDesc* LOC13;
					NI TMP2838;
					if (!(last_99251 <= (s ? s->Sup.len : 0))) goto LA7;
					nimln(296, "strutils.nim");
					first_99253 = last_99251;
					{
						nimln(297, "strutils.nim");
						while (1) {
							NIM_BOOL LOC10;
							NI TMP2835;
							NimStringDesc* LOC12;
							NI TMP2836;
							LOC10 = 0;
							LOC10 = (last_99251 < (s ? s->Sup.len : 0));
							if (!(LOC10)) goto LA11;
							TMP2835 = addInt(last_99251, subInt((sep ? sep->Sup.len : 0), 1));
							LOC12 = 0;
							LOC12 = copyStrLast(s, last_99251, (NI)(TMP2835));
							LOC10 = !(eqStrings(LOC12, sep));
							LA11: ;
							if (!LOC10) goto LA9;
							nimln(298, "strutils.nim");
							TMP2836 = addInt(last_99251, ((NI) 1));
							last_99251 = (NI)(TMP2836);
						} LA9: ;
					}
					nimln(299, "strutils.nim");
					TMP2837 = subInt(last_99251, ((NI) 1));
					x_99220 = copyStrLast(s, first_99253, (NI)(TMP2837));
					nimln(2158, "system.nim");
					result = (TY13606*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
					LOC13 = 0;
					LOC13 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(x_99220);
					if (LOC13) nimGCunrefNoCycle(LOC13);
					nimln(300, "strutils.nim");
					TMP2838 = addInt(last_99251, (sep ? sep->Sup.len : 0));
					last_99251 = (NI)(TMP2838);
				} LA7: ;
			}
		}
		LA4: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, nsuDelete)(NimStringDesc** s, NI first, NI last) {
	NI i;
	NI j;
	NI TMP2896;
	NI newlen;
	NI TMP2897;
	NI TMP2898;
	nimfr("delete", "strutils.nim")
	nimln(952, "strutils.nim");
	i = first;
	nimln(953, "strutils.nim");
	TMP2896 = addInt(last, ((NI) 1));
	j = (NI)(TMP2896);
	nimln(954, "strutils.nim");
	TMP2897 = subInt(((*s) ? (*s)->Sup.len : 0), j);
	TMP2898 = addInt((NI)(TMP2897), i);
	newlen = (NI)(TMP2898);
	{
		nimln(955, "strutils.nim");
		while (1) {
			NI TMP2899;
			NI TMP2900;
			if (!(i < newlen)) goto LA2;
			nimln(956, "strutils.nim");
			if ((NU)(i) > (NU)((*s)->Sup.len)) raiseIndexError();
			if ((NU)(j) > (NU)((*s)->Sup.len)) raiseIndexError();
			(*s)->data[i] = (*s)->data[j];
			nimln(957, "strutils.nim");
			TMP2899 = addInt(i, ((NI) 1));
			i = (NI)(TMP2899);
			nimln(958, "strutils.nim");
			TMP2900 = addInt(j, ((NI) 1));
			j = (NI)(TMP2900);
		} LA2: ;
	}
	nimln(959, "strutils.nim");
	(*s) = setLengthStr((*s), ((NI)chckRange(newlen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void) {
}

