/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\stdlib_os.o c:\users\owner\documents\nim\esfj\nimcache\stdlib_os.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdlib.h>
typedef struct TY13606 TY13606;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Oserror3433 Oserror3433;
typedef struct Systemerror3429 Systemerror3429;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TY119789 TY119789;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef N_STDCALL_PTR(NI16*, TY106440) (void);
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3429  {
  Exception Sup;
};
struct  Oserror3433  {
  Systemerror3429 Sup;
NI32 errorcode;
};
typedef N_STDCALL_PTR(NI32, TY105663) (NI32 dwflags, void* lpsource, NI32 dwmessageid, NI32 dwlanguageid, void* lpbuffer, NI32 nsize, void* Arguments);
typedef N_STDCALL_PTR(void, TY105805) (void* p);
typedef N_STDCALL_PTR(NI32, TY105658) (void);
typedef N_STDCALL_PTR(NI16*, TY106435) (void);
typedef N_STDCALL_PTR(NI32, TY106437) (NI16* para1);
typedef N_STDCALL_PTR(void, TY106632) (NI32 dwmilliseconds);
struct TY119789 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NI TY27820[8];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct TY13606 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pop_125662)(TY13606** s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NI, nosparamCount)(void);
N_NIMCALL(TY13606*, nosparseCmdLine)(NimStringDesc* c);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(NimStringDesc*, HEX24_81389)(NI16* s);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, nosparamStr)(NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, oserrormsg_115020)(NI32 errorcode);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, findenvvar_124804)(NimStringDesc* key);
N_NIMCALL(void, getenvvarsc_124405)(void);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
STRING_LITERAL(TMP471, "", 0);
STRING_LITERAL(TMP532, "unknown OS error", 16);
NIM_BOOL envcomputed_124007;
TY13606* environment_124009;
extern TFrame* frameptr_17042;
TY13606* ownargv_128609;
extern TNimType NTI13606; /* seq[string] */
extern Tgcheap48616 gch_48644;
extern TY106440 Dl_106439;
extern TNimType NTI115433; /* ref OSError */
extern TNimType NTI3433; /* OSError */
extern TY105663 Dl_105662;
extern TY105805 Dl_105804;
extern TY105658 Dl_105657;
extern TY106435 Dl_106434;
extern TY106437 Dl_106436;
extern TY106632 Dl_106631;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(NimStringDesc*, pop_125662)(TY13606** s) {
	NimStringDesc* result;
	NI L;
	NI TMP465;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1926, "system.nim");
	TMP465 = subInt(((*s) ? (*s)->Sup.len : 0), ((NI) 1));
	L = (NI)(TMP465);
	nimln(1927, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln(1928, "system.nim");
	(*s) = (TY13606*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI)(a % b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(TY13606*, nosparseCmdLine)(NimStringDesc* c) {
	TY13606* result;
	NI i;
	NimStringDesc* a;
	nimfr("parseCmdLine", "os.nim")
	result = 0;
	nimln(1493, "os.nim");
	result = (TY13606*) newSeq((&NTI13606), 0);
	nimln(1494, "os.nim");
	i = ((NI) 0);
	nimln(1495, "os.nim");
	a = copyString(((NimStringDesc*) &TMP471));
	{
		nimln(1496, "os.nim");
		while (1) {
			NIM_BOOL inquote;
			NimStringDesc* LOC49;
			nimln(1497, "os.nim");
			a = setLengthStr(a, ((NI) 0));
			{
				nimln(1499, "os.nim");
				while (1) {
					NIM_BOOL LOC5;
					NIM_BOOL LOC6;
					NIM_BOOL LOC7;
					NI TMP472;
					LOC5 = 0;
					LOC6 = 0;
					LOC7 = 0;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC7 = ((NU8)(c->data[i]) == (NU8)(32));
					if (LOC7) goto LA8;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC7 = ((NU8)(c->data[i]) == (NU8)(9));
					LA8: ;
					LOC6 = LOC7;
					if (LOC6) goto LA9;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC6 = ((NU8)(c->data[i]) == (NU8)(10));
					LA9: ;
					LOC5 = LOC6;
					if (LOC5) goto LA10;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC5 = ((NU8)(c->data[i]) == (NU8)(13));
					LA10: ;
					if (!LOC5) goto LA4;
					TMP472 = addInt(i, ((NI) 1));
					i = (NI)(TMP472);
				} LA4: ;
			}
			nimln(1502, "os.nim");
			{
				if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
				if (!((NU8)(c->data[i]) == (NU8)(0))) goto LA13;
				goto LA1;
			}
			LA13: ;
			nimln(1503, "os.nim");
			inquote = NIM_FALSE;
			{
				nimln(1504, "os.nim");
				while (1) {
					nimln(1505, "os.nim");
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					switch (((NU8)(c->data[i]))) {
					case 0:
					{
						nimln(1506, "os.nim");
						goto LA15;
					}
					break;
					case 92:
					{
						NI j;
						nimln(1508, "os.nim");
						j = i;
						{
							nimln(1509, "os.nim");
							while (1) {
								NI TMP473;
								if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();
								if (!((NU8)(c->data[j]) == (NU8)(92))) goto LA20;
								TMP473 = addInt(j, ((NI) 1));
								j = (NI)(TMP473);
							} LA20: ;
						}
						nimln(1510, "os.nim");
						{
							if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();
							if (!((NU8)(c->data[j]) == (NU8)(34))) goto LA23;
							{
								NI k_127622;
								NI HEX3Atmp_127684;
								NI TMP474;
								NI TMP475;
								NI res_127687;
								k_127622 = 0;
								HEX3Atmp_127684 = 0;
								nimln(1511, "os.nim");
								TMP474 = subInt(j, i);
								TMP475 = divInt((NI)(TMP474), ((NI) 2));
								HEX3Atmp_127684 = (NI)(TMP475);
								nimln(1598, "system.nim");
								res_127687 = ((NI) 1);
								{
									nimln(1599, "system.nim");
									while (1) {
										NI TMP476;
										if (!(res_127687 <= HEX3Atmp_127684)) goto LA27;
										nimln(1600, "system.nim");
										k_127622 = res_127687;
										nimln(1511, "os.nim");
										a = addChar(a, 92);
										nimln(1619, "system.nim");
										TMP476 = addInt(res_127687, ((NI) 1));
										res_127687 = (NI)(TMP476);
									} LA27: ;
								}
							}
							nimln(1512, "os.nim");
							{
								NI TMP477;
								NI TMP478;
								TMP477 = subInt(j, i);
								TMP478 = modInt((NI)(TMP477), ((NI) 2));
								if (!(((NI) ((NI)(TMP478))) == ((NI) 0))) goto LA30;
								nimln(1513, "os.nim");
								i = j;
							}
							goto LA28;
							LA30: ;
							{
								NI TMP479;
								nimln(1515, "os.nim");
								a = addChar(a, 34);
								nimln(1516, "os.nim");
								TMP479 = addInt(j, ((NI) 1));
								i = (NI)(TMP479);
							}
							LA28: ;
						}
						goto LA21;
						LA23: ;
						{
							NI TMP480;
							nimln(1518, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							a = addChar(a, c->data[i]);
							nimln(1519, "os.nim");
							TMP480 = addInt(i, ((NI) 1));
							i = (NI)(TMP480);
						}
						LA21: ;
					}
					break;
					case 34:
					{
						NI TMP481;
						nimln(1521, "os.nim");
						TMP481 = addInt(i, ((NI) 1));
						i = (NI)(TMP481);
						nimln(1522, "os.nim");
						{
							if (!!(inquote)) goto LA37;
							inquote = NIM_TRUE;
						}
						goto LA35;
						LA37: ;
						{
							NI TMP482;
							nimln(1523, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							if (!((NU8)(c->data[i]) == (NU8)(34))) goto LA40;
							nimln(1524, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							a = addChar(a, c->data[i]);
							nimln(1525, "os.nim");
							TMP482 = addInt(i, ((NI) 1));
							i = (NI)(TMP482);
						}
						goto LA35;
						LA40: ;
						{
							nimln(1527, "os.nim");
							inquote = NIM_FALSE;
							nimln(1528, "os.nim");
							goto LA15;
						}
						LA35: ;
					}
					break;
					case 32:
					case 9:
					{
						NI TMP483;
						nimln(1530, "os.nim");
						{
							if (!!(inquote)) goto LA46;
							goto LA15;
						}
						LA46: ;
						nimln(1531, "os.nim");
						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
						a = addChar(a, c->data[i]);
						nimln(1532, "os.nim");
						TMP483 = addInt(i, ((NI) 1));
						i = (NI)(TMP483);
					}
					break;
					default:
					{
						NI TMP484;
						nimln(1534, "os.nim");
						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
						a = addChar(a, c->data[i]);
						nimln(1535, "os.nim");
						TMP484 = addInt(i, ((NI) 1));
						i = (NI)(TMP484);
					}
					break;
					}
				}
			} LA15: ;
			nimln(1550, "os.nim");
			result = (TY13606*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
			LOC49 = 0;
			LOC49 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(a);
			if (LOC49) nimGCunrefNoCycle(LOC49);
		}
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nosparamCount)(void) {
	NI result;
	NI TMP485;
	nimfr("paramCount", "os.nim")
	result = 0;
	nimln(1699, "os.nim");
	{
		NI16* LOC5;
		NimStringDesc* LOC6;
		if (!ownargv_128609 == 0) goto LA3;
		LOC5 = 0;
		LOC5 = Dl_106439();
		LOC6 = 0;
		LOC6 = HEX24_81389(LOC5);
		asgnRefNoCycle((void**) (&ownargv_128609), nosparseCmdLine(LOC6));
	}
	LA3: ;
	nimln(1700, "os.nim");
	TMP485 = subInt((ownargv_128609 ? ownargv_128609->Sup.len : 0), ((NI) 1));
	result = (NI)(TMP485);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosparamStr)(NI i) {
	NimStringDesc* result;
	nimfr("paramStr", "os.nim")
{	result = 0;
	nimln(1705, "os.nim");
	{
		NI16* LOC5;
		NimStringDesc* LOC6;
		if (!ownargv_128609 == 0) goto LA3;
		LOC5 = 0;
		LOC5 = Dl_106439();
		LOC6 = 0;
		LOC6 = HEX24_81389(LOC5);
		asgnRefNoCycle((void**) (&ownargv_128609), nosparseCmdLine(LOC6));
	}
	LA3: ;
	nimln(1706, "os.nim");
	if ((NU)(i) >= (NU)(ownargv_128609->Sup.len)) raiseIndexError();
	result = copyString(ownargv_128609->data[i]);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY13606*, commandlineparams_128805)(void) {
	TY13606* result;
	nimfr("commandLineParams", "os.nim")
	result = 0;
	nimln(1740, "os.nim");
	result = (TY13606*) newSeq((&NTI13606), 0);
	{
		NI i_128835;
		NI HEX3Atmp_128847;
		NI res_128850;
		i_128835 = 0;
		HEX3Atmp_128847 = 0;
		nimln(1741, "os.nim");
		HEX3Atmp_128847 = nosparamCount();
		nimln(1598, "system.nim");
		res_128850 = ((NI) 1);
		{
			nimln(1599, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NimStringDesc* LOC5;
				NI TMP486;
				if (!(res_128850 <= HEX3Atmp_128847)) goto LA3;
				nimln(1600, "system.nim");
				i_128835 = res_128850;
				nimln(1742, "os.nim");
				LOC4 = 0;
				LOC4 = nosparamStr(i_128835);
				result = (TY13606*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
				LOC5 = 0;
				LOC5 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(LOC4);
				if (LOC5) nimGCunrefNoCycle(LOC5);
				nimln(1619, "system.nim");
				TMP486 = addInt(res_128850, ((NI) 1));
				res_128850 = (NI)(TMP486);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, oserrormsg_115020)(NI32 errorcode) {
	NimStringDesc* result;
	nimfr("osErrorMsg", "os.nim")
	result = 0;
	nimln(245, "os.nim");
	result = copyString(((NimStringDesc*) &TMP471));
	nimln(247, "os.nim");
	{
		NI16* msgbuf;
		if (!!((errorcode == ((NI32) 0)))) goto LA3;
		msgbuf = 0;
		nimln(250, "os.nim");
		{
			NI32 LOC7;
			nimln(251, "os.nim");
			nimln(250, "os.nim");
			LOC7 = 0;
			LOC7 = Dl_105662(((NI32) 4864), NIM_NIL, errorcode, ((NI32) 0), ((void*) (&msgbuf)), ((NI32) 0), NIM_NIL);
			if (!!((LOC7 == ((NI32) 0)))) goto LA8;
			nimln(252, "os.nim");
			result = HEX24_81389(msgbuf);
			nimln(253, "os.nim");
			{
				if (!!((msgbuf == NIM_NIL))) goto LA12;
				Dl_105804(((void*) (msgbuf)));
			}
			LA12: ;
		}
		LA8: ;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, raiseoserror_115430)(NI32 errorcode) {
	Oserror3433* e;
	nimfr("raiseOSError", "os.nim")
	e = 0;
	nimln(272, "os.nim");
	e = (Oserror3433*) newObj((&NTI115433), sizeof(Oserror3433));
	(*e).Sup.Sup.Sup.m_type = (&NTI3433);
	nimln(273, "os.nim");
	(*e).errorcode = errorcode;
	nimln(274, "os.nim");
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), oserrormsg_115020(errorcode));
	nimln(275, "os.nim");
	{
		NimStringDesc* LOC5;
		if (!(((*e).Sup.Sup.message) && ((*e).Sup.Sup.message)->Sup.len == 0)) goto LA3;
		nimln(276, "os.nim");
		LOC5 = 0;
		LOC5 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP532));
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	LA3: ;
	nimln(277, "os.nim");
	raiseException((Exception*)e, "OSError");
	popFrame();
}

N_NIMCALL(NI32, oslasterror_115454)(void) {
	NI32 result;
	result = 0;
	result = Dl_105657();
	return result;
}

N_NIMCALL(void, getenvvarsc_124405)(void) {
	nimfr("getEnvVarsC", "os.nim")
{	nimln(1096, "os.nim");
	{
		NI16* env;
		NI16* e;
		NI32 LOC17;
		if (!!(envcomputed_124007)) goto LA3;
		nimln(1097, "os.nim");
		if (environment_124009) nimGCunrefNoCycle(environment_124009);
		environment_124009 = (TY13606*) newSeqRC1((&NTI13606), 0);
		nimln(1100, "os.nim");
		env = Dl_106434();
		nimln(1101, "os.nim");
		e = env;
		nimln(1102, "os.nim");
		{
			if (!(e == NIM_NIL)) goto LA7;
			goto BeforeRet;
		}
		LA7: ;
		{
			nimln(1103, "os.nim");
			while (1) {
				NI16* eend;
				NimStringDesc* LOC11;
				NimStringDesc* LOC12;
				NI TMP564;
				nimln(1104, "os.nim");
				eend = wcschr(e, ((NI32) 0));
				nimln(1105, "os.nim");
				LOC11 = 0;
				LOC11 = HEX24_81389(e);
				environment_124009 = (TY13606*) incrSeq(&(environment_124009)->Sup, sizeof(NimStringDesc*));
				LOC12 = 0;
				LOC12 = environment_124009->data[environment_124009->Sup.len-1]; environment_124009->data[environment_124009->Sup.len-1] = copyStringRC1(LOC11);
				if (LOC12) nimGCunrefNoCycle(LOC12);
				nimln(1106, "os.nim");
				TMP564 = addInt(((NI) (eend)), ((NI) 2));
				e = ((NI16*) ((NI)(TMP564)));
				nimln(1107, "os.nim");
				{
					if (!(((NI) (eend[(((NI) 1))- 0])) == ((NI) 0))) goto LA15;
					goto LA9;
				}
				LA15: ;
			}
		} LA9: ;
		nimln(1108, "os.nim");
		LOC17 = 0;
		LOC17 = Dl_106436(env);
		nimln(1120, "os.nim");
		envcomputed_124007 = NIM_TRUE;
	}
	LA3: ;
	}BeforeRet: ;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NI, findenvvar_124804)(NimStringDesc* key) {
	NI result;
	NimStringDesc* temp;
	NimStringDesc* LOC1;
	nimfr("findEnvVar", "os.nim")
{	result = 0;
	nimln(1154, "os.nim");
	getenvvarsc_124405();
	nimln(1155, "os.nim");
	LOC1 = 0;
	LOC1 = rawNewString(key->Sup.len + 1);
appendString(LOC1, key);
appendChar(LOC1, 61);
	temp = LOC1;
	{
		NI i_124819;
		NI HEX3Atmp_124821;
		NI res_124824;
		i_124819 = 0;
		HEX3Atmp_124821 = 0;
		nimln(1156, "os.nim");
		HEX3Atmp_124821 = (environment_124009 ? (environment_124009->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_124824 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP565;
				if (!(res_124824 <= HEX3Atmp_124821)) goto LA4;
				nimln(1600, "system.nim");
				i_124819 = res_124824;
				nimln(1157, "os.nim");
				{
					NIM_BOOL LOC7;
					if ((NU)(i_124819) >= (NU)(environment_124009->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = nsuStartsWith(environment_124009->data[i_124819], temp);
					if (!LOC7) goto LA8;
					result = i_124819;
					goto BeforeRet;
				}
				LA8: ;
				nimln(1619, "system.nim");
				TMP565 = addInt(res_124824, ((NI) 1));
				res_124824 = (NI)(TMP565);
			} LA4: ;
		}
	}
	nimln(1158, "os.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getenv_124843)(NimStringDesc* key) {
	NimStringDesc* result;
	NI i;
	nimfr("getEnv", "os.nim")
{	result = 0;
	nimln(1166, "os.nim");
	i = findenvvar_124804(key);
	nimln(1167, "os.nim");
	{
		NI LOC5;
		NI TMP566;
		if (!(((NI) 0) <= i)) goto LA3;
		nimln(1168, "os.nim");
		if ((NU)(i) >= (NU)(environment_124009->Sup.len)) raiseIndexError();
		if ((NU)(i) >= (NU)(environment_124009->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = nsuFindChar(environment_124009->data[i], 61, ((NI) 0));
		TMP566 = addInt(LOC5, ((NI) 1));
		result = copyStr(environment_124009->data[i], (NI)(TMP566));
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NCSTRING env;
		nimln(1170, "os.nim");
		env = getenv(key->data);
		nimln(1171, "os.nim");
		{
			if (!(env == NIM_NIL)) goto LA9;
			result = copyString(((NimStringDesc*) &TMP471));
			goto BeforeRet;
		}
		LA9: ;
		nimln(1172, "os.nim");
		result = cstrToNimstr(env);
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nossleep)(NI milsecs) {
	nimfr("sleep", "os.nim")
	nimln(1843, "os.nim");
	Dl_106631(((NI32)chckRange(milsecs, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
	popFrame();
}

N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY119789* Result) {
	nimfr("splitFile", "os.nim")
	nimln(691, "os.nim");
	{
		NIM_BOOL LOC3;
		NI TMP2535;
		LOC3 = 0;
		LOC3 = ((path ? path->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		TMP2535 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP2535)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC3 = (((NU8)(path->data[(NI)(TMP2535)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TMP2535)])) == ((NU8)(47)));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(692, "os.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), copyString(path));
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(((NimStringDesc*) &TMP471)));
		unsureAsgnRef((void**) (&(*Result).Field2), copyString(((NimStringDesc*) &TMP471)));
	}
	goto LA1;
	LA5: ;
	{
		NI seppos;
		NI dotpos;
		NI TMP2539;
		NI TMP2540;
		NI TMP2541;
		nimln(694, "os.nim");
		seppos = ((NI) -1);
		nimln(695, "os.nim");
		dotpos = (path ? path->Sup.len : 0);
		{
			NI i_119819;
			NI HEX3Atmp_119843;
			NI TMP2536;
			NI res_119846;
			i_119819 = 0;
			HEX3Atmp_119843 = 0;
			nimln(696, "os.nim");
			TMP2536 = subInt((path ? path->Sup.len : 0), ((NI) 1));
			HEX3Atmp_119843 = (NI)(TMP2536);
			nimln(1586, "system.nim");
			res_119846 = HEX3Atmp_119843;
			{
				nimln(1587, "system.nim");
				while (1) {
					NI TMP2538;
					if (!(((NI) 0) <= res_119846)) goto LA10;
					nimln(1588, "system.nim");
					i_119819 = res_119846;
					nimln(697, "os.nim");
					{
						if ((NU)(i_119819) > (NU)(path->Sup.len)) raiseIndexError();
						if (!((NU8)(path->data[i_119819]) == (NU8)(46))) goto LA13;
						nimln(698, "os.nim");
						{
							NIM_BOOL LOC17;
							NIM_BOOL LOC18;
							NI TMP2537;
							LOC17 = 0;
							LOC18 = 0;
							LOC18 = (dotpos == (path ? path->Sup.len : 0));
							if (!(LOC18)) goto LA19;
							LOC18 = (((NI) 0) < i_119819);
							LA19: ;
							LOC17 = LOC18;
							if (!(LOC17)) goto LA20;
							nimln(699, "os.nim");
							TMP2537 = subInt(i_119819, ((NI) 1));
							if ((NU)((NI)(TMP2537)) > (NU)(path->Sup.len)) raiseIndexError();
							LOC17 = !((((NU8)(path->data[(NI)(TMP2537)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TMP2537)])) == ((NU8)(47))));
							LA20: ;
							if (!LOC17) goto LA21;
							dotpos = i_119819;
						}
						LA21: ;
					}
					goto LA11;
					LA13: ;
					{
						nimln(700, "os.nim");
						if ((NU)(i_119819) > (NU)(path->Sup.len)) raiseIndexError();
						if (!(((NU8)(path->data[i_119819])) == ((NU8)(92)) || ((NU8)(path->data[i_119819])) == ((NU8)(47)))) goto LA24;
						nimln(701, "os.nim");
						seppos = i_119819;
						nimln(702, "os.nim");
						goto LA8;
					}
					goto LA11;
					LA24: ;
					LA11: ;
					nimln(1589, "system.nim");
					TMP2538 = subInt(res_119846, ((NI) 1));
					res_119846 = (NI)(TMP2538);
				} LA10: ;
			}
		} LA8: ;
		nimln(703, "os.nim");
		TMP2539 = subInt(seppos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field0), copyStrLast(path, ((NI) 0), (NI)(TMP2539)));
		nimln(704, "os.nim");
		TMP2540 = addInt(seppos, ((NI) 1));
		TMP2541 = subInt(dotpos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field1), copyStrLast(path, (NI)(TMP2540), (NI)(TMP2541)));
		nimln(705, "os.nim");
		unsureAsgnRef((void**) (&(*Result).Field2), copyStr(path, dotpos));
	}
	LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void) {
	nimfr("os", "os.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void) {
}

