/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\stdlib_tables.o c:\users\owner\documents\nim\esfj\nimcache\stdlib_tables.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Table230371 Table230371;
typedef struct Keyvaluepairseq230374 Keyvaluepairseq230374;
typedef struct Keyvaluepair230377 Keyvaluepair230377;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Table230371  {
Keyvaluepairseq230374* data;
NI counter;
};
struct Keyvaluepair230377 {
NI Field0;
NI64 Field1;
void* Field2;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct Keyvaluepairseq230374 {
  TGenericSeq Sup;
  Keyvaluepair230377 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_227201)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_227211)(NI hcode);
static N_INLINE(NIM_BOOL, mustrehash_227313)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, rightsize_227407)(NI count);
N_NIMCALL(NI, nextpoweroftwo_119531)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, nexttry_227420)(NI h, NI maxhash);
static N_INLINE(NI, rawget_230633)(Table230371 t, NI64 key, NI* hc);
static N_INLINE(NI, hash_116814)(NI64 x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, enlarge_230720)(Table230371* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, TMP1210)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, rawgetknownhc_230774)(Table230371 t, NI64 key, NI hc);
N_NIMCALL(void, rawinsert_230800)(Table230371* t, Keyvaluepairseq230374** data, NI64 key, void* val, NI hc, NI h);
STRING_LITERAL(TMP1158, "counter < length ", 17);
extern TFrame* frameptr_17042;
TNimType NTI230377; /* KeyValuePair */
extern TNimType NTI116023; /* THash */
extern TNimType NTI5710; /* BiggestInt */
extern TNimType NTI153; /* pointer */
TNimType NTI230374; /* KeyValuePairSeq */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(NIM_BOOL, isempty_227201)(NI hcode) {
	NIM_BOOL result;
	nimfr("isEmpty", "tables.nim")
	result = 0;
	nimln(89, "tables.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isfilled_227211)(NI hcode) {
	NIM_BOOL result;
	nimfr("isFilled", "tables.nim")
	result = 0;
	nimln(92, "tables.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustrehash_227313)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP1159;
	NI TMP1160;
	NI TMP1161;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(128, "tables.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP1158));
	}
	LA3: ;
	nimln(129, "tables.nim");
	LOC5 = 0;
	TMP1159 = mulInt(length, ((NI) 2));
	TMP1160 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP1159) < (NI)(TMP1160));
	if (LOC5) goto LA6;
	TMP1161 = subInt(length, counter);
	LOC5 = ((NI)(TMP1161) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rightsize_227407)(NI count) {
	NI result;
	NI TMP1162;
	NI TMP1163;
	NI TMP1164;
	nimfr("rightSize", "tables.nim")
	result = 0;
	nimln(138, "tables.nim");
	TMP1162 = mulInt(((NI) (count)), ((NI) 3));
	TMP1163 = divInt(((NI) ((NI)(TMP1162))), ((NI) 2));
	TMP1164 = addInt(((NI) ((NI)(TMP1163))), ((NI) 4));
	result = nextpoweroftwo_119531(((NI) ((NI)(TMP1164))));
	popFrame();
	return result;
}

static N_INLINE(NI, nexttry_227420)(NI h, NI maxhash) {
	NI result;
	NI TMP1165;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(141, "tables.nim");
	TMP1165 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TMP1165) & maxhash);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_116814)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(111, "hashes.nim");
	result = ((NI) (((NI32)(NU32)(NU64)(x))));
	popFrame();
	return result;
}

static N_INLINE(NI, rawget_230633)(Table230371 t, NI64 key, NI* hc) {
	NI result;
	NI h;
	NI TMP1205;
	nimfr("rawGet", "tables.nim")
{	result = 0;
	nimln(156, "tables.nim");
	(*hc) = hash_116814(key);
	nimln(157, "tables.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(158, "tables.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(144, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_227211(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field1 == key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(152, "tables.nim");
			h = nexttry_227420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(153, "tables.nim");
	TMP1205 = subInt(((NI) -1), h);
	result = (NI)(TMP1205);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void*, HEX5BHEX5D_230621)(Table230371 t, NI64 key) {
	void* result;
	NI hc;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	hc = 0;
	nimln(190, "tables.nim");
	index = rawget_230633(t, key, (&hc));
	nimln(191, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		result = t.data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP1210)(void* p, NI op) {
	Keyvaluepairseq230374* a;
	NI LOC1;
	a = (Keyvaluepairseq230374*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(NI, rawgetknownhc_230774)(Table230371 t, NI64 key, NI hc) {
	NI result;
	NI h;
	NI TMP1211;
	nimfr("rawGetKnownHC", "tables.nim")
{	result = 0;
	nimln(144, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_227211(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field1 == key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(152, "tables.nim");
			h = nexttry_227420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(153, "tables.nim");
	TMP1211 = subInt(((NI) -1), h);
	result = (NI)(TMP1211);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_230800)(Table230371* t, Keyvaluepairseq230374** data, NI64 key, void* val, NI hc, NI h) {
	nimfr("rawInsert", "tables.nim")
	nimln(171, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field1 = key;
	nimln(172, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field2 = val;
	nimln(173, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_230720)(Table230371* t) {
	Keyvaluepairseq230374* n;
	NI TMP1208;
	Keyvaluepairseq230374* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(224, "tables.nim");
	TMP1208 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq230374*) newSeq((&NTI230374), ((NI)chckRange((NI)(TMP1208), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(225, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_230772;
		NI HEX3Atmp_230826;
		NI res_230829;
		i_230772 = 0;
		HEX3Atmp_230826 = 0;
		nimln(226, "tables.nim");
		HEX3Atmp_230826 = (n ? (n->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_230829 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP1213;
				if (!(res_230829 <= HEX3Atmp_230826)) goto LA4;
				nimln(1600, "system.nim");
				i_230772 = res_230829;
				nimln(227, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP1212;
					if ((NU)(i_230772) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_227211(n->data[i_230772].Field0);
					if (!LOC7) goto LA8;
					nimln(228, "tables.nim");
					if ((NU)(i_230772) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_230772) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_230774((*t), n->data[i_230772].Field1, n->data[i_230772].Field0);
					TMP1212 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP1212);
					nimln(229, "tables.nim");
					if ((NU)(i_230772) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_230772) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_230772) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_230800(t, (&(*t).data), n->data[i_230772].Field1, n->data[i_230772].Field2, n->data[i_230772].Field0, j);
				}
				LA8: ;
				nimln(1614, "system.nim");
				TMP1213 = addInt(res_230829, ((NI) 1));
				res_230829 = (NI)(TMP1213);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_230683)(Table230371* t, NI64 key, void* val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(248, "tables.nim");
	index = rawget_230633((*t), key, (&hc));
	nimln(249, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2 = val;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP1214;
		NI TMP1215;
		nimln(239, "tables.nim");
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = mustrehash_227313(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(240, "tables.nim");
			enlarge_230720(t);
			nimln(241, "tables.nim");
			index = rawgetknownhc_230774((*t), key, hc);
		}
		LA9: ;
		nimln(242, "tables.nim");
		TMP1214 = subInt(((NI) -1), index);
		index = (NI)(TMP1214);
		nimln(243, "tables.nim");
		rawinsert_230800(t, (&(*t).data), key, val, hc, index);
		nimln(244, "tables.nim");
		TMP1215 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP1215);
	}
	LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void) {
static TNimNode* TMP1209[3];
static TNimNode TMP1156[4];
NTI230377.size = sizeof(Keyvaluepair230377);
NTI230377.kind = 18;
NTI230377.base = 0;
NTI230377.flags = 3;
TMP1209[0] = &TMP1156[1];
TMP1156[1].kind = 1;
TMP1156[1].offset = offsetof(Keyvaluepair230377, Field0);
TMP1156[1].typ = (&NTI116023);
TMP1156[1].name = "Field0";
TMP1209[1] = &TMP1156[2];
TMP1156[2].kind = 1;
TMP1156[2].offset = offsetof(Keyvaluepair230377, Field1);
TMP1156[2].typ = (&NTI5710);
TMP1156[2].name = "Field1";
TMP1209[2] = &TMP1156[3];
TMP1156[3].kind = 1;
TMP1156[3].offset = offsetof(Keyvaluepair230377, Field2);
TMP1156[3].typ = (&NTI153);
TMP1156[3].name = "Field2";
TMP1156[0].len = 3; TMP1156[0].kind = 2; TMP1156[0].sons = &TMP1209[0];
NTI230377.node = &TMP1156[0];
NTI230374.size = sizeof(Keyvaluepairseq230374*);
NTI230374.kind = 24;
NTI230374.base = (&NTI230377);
NTI230374.flags = 2;
NTI230374.marker = TMP1210;
}

