/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\stdlib_streams.o c:\users\owner\documents\nim\esfj\nimcache\stdlib_streams.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct Ioerror3431 Ioerror3431;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Systemerror3429 Systemerror3429;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Streamobj179027 Streamobj179027;
typedef struct Stringstreamobj179554 Stringstreamobj179554;
typedef struct Filestreamobj179692 Filestreamobj179692;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3429  {
  Exception Sup;
};
struct  Ioerror3431  {
  Systemerror3429 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef N_NIMCALL_PTR(void, TY179028) (Streamobj179027* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY179032) (Streamobj179027* s);
typedef N_NIMCALL_PTR(void, TY179036) (Streamobj179027* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY179041) (Streamobj179027* s);
typedef N_NIMCALL_PTR(NI, TY179045) (Streamobj179027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY179051) (Streamobj179027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY179057) (Streamobj179027* s);
struct  Streamobj179027  {
  TNimObject Sup;
TY179028 closeimpl;
TY179032 atendimpl;
TY179036 setpositionimpl;
TY179041 getpositionimpl;
TY179045 readdataimpl;
TY179051 writedataimpl;
TY179057 flushimpl;
};
struct  Stringstreamobj179554  {
  Streamobj179027 Sup;
NimStringDesc* data;
NI pos;
};
struct  Filestreamobj179692  {
  Streamobj179027 Sup;
FILE* f;
};
typedef NI TY27820[8];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
N_NIMCALL(Ioerror3431*, neweio_179005)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void, flush_179069)(Streamobj179027* s);
N_NIMCALL(void, close_179085)(Streamobj179027* s);
N_NIMCALL(void, close_179101)(Streamobj179027* s, Streamobj179027* unused);
N_NIMCALL(NIM_BOOL, atend_179111)(Streamobj179027* s);
N_NIMCALL(NIM_BOOL, atend_179121)(Streamobj179027* s, Streamobj179027* unused);
N_NIMCALL(void, setposition_179132)(Streamobj179027* s, NI pos);
N_NIMCALL(void, setposition_179142)(Streamobj179027* s, Streamobj179027* unused, NI pos);
N_NIMCALL(NI, getposition_179153)(Streamobj179027* s);
N_NIMCALL(NI, getposition_179163)(Streamobj179027* s, Streamobj179027* unused);
N_NIMCALL(NI, readdata_179174)(Streamobj179027* s, void* buffer, NI buflen);
N_NIMCALL(NI, readdata_179186)(Streamobj179027* s, Streamobj179027* unused, void* buffer, NI buflen);
N_NIMCALL(void, writedata_179199)(Streamobj179027* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_179210)(Streamobj179027* s, Streamobj179027* unused, void* buffer, NI buflen);
N_NIMCALL(void, write_179233)(Streamobj179027* s, NimStringDesc* x);
N_NIMCALL(void, writeln_179243)(Streamobj179027* s, NimStringDesc** args, NI argsLen0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NIM_CHAR, readchar_179287)(Streamobj179027* s);
N_NIMCALL(void, read_179303)(Streamobj179027* s, NIM_BOOL* result);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, readbool_179298)(Streamobj179027* s);
N_NIMCALL(void, read_179331)(Streamobj179027* s, NI8* result);
N_NIMCALL(NI8, readint8_179326)(Streamobj179027* s);
N_NIMCALL(void, read_179359)(Streamobj179027* s, NI16* result);
N_NIMCALL(NI16, readint16_179354)(Streamobj179027* s);
N_NIMCALL(void, read_179387)(Streamobj179027* s, NI32* result);
N_NIMCALL(NI32, readint32_179382)(Streamobj179027* s);
N_NIMCALL(void, read_179415)(Streamobj179027* s, NI64* result);
N_NIMCALL(NI64, readint64_179410)(Streamobj179027* s);
N_NIMCALL(void, read_179443)(Streamobj179027* s, NF32* result);
N_NIMCALL(NF32, readfloat32_179438)(Streamobj179027* s);
N_NIMCALL(void, read_179471)(Streamobj179027* s, NF* result);
N_NIMCALL(NF, readfloat64_179466)(Streamobj179027* s);
N_NIMCALL(NimStringDesc*, readstr_179494)(Streamobj179027* s, NI length);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NIM_BOOL, readline_179509)(Streamobj179027* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, readline_179531)(Streamobj179027* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, ssatend_179565)(Streamobj179027* s_179567);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NI, clamp_179582)(NI x, NI a, NI b);
N_NIMCALL(void, sssetposition_179576)(Streamobj179027* s_179578, NI pos);
N_NIMCALL(NI, ssgetposition_179601)(Streamobj179027* s_179603);
N_NIMCALL(NI, ssreaddata_179612)(Streamobj179027* s_179614, void* buffer, NI buflen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, sswritedata_179639)(Streamobj179027* s_179641, void* buffer, NI buflen);
N_NIMCALL(void, ssclose_179661)(Streamobj179027* s_179663);
N_NIMCALL(Stringstreamobj179554*, newstringstream_179671)(NimStringDesc* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP726)(void* p, NI op);
N_NIMCALL(void, fsclose_179696)(Streamobj179027* s);
N_NIMCALL(void, fsflush_179714)(Streamobj179027* s);
N_NIMCALL(NIM_BOOL, fsatend_179720)(Streamobj179027* s);
N_NIMCALL(NIM_BOOL, endoffile_13422)(FILE* f);
N_NIMCALL(void, fssetposition_179727)(Streamobj179027* s, NI pos);
N_NIMCALL(void, setfilepos_13542)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_179734)(Streamobj179027* s);
N_NIMCALL(NI64, getfilepos_13546)(FILE* f);
N_NIMCALL(NI, fsreaddata_179742)(Streamobj179027* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_13515)(FILE* f, void* buffer, NI len);
N_NIMCALL(void, fswritedata_179751)(Streamobj179027* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_13537)(FILE* f, void* buffer, NI len);
N_NIMCALL(Filestreamobj179692*, newfilestream_179759)(FILE* f);
N_NIMCALL(void, TMP728)(void* p, NI op);
N_NIMCALL(Filestreamobj179692*, newfilestream_179774)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(NIM_BOOL, open_13203)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, TMP1071)(void* p, NI op);
STRING_LITERAL(TMP716, "\015\012", 2);
STRING_LITERAL(TMP717, "cannot read from stream", 23);
STRING_LITERAL(TMP718, "", 0);
STRING_LITERAL(TMP727, "cannot write to stream", 22);
extern TNimType NTI13401; /* ref IOError */
extern TNimType NTI3431; /* IOError */
extern TFrame* frameptr_17042;
extern Tgcheap48616 gch_48644;
extern TNimType NTI3411; /* RootObj */
TNimType NTI179027; /* StreamObj */
TNimType NTI179028; /* proc (s: Stream){.gcsafe.} */
TNimType NTI179032; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI179036; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI179041; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI179045; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI179051; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI179057; /* proc (s: Stream){.gcsafe.} */
TNimType NTI179554; /* StringStreamObj */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
TNimType NTI179552; /* StringStream */
TNimType NTI179692; /* FileStreamObj */
extern TNimType NTI13004; /* File */
TNimType NTI179690; /* FileStream */
TNimType NTI179025; /* Stream */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Ioerror3431*, neweio_179005)(NimStringDesc* msg) {
	Ioerror3431* result;
	NimStringDesc* LOC1;
	nimfr("newEIO", "streams.nim")
	result = 0;
	nimln(18, "streams.nim");
	result = (Ioerror3431*) newObj((&NTI13401), sizeof(Ioerror3431));
	(*result).Sup.Sup.Sup.m_type = (&NTI3431);
	nimln(19, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, flush_179069)(Streamobj179027* s) {
	nimfr("flush", "streams.nim")
	nimln(42, "streams.nim");
	{
		if (!!((*s).flushimpl == 0)) goto LA3;
		(*s).flushimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_179085)(Streamobj179027* s) {
	nimfr("close", "streams.nim")
	nimln(46, "streams.nim");
	{
		if (!!((*s).closeimpl == 0)) goto LA3;
		(*s).closeimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_179101)(Streamobj179027* s, Streamobj179027* unused) {
	nimfr("close", "streams.nim")
	nimln(50, "streams.nim");
	(*s).closeimpl(s);
	popFrame();
}

N_NIMCALL(NIM_BOOL, atend_179111)(Streamobj179027* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(55, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, atend_179121)(Streamobj179027* s, Streamobj179027* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(60, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(void, setposition_179132)(Streamobj179027* s, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(64, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(void, setposition_179142)(Streamobj179027* s, Streamobj179027* unused, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(68, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(NI, getposition_179153)(Streamobj179027* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(72, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, getposition_179163)(Streamobj179027* s, Streamobj179027* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(76, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_179174)(Streamobj179027* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(80, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_179186)(Streamobj179027* s, Streamobj179027* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(85, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, writedata_179199)(Streamobj179027* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(90, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, writedata_179210)(Streamobj179027* s, Streamobj179027* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(96, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, write_179233)(Streamobj179027* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")
	nimln(111, "streams.nim");
	writedata_179199(s, ((void*) (x->data)), (x ? x->Sup.len : 0));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, writeln_179243)(Streamobj179027* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeln", "streams.nim")
	{
		NimStringDesc* str_179256;
		NI i_179260;
		str_179256 = 0;
		nimln(1689, "system.nim");
		i_179260 = ((NI) 0);
		{
			nimln(1690, "system.nim");
			while (1) {
				NI TMP715;
				if (!(i_179260 < argsLen0)) goto LA3;
				nimln(1691, "system.nim");
				if ((NU)(i_179260) >= (NU)(argsLen0)) raiseIndexError();
				str_179256 = args[i_179260];
				nimln(116, "streams.nim");
				write_179233(s, str_179256);
				nimln(1692, "system.nim");
				TMP715 = addInt(i_179260, ((NI) 1));
				i_179260 = (NI)(TMP715);
			} LA3: ;
		}
	}
	nimln(117, "streams.nim");
	write_179233(s, ((NimStringDesc*) &TMP716));
	popFrame();
}

N_NIMCALL(NIM_CHAR, readchar_179287)(Streamobj179027* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
	nimln(127, "streams.nim");
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) ((&result))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, read_179303)(Streamobj179027* s, NIM_BOOL* result) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP717));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readbool_179298)(Streamobj179027* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
	nimln(131, "streams.nim");
	read_179303(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_179331)(Streamobj179027* s, NI8* result) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP717));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, readint8_179326)(Streamobj179027* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
	nimln(135, "streams.nim");
	read_179331(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_179359)(Streamobj179027* s, NI16* result) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) (result)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP717));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, readint16_179354)(Streamobj179027* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
	nimln(139, "streams.nim");
	read_179359(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_179387)(Streamobj179027* s, NI32* result) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP717));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, readint32_179382)(Streamobj179027* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
	nimln(143, "streams.nim");
	read_179387(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_179415)(Streamobj179027* s, NI64* result) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP717));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, readint64_179410)(Streamobj179027* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
	nimln(147, "streams.nim");
	read_179415(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_179443)(Streamobj179027* s, NF32* result) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP717));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, readfloat32_179438)(Streamobj179027* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
	nimln(151, "streams.nim");
	read_179443(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_179471)(Streamobj179027* s, NF* result) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = readdata_179174(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP717));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, readfloat64_179466)(Streamobj179027* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
	nimln(155, "streams.nim");
	read_179471(s, (&result));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, readstr_179494)(Streamobj179027* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("readStr", "streams.nim")
	result = 0;
	nimln(160, "streams.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(161, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	L = readdata_179174(s, ((void*) ((&result->data[((NI) 0)]))), length);
	nimln(162, "streams.nim");
	{
		if (!!((L == length))) goto LA3;
		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readline_179509)(Streamobj179027* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
{	result = 0;
	nimln(171, "streams.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln(172, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(173, "streams.nim");
			c = readchar_179287(s);
			nimln(174, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(175, "streams.nim");
				c = readchar_179287(s);
				nimln(176, "streams.nim");
				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
				nimln(177, "streams.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA8;
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				nimln(178, "streams.nim");
				if (!((NU8)(c) == (NU8)(0))) goto LA11;
				nimln(179, "streams.nim");
				{
					if (!(((NI) 0) < ((*line) ? (*line)->Sup.len : 0))) goto LA15;
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
					nimln(180, "streams.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;
			nimln(181, "streams.nim");
			(*line) = addChar((*line), c);
		}
	} LA1: ;
	nimln(182, "streams.nim");
	result = NIM_TRUE;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readline_179531)(Streamobj179027* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(187, "streams.nim");
	result = copyString(((NimStringDesc*) &TMP718));
	{
		nimln(188, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(189, "streams.nim");
			c = readchar_179287(s);
			nimln(190, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(191, "streams.nim");
				c = readchar_179287(s);
				nimln(192, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(193, "streams.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = ((NU8)(c) == (NU8)(10));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(c) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				nimln(194, "streams.nim");
				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
				nimln(196, "streams.nim");
				result = addChar(result, c);
			}
			LA7: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ssatend_179565)(Streamobj179027* s_179567) {
	NIM_BOOL result;
	Stringstreamobj179554* s;
	nimfr("ssAtEnd", "streams.nim")
{	result = 0;
	nimln(207, "streams.nim");
	if (s_179567) chckObj((*s_179567).Sup.m_type, (&NTI179554));
	s = ((Stringstreamobj179554*) (s_179567));
	nimln(208, "streams.nim");
	result = (((*s).data ? (*s).data->Sup.len : 0) <= (*s).pos);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sssetposition_179576)(Streamobj179027* s_179578, NI pos) {
	Stringstreamobj179554* s;
	nimfr("ssSetPosition", "streams.nim")
	nimln(211, "streams.nim");
	if (s_179578) chckObj((*s_179578).Sup.m_type, (&NTI179554));
	s = ((Stringstreamobj179554*) (s_179578));
	nimln(212, "streams.nim");
	(*s).pos = clamp_179582(pos, ((NI) 0), ((*s).data ? ((*s).data->Sup.len-1) : -1));
	popFrame();
}

N_NIMCALL(NI, ssgetposition_179601)(Streamobj179027* s_179603) {
	NI result;
	Stringstreamobj179554* s;
	nimfr("ssGetPosition", "streams.nim")
{	result = 0;
	nimln(215, "streams.nim");
	if (s_179603) chckObj((*s_179603).Sup.m_type, (&NTI179554));
	s = ((Stringstreamobj179554*) (s_179603));
	nimln(216, "streams.nim");
	result = (*s).pos;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, ssreaddata_179612)(Streamobj179027* s_179614, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj179554* s;
	NI TMP721;
	nimfr("ssReadData", "streams.nim")
	result = 0;
	nimln(219, "streams.nim");
	if (s_179614) chckObj((*s_179614).Sup.m_type, (&NTI179554));
	s = ((Stringstreamobj179554*) (s_179614));
	nimln(220, "streams.nim");
	TMP721 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);
	result = ((buflen <= (NI)(TMP721)) ? buflen : (NI)(TMP721));
	nimln(221, "streams.nim");
	{
		NI TMP722;
		if (!(((NI) 0) < result)) goto LA3;
		nimln(222, "streams.nim");
		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(223, "streams.nim");
		TMP722 = addInt((*s).pos, result);
		(*s).pos = (NI)(TMP722);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sswritedata_179639)(Streamobj179027* s_179641, void* buffer, NI buflen) {
	Stringstreamobj179554* s;
	NI TMP725;
	nimfr("ssWriteData", "streams.nim")
{	nimln(226, "streams.nim");
	if (s_179641) chckObj((*s_179641).Sup.m_type, (&NTI179554));
	s = ((Stringstreamobj179554*) (s_179641));
	nimln(227, "streams.nim");
	{
		if (!(buflen <= ((NI) 0))) goto LA3;
		nimln(228, "streams.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(229, "streams.nim");
	{
		NI TMP723;
		NI TMP724;
		TMP723 = addInt((*s).pos, buflen);
		if (!(((*s).data ? (*s).data->Sup.len : 0) < (NI)(TMP723))) goto LA7;
		nimln(230, "streams.nim");
		TMP724 = addInt((*s).pos, buflen);
		(*s).data = setLengthStr((*s).data, ((NI)chckRange((NI)(TMP724), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA7: ;
	nimln(231, "streams.nim");
	if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
	memcpy(((void*) ((&(*s).data->data[(*s).pos]))), buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(232, "streams.nim");
	TMP725 = addInt((*s).pos, buflen);
	(*s).pos = (NI)(TMP725);
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, ssclose_179661)(Streamobj179027* s_179663) {
	Stringstreamobj179554* s;
	NimStringDesc* LOC1;
	nimfr("ssClose", "streams.nim")
	nimln(235, "streams.nim");
	if (s_179663) chckObj((*s_179663).Sup.m_type, (&NTI179554));
	s = ((Stringstreamobj179554*) (s_179663));
	nimln(236, "streams.nim");
	LOC1 = 0;
	LOC1 = (*s).data; (*s).data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP726)(void* p, NI op) {
	Stringstreamobj179554* a;
	a = (Stringstreamobj179554*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_NIMCALL(Stringstreamobj179554*, newstringstream_179671)(NimStringDesc* s) {
	Stringstreamobj179554* result;
	NimStringDesc* LOC1;
	nimfr("newStringStream", "streams.nim")
	result = 0;
	nimln(240, "streams.nim");
	result = (Stringstreamobj179554*) newObj((&NTI179552), sizeof(Stringstreamobj179554));
	(*result).Sup.Sup.m_type = (&NTI179554);
	nimln(241, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).data; (*result).data = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(242, "streams.nim");
	(*result).pos = ((NI) 0);
	nimln(243, "streams.nim");
	(*result).Sup.closeimpl = ssclose_179661;
	nimln(244, "streams.nim");
	(*result).Sup.atendimpl = ssatend_179565;
	nimln(245, "streams.nim");
	(*result).Sup.setpositionimpl = sssetposition_179576;
	nimln(246, "streams.nim");
	(*result).Sup.getpositionimpl = ssgetposition_179601;
	nimln(247, "streams.nim");
	(*result).Sup.readdataimpl = ssreaddata_179612;
	nimln(248, "streams.nim");
	(*result).Sup.writedataimpl = sswritedata_179639;
	popFrame();
	return result;
}

N_NIMCALL(void, fsclose_179696)(Streamobj179027* s) {
	nimfr("fsClose", "streams.nim")
	nimln(259, "streams.nim");
	{
		if (s) chckObj((*s).Sup.m_type, (&NTI179692));
		if (!!(((*((Filestreamobj179692*) (s))).f == NIM_NIL))) goto LA3;
		nimln(260, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI179692));
		fclose((*((Filestreamobj179692*) (s))).f);
		nimln(261, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI179692));
		(*((Filestreamobj179692*) (s))).f = NIM_NIL;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, fsflush_179714)(Streamobj179027* s) {
	nimfr("fsFlush", "streams.nim")
	nimln(262, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI179692));
	fflush((*((Filestreamobj179692*) (s))).f);
	popFrame();
}

N_NIMCALL(NIM_BOOL, fsatend_179720)(Streamobj179027* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
{	result = 0;
	nimln(263, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI179692));
	result = endoffile_13422((*((Filestreamobj179692*) (s))).f);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fssetposition_179727)(Streamobj179027* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")
	nimln(264, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI179692));
	setfilepos_13542((*((Filestreamobj179692*) (s))).f, ((NI64) (pos)));
	popFrame();
}

N_NIMCALL(NI, fsgetposition_179734)(Streamobj179027* s) {
	NI result;
	NI64 LOC1;
	nimfr("fsGetPosition", "streams.nim")
{	result = 0;
	nimln(265, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI179692));
	LOC1 = 0;
	LOC1 = getfilepos_13546((*((Filestreamobj179692*) (s))).f);
	result = ((NI) (LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fsreaddata_179742)(Streamobj179027* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
	nimln(268, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI179692));
	result = readbuffer_13515((*((Filestreamobj179692*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_NIMCALL(void, fswritedata_179751)(Streamobj179027* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")
	nimln(271, "streams.nim");
	{
		NI LOC3;
		Ioerror3431* LOC6;
		if (s) chckObj((*s).Sup.m_type, (&NTI179692));
		LOC3 = 0;
		LOC3 = writebuffer_13537((*((Filestreamobj179692*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		if (!!((LOC3 == buflen))) goto LA4;
		nimln(272, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_179005(((NimStringDesc*) &TMP727));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}
N_NIMCALL(void, TMP728)(void* p, NI op) {
	Filestreamobj179692* a;
	a = (Filestreamobj179692*)p;
}

N_NIMCALL(Filestreamobj179692*, newfilestream_179759)(FILE* f) {
	Filestreamobj179692* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	nimln(276, "streams.nim");
	result = (Filestreamobj179692*) newObj((&NTI179690), sizeof(Filestreamobj179692));
	(*result).Sup.Sup.m_type = (&NTI179692);
	nimln(277, "streams.nim");
	(*result).f = f;
	nimln(278, "streams.nim");
	(*result).Sup.closeimpl = fsclose_179696;
	nimln(279, "streams.nim");
	(*result).Sup.atendimpl = fsatend_179720;
	nimln(280, "streams.nim");
	(*result).Sup.setpositionimpl = fssetposition_179727;
	nimln(281, "streams.nim");
	(*result).Sup.getpositionimpl = fsgetposition_179734;
	nimln(282, "streams.nim");
	(*result).Sup.readdataimpl = fsreaddata_179742;
	nimln(283, "streams.nim");
	(*result).Sup.writedataimpl = fswritedata_179751;
	nimln(284, "streams.nim");
	(*result).Sup.flushimpl = fsflush_179714;
	popFrame();
	return result;
}

N_NIMCALL(Filestreamobj179692*, newfilestream_179774)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj179692* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	f = 0;
	nimln(291, "streams.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = open_13203(&f, filename, mode, ((NI) -1));
		if (!LOC3) goto LA4;
		result = newfilestream_179759(f);
	}
	LA4: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP1071)(void* p, NI op) {
	Streamobj179027* a;
	a = (Streamobj179027*)p;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void) {
	nimfr("streams", "streams.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void) {
static TNimNode* TMP719[7];
static TNimNode* TMP720[2];
static TNimNode TMP713[12];
NTI179027.size = sizeof(Streamobj179027);
NTI179027.kind = 17;
NTI179027.base = (&NTI3411);
NTI179027.flags = 1;
TMP719[0] = &TMP713[1];
NTI179028.size = sizeof(TY179028);
NTI179028.kind = 25;
NTI179028.base = 0;
NTI179028.flags = 3;
TMP713[1].kind = 1;
TMP713[1].offset = offsetof(Streamobj179027, closeimpl);
TMP713[1].typ = (&NTI179028);
TMP713[1].name = "closeImpl";
TMP719[1] = &TMP713[2];
NTI179032.size = sizeof(TY179032);
NTI179032.kind = 25;
NTI179032.base = 0;
NTI179032.flags = 3;
TMP713[2].kind = 1;
TMP713[2].offset = offsetof(Streamobj179027, atendimpl);
TMP713[2].typ = (&NTI179032);
TMP713[2].name = "atEndImpl";
TMP719[2] = &TMP713[3];
NTI179036.size = sizeof(TY179036);
NTI179036.kind = 25;
NTI179036.base = 0;
NTI179036.flags = 3;
TMP713[3].kind = 1;
TMP713[3].offset = offsetof(Streamobj179027, setpositionimpl);
TMP713[3].typ = (&NTI179036);
TMP713[3].name = "setPositionImpl";
TMP719[3] = &TMP713[4];
NTI179041.size = sizeof(TY179041);
NTI179041.kind = 25;
NTI179041.base = 0;
NTI179041.flags = 3;
TMP713[4].kind = 1;
TMP713[4].offset = offsetof(Streamobj179027, getpositionimpl);
TMP713[4].typ = (&NTI179041);
TMP713[4].name = "getPositionImpl";
TMP719[4] = &TMP713[5];
NTI179045.size = sizeof(TY179045);
NTI179045.kind = 25;
NTI179045.base = 0;
NTI179045.flags = 3;
TMP713[5].kind = 1;
TMP713[5].offset = offsetof(Streamobj179027, readdataimpl);
TMP713[5].typ = (&NTI179045);
TMP713[5].name = "readDataImpl";
TMP719[5] = &TMP713[6];
NTI179051.size = sizeof(TY179051);
NTI179051.kind = 25;
NTI179051.base = 0;
NTI179051.flags = 3;
TMP713[6].kind = 1;
TMP713[6].offset = offsetof(Streamobj179027, writedataimpl);
TMP713[6].typ = (&NTI179051);
TMP713[6].name = "writeDataImpl";
TMP719[6] = &TMP713[7];
NTI179057.size = sizeof(TY179057);
NTI179057.kind = 25;
NTI179057.base = 0;
NTI179057.flags = 3;
TMP713[7].kind = 1;
TMP713[7].offset = offsetof(Streamobj179027, flushimpl);
TMP713[7].typ = (&NTI179057);
TMP713[7].name = "flushImpl";
TMP713[0].len = 7; TMP713[0].kind = 2; TMP713[0].sons = &TMP719[0];
NTI179027.node = &TMP713[0];
NTI179554.size = sizeof(Stringstreamobj179554);
NTI179554.kind = 17;
NTI179554.base = (&NTI179027);
TMP720[0] = &TMP713[9];
TMP713[9].kind = 1;
TMP713[9].offset = offsetof(Stringstreamobj179554, data);
TMP713[9].typ = (&NTI149);
TMP713[9].name = "data";
TMP720[1] = &TMP713[10];
TMP713[10].kind = 1;
TMP713[10].offset = offsetof(Stringstreamobj179554, pos);
TMP713[10].typ = (&NTI108);
TMP713[10].name = "pos";
TMP713[8].len = 2; TMP713[8].kind = 2; TMP713[8].sons = &TMP720[0];
NTI179554.node = &TMP713[8];
NTI179552.size = sizeof(Stringstreamobj179554*);
NTI179552.kind = 22;
NTI179552.base = (&NTI179554);
NTI179552.marker = TMP726;
NTI179692.size = sizeof(Filestreamobj179692);
NTI179692.kind = 17;
NTI179692.base = (&NTI179027);
NTI179692.flags = 1;
TMP713[11].kind = 1;
TMP713[11].offset = offsetof(Filestreamobj179692, f);
TMP713[11].typ = (&NTI13004);
TMP713[11].name = "f";
NTI179692.node = &TMP713[11];
NTI179690.size = sizeof(Filestreamobj179692*);
NTI179690.kind = 22;
NTI179690.base = (&NTI179692);
NTI179690.marker = TMP728;
NTI179025.size = sizeof(Streamobj179027*);
NTI179025.kind = 22;
NTI179025.base = (&NTI179027);
NTI179025.marker = TMP1071;
}

