/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\stdlib_lexbase.o c:\users\owner\documents\nim\esfj\nimcache\stdlib_lexbase.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct Baselexer191021 Baselexer191021;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Streamobj179027 Streamobj179027;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 TY77659[32];
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Baselexer191021  {
  TNimObject Sup;
NI bufpos;
NCSTRING buf;
NI buflen;
Streamobj179027* input;
NI linenumber;
NI sentinel;
NI linestart;
NIM_BOOL fileopened;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY179028) (Streamobj179027* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY179032) (Streamobj179027* s);
typedef N_NIMCALL_PTR(void, TY179036) (Streamobj179027* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY179041) (Streamobj179027* s);
typedef N_NIMCALL_PTR(NI, TY179045) (Streamobj179027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY179051) (Streamobj179027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY179057) (Streamobj179027* s);
struct  Streamobj179027  {
  TNimObject Sup;
TY179028 closeimpl;
TY179032 atendimpl;
TY179036 setpositionimpl;
TY179041 getpositionimpl;
TY179045 readdataimpl;
TY179051 writedataimpl;
TY179057 flushimpl;
};
N_NIMCALL(void, close_191047)(Baselexer191021* L);
N_NOCONV(void, dealloc_6048)(void* p);
N_NIMCALL(void, close_179085)(Streamobj179027* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, fillbuffer_191099)(Baselexer191021* L);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, readdata_179174)(Streamobj179027* s, void* buffer, NI buflen);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOCONV(void*, realloc_6033)(void* p, NI newsize);
N_NIMCALL(NI, fillbaselexer_191827)(Baselexer191021* L, NI pos);
N_NIMCALL(NI, handlecr_191068)(Baselexer191021* L, NI pos);
N_NIMCALL(NI, handlelf_191076)(Baselexer191021* L, NI pos);
N_NIMCALL(void, skiputf8bom_192416)(Baselexer191021* L);
N_NIMCALL(void, open_191037)(Baselexer191021* L, Streamobj179027* input, NI buflen);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NOCONV(void*, alloc_6001)(NI size);
N_NIMCALL(NI, getcolnumber_191061)(Baselexer191021* L, NI pos);
N_NIMCALL(NimStringDesc*, getcurrentline_191054)(Baselexer191021* L, NIM_BOOL marker);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
NIM_CONST TY77659 Newlines_191015 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP826, "L.sentinel < L.bufLen ", 22);
STRING_LITERAL(TMP829, "0 <= toCopy ", 12);
STRING_LITERAL(TMP838, "s < L.bufLen ", 13);
STRING_LITERAL(TMP843, "L.bufLen - oldBufLen == oldBufLen ", 34);
STRING_LITERAL(TMP849, "pos <= L.sentinel ", 18);
STRING_LITERAL(TMP851, "L.buf[pos] == \'\\x0D\' ", 21);
STRING_LITERAL(TMP853, "L.buf[pos] == \'\\x0A\' ", 21);
STRING_LITERAL(TMP857, "0 < bufLen ", 11);
STRING_LITERAL(TMP858, "not (input == nil) ", 19);
STRING_LITERAL(TMP862, "", 0);
STRING_LITERAL(TMP864, "\015\012", 2);
STRING_LITERAL(TMP865, "^\015\012", 3);
extern TFrame* frameptr_17042;
extern TNimType NTI3411; /* RootObj */
TNimType NTI191021; /* BaseLexer */
extern TNimType NTI108; /* int */
extern TNimType NTI151; /* cstring */
extern TNimType NTI179025; /* Stream */
extern TNimType NTI138; /* bool */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, close_191047)(Baselexer191021* L) {
	nimfr("close", "lexbase.nim")
	nimln(68, "lexbase.nim");
	dealloc_6048(((void*) ((*L).buf)));
	nimln(69, "lexbase.nim");
	close_179085((*L).input);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, fillbuffer_191099)(Baselexer191021* L) {
	NI charsread;
	NI tocopy;
	NI s;
	NI oldbuflen;
	NI TMP827;
	NI TMP828;
	NI TMP832;
	NI TMP833;
	NI LOC13;
	NI TMP834;
	NI TMP835;
	nimfr("fillBuffer", "lexbase.nim")
	charsread = 0;
	tocopy = 0;
	s = 0;
	oldbuflen = 0;
	nimln(79, "lexbase.nim");
	{
		if (!!(((*L).sentinel < (*L).buflen))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP826));
	}
	LA3: ;
	nimln(80, "lexbase.nim");
	TMP827 = subInt((*L).buflen, (*L).sentinel);
	TMP828 = subInt((NI)(TMP827), ((NI) 1));
	tocopy = (NI)(TMP828);
	nimln(81, "lexbase.nim");
	{
		if (!!((((NI) 0) <= tocopy))) goto LA7;
		failedassertimpl_88817(((NimStringDesc*) &TMP829));
	}
	LA7: ;
	nimln(82, "lexbase.nim");
	{
		NI TMP830;
		NI TMP831;
		if (!(((NI) 0) < tocopy)) goto LA11;
		nimln(83, "lexbase.nim");
		TMP830 = addInt((*L).sentinel, ((NI) 1));
		TMP831 = mulInt(tocopy, ((NI) 1));
		memmove(((void*) ((*L).buf)), ((void*) ((&(*L).buf[(NI)(TMP830)]))), ((NI)chckRange((NI)(TMP831), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA11: ;
	nimln(85, "lexbase.nim");
	nimln(86, "lexbase.nim");
	nimln(85, "lexbase.nim");
	nimln(86, "lexbase.nim");
	TMP832 = addInt((*L).sentinel, ((NI) 1));
	TMP833 = mulInt((NI)(TMP832), ((NI) 1));
	LOC13 = 0;
	LOC13 = readdata_179174((*L).input, ((void*) ((&(*L).buf[tocopy]))), (NI)(TMP833));
	TMP834 = divInt(LOC13, ((NI) 1));
	charsread = (NI)(TMP834);
	nimln(87, "lexbase.nim");
	TMP835 = addInt(tocopy, charsread);
	s = (NI)(TMP835);
	nimln(88, "lexbase.nim");
	{
		NI TMP836;
		TMP836 = addInt((*L).sentinel, ((NI) 1));
		if (!(charsread < (NI)(TMP836))) goto LA16;
		nimln(89, "lexbase.nim");
		(*L).buf[s] = 0;
		nimln(90, "lexbase.nim");
		(*L).sentinel = s;
	}
	goto LA14;
	LA16: ;
	{
		NI TMP837;
		nimln(93, "lexbase.nim");
		TMP837 = subInt(s, ((NI) 1));
		s = (NI)(TMP837);
		{
			nimln(94, "lexbase.nim");
			while (1) {
				nimln(95, "lexbase.nim");
				{
					if (!!((s < (*L).buflen))) goto LA23;
					failedassertimpl_88817(((NimStringDesc*) &TMP838));
				}
				LA23: ;
				{
					nimln(96, "lexbase.nim");
					while (1) {
						NIM_BOOL LOC27;
						NI TMP839;
						LOC27 = 0;
						LOC27 = (((NI) 0) <= s);
						if (!(LOC27)) goto LA28;
						LOC27 = !((((NU8)((*L).buf[s])) == ((NU8)(13)) || ((NU8)((*L).buf[s])) == ((NU8)(10))));
						LA28: ;
						if (!LOC27) goto LA26;
						TMP839 = subInt(s, ((NI) 1));
						s = (NI)(TMP839);
					} LA26: ;
				}
				nimln(97, "lexbase.nim");
				{
					if (!(((NI) 0) <= s)) goto LA31;
					nimln(99, "lexbase.nim");
					(*L).sentinel = s;
					nimln(100, "lexbase.nim");
					goto LA19;
				}
				goto LA29;
				LA31: ;
				{
					NI TMP840;
					NI TMP841;
					void* LOC34;
					NI TMP844;
					NI LOC39;
					NI TMP845;
					NI TMP848;
					nimln(104, "lexbase.nim");
					oldbuflen = (*L).buflen;
					nimln(105, "lexbase.nim");
					TMP840 = mulInt((*L).buflen, ((NI) 2));
					(*L).buflen = (NI)(TMP840);
					nimln(106, "lexbase.nim");
					TMP841 = mulInt((*L).buflen, ((NI) 1));
					LOC34 = 0;
					LOC34 = realloc_6033(((void*) ((*L).buf)), ((NI)chckRange((NI)(TMP841), ((NI) 0), ((NI) IL64(9223372036854775807)))));
					(*L).buf = ((NCSTRING) (LOC34));
					nimln(107, "lexbase.nim");
					{
						NI TMP842;
						TMP842 = subInt((*L).buflen, oldbuflen);
						if (!!(((NI)(TMP842) == oldbuflen))) goto LA37;
						failedassertimpl_88817(((NimStringDesc*) &TMP843));
					}
					LA37: ;
					nimln(108, "lexbase.nim");
					nimln(109, "lexbase.nim");
					nimln(108, "lexbase.nim");
					nimln(109, "lexbase.nim");
					TMP844 = mulInt(oldbuflen, ((NI) 1));
					LOC39 = 0;
					LOC39 = readdata_179174((*L).input, ((void*) ((&(*L).buf[oldbuflen]))), (NI)(TMP844));
					TMP845 = divInt(LOC39, ((NI) 1));
					charsread = (NI)(TMP845);
					nimln(110, "lexbase.nim");
					{
						NI TMP846;
						NI TMP847;
						if (!(charsread < oldbuflen)) goto LA42;
						nimln(111, "lexbase.nim");
						TMP846 = addInt(oldbuflen, charsread);
						(*L).buf[(NI)(TMP846)] = 0;
						nimln(112, "lexbase.nim");
						TMP847 = addInt(oldbuflen, charsread);
						(*L).sentinel = (NI)(TMP847);
						nimln(113, "lexbase.nim");
						goto LA19;
					}
					LA42: ;
					nimln(114, "lexbase.nim");
					TMP848 = subInt((*L).buflen, ((NI) 1));
					s = (NI)(TMP848);
				}
				LA29: ;
			}
		} LA19: ;
	}
	LA14: ;
	popFrame();
}

N_NIMCALL(NI, fillbaselexer_191827)(Baselexer191021* L, NI pos) {
	NI result;
	nimfr("fillBaseLexer", "lexbase.nim")
	result = 0;
	nimln(117, "lexbase.nim");
	{
		if (!!((pos <= (*L).sentinel))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP849));
	}
	LA3: ;
	nimln(118, "lexbase.nim");
	{
		NI TMP850;
		if (!(pos < (*L).sentinel)) goto LA7;
		nimln(119, "lexbase.nim");
		TMP850 = addInt(pos, ((NI) 1));
		result = (NI)(TMP850);
	}
	goto LA5;
	LA7: ;
	{
		nimln(121, "lexbase.nim");
		fillbuffer_191099(L);
		nimln(122, "lexbase.nim");
		(*L).bufpos = ((NI) 0);
		nimln(123, "lexbase.nim");
		result = ((NI) 0);
	}
	LA5: ;
	nimln(124, "lexbase.nim");
	(*L).linestart = result;
	popFrame();
	return result;
}

N_NIMCALL(NI, handlecr_191068)(Baselexer191021* L, NI pos) {
	NI result;
	NI TMP852;
	nimfr("handleCR", "lexbase.nim")
	result = 0;
	nimln(127, "lexbase.nim");
	{
		if (!!(((NU8)((*L).buf[pos]) == (NU8)(13)))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP851));
	}
	LA3: ;
	nimln(128, "lexbase.nim");
	TMP852 = addInt((*L).linenumber, ((NI) 1));
	(*L).linenumber = (NI)(TMP852);
	nimln(129, "lexbase.nim");
	result = fillbaselexer_191827(L, pos);
	nimln(130, "lexbase.nim");
	{
		if (!((NU8)((*L).buf[result]) == (NU8)(10))) goto LA7;
		nimln(131, "lexbase.nim");
		result = fillbaselexer_191827(L, result);
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, handlelf_191076)(Baselexer191021* L, NI pos) {
	NI result;
	NI TMP854;
	nimfr("handleLF", "lexbase.nim")
	result = 0;
	nimln(134, "lexbase.nim");
	{
		if (!!(((NU8)((*L).buf[pos]) == (NU8)(10)))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP853));
	}
	LA3: ;
	nimln(135, "lexbase.nim");
	TMP854 = addInt((*L).linenumber, ((NI) 1));
	(*L).linenumber = (NI)(TMP854);
	nimln(136, "lexbase.nim");
	result = fillbaselexer_191827(L, pos);
	popFrame();
	return result;
}

N_NIMCALL(void, skiputf8bom_192416)(Baselexer191021* L) {
	nimfr("skipUtf8Bom", "lexbase.nim")
	nimln(139, "lexbase.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NI TMP855;
		NI TMP856;
		LOC3 = 0;
		LOC4 = 0;
		LOC4 = ((NU8)((*L).buf[((NI) 0)]) == (NU8)(239));
		if (!(LOC4)) goto LA5;
		LOC4 = ((NU8)((*L).buf[((NI) 1)]) == (NU8)(187));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		LOC3 = ((NU8)((*L).buf[((NI) 2)]) == (NU8)(191));
		LA6: ;
		if (!LOC3) goto LA7;
		nimln(140, "lexbase.nim");
		TMP855 = addInt((*L).bufpos, ((NI) 3));
		(*L).bufpos = (NI)(TMP855);
		nimln(141, "lexbase.nim");
		TMP856 = addInt((*L).linestart, ((NI) 3));
		(*L).linestart = (NI)(TMP856);
	}
	LA7: ;
	popFrame();
}

N_NIMCALL(void, open_191037)(Baselexer191021* L, Streamobj179027* input, NI buflen) {
	NI TMP859;
	void* LOC9;
	NI TMP860;
	nimfr("open", "lexbase.nim")
	nimln(144, "lexbase.nim");
	{
		if (!!((((NI) 0) < buflen))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP857));
	}
	LA3: ;
	nimln(145, "lexbase.nim");
	{
		if (!!(!((input == NIM_NIL)))) goto LA7;
		failedassertimpl_88817(((NimStringDesc*) &TMP858));
	}
	LA7: ;
	nimln(146, "lexbase.nim");
	unsureAsgnRef((void**) (&(*L).input), input);
	nimln(147, "lexbase.nim");
	(*L).bufpos = ((NI) 0);
	nimln(148, "lexbase.nim");
	(*L).buflen = buflen;
	nimln(149, "lexbase.nim");
	TMP859 = mulInt(buflen, ((NI) 1));
	LOC9 = 0;
	LOC9 = alloc_6001(((NI)chckRange((NI)(TMP859), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	(*L).buf = ((NCSTRING) (LOC9));
	nimln(150, "lexbase.nim");
	TMP860 = subInt(buflen, ((NI) 1));
	(*L).sentinel = (NI)(TMP860);
	nimln(151, "lexbase.nim");
	(*L).linestart = ((NI) 0);
	nimln(152, "lexbase.nim");
	(*L).linenumber = ((NI) 1);
	nimln(153, "lexbase.nim");
	fillbuffer_191099(L);
	nimln(154, "lexbase.nim");
	skiputf8bom_192416(L);
	popFrame();
}

N_NIMCALL(NI, getcolnumber_191061)(Baselexer191021* L, NI pos) {
	NI result;
	NI TMP861;
	nimfr("getColNumber", "lexbase.nim")
	result = 0;
	nimln(157, "lexbase.nim");
	TMP861 = subInt(pos, (*L).linestart);
	if ((NI)(TMP861) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
	result = ((NI)(TMP861) > 0? ((NI)(TMP861)) : -((NI)(TMP861)));
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, getcurrentline_191054)(Baselexer191021* L, NIM_BOOL marker) {
	NimStringDesc* result;
	NI i;
	nimfr("getCurrentLine", "lexbase.nim")
	result = 0;
	i = 0;
	nimln(161, "lexbase.nim");
	result = copyString(((NimStringDesc*) &TMP862));
	nimln(162, "lexbase.nim");
	i = (*L).linestart;
	{
		nimln(163, "lexbase.nim");
		while (1) {
			NI TMP863;
			if (!!((((NU8)((*L).buf[i])) == ((NU8)(13)) || ((NU8)((*L).buf[i])) == ((NU8)(10)) || ((NU8)((*L).buf[i])) == ((NU8)(0))))) goto LA2;
			nimln(164, "lexbase.nim");
			result = addChar(result, (*L).buf[i]);
			nimln(165, "lexbase.nim");
			TMP863 = addInt(i, ((NI) 1));
			i = (NI)(TMP863);
		} LA2: ;
	}
	nimln(166, "lexbase.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP864));
	nimln(167, "lexbase.nim");
	{
		NimStringDesc* LOC7;
		NI LOC8;
		NimStringDesc* LOC9;
		if (!marker) goto LA5;
		nimln(168, "lexbase.nim");
		LOC7 = 0;
		LOC8 = 0;
		LOC8 = getcolnumber_191061(L, (*L).bufpos);
		LOC9 = 0;
		LOC9 = nsuRepeatChar(32, ((NI)chckRange(LOC8, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		LOC7 = rawNewString(LOC9->Sup.len + 3);
appendString(LOC7, LOC9);
appendString(LOC7, ((NimStringDesc*) &TMP865));
		result = resizeString(result, LOC7->Sup.len + 0);
appendString(result, LOC7);
	}
	LA5: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void) {
	nimfr("lexbase", "lexbase.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void) {
static TNimNode* TMP1070[8];
static TNimNode TMP824[9];
NTI191021.size = sizeof(Baselexer191021);
NTI191021.kind = 17;
NTI191021.base = (&NTI3411);
TMP1070[0] = &TMP824[1];
TMP824[1].kind = 1;
TMP824[1].offset = offsetof(Baselexer191021, bufpos);
TMP824[1].typ = (&NTI108);
TMP824[1].name = "bufpos";
TMP1070[1] = &TMP824[2];
TMP824[2].kind = 1;
TMP824[2].offset = offsetof(Baselexer191021, buf);
TMP824[2].typ = (&NTI151);
TMP824[2].name = "buf";
TMP1070[2] = &TMP824[3];
TMP824[3].kind = 1;
TMP824[3].offset = offsetof(Baselexer191021, buflen);
TMP824[3].typ = (&NTI108);
TMP824[3].name = "bufLen";
TMP1070[3] = &TMP824[4];
TMP824[4].kind = 1;
TMP824[4].offset = offsetof(Baselexer191021, input);
TMP824[4].typ = (&NTI179025);
TMP824[4].name = "input";
TMP1070[4] = &TMP824[5];
TMP824[5].kind = 1;
TMP824[5].offset = offsetof(Baselexer191021, linenumber);
TMP824[5].typ = (&NTI108);
TMP824[5].name = "lineNumber";
TMP1070[5] = &TMP824[6];
TMP824[6].kind = 1;
TMP824[6].offset = offsetof(Baselexer191021, sentinel);
TMP824[6].typ = (&NTI108);
TMP824[6].name = "sentinel";
TMP1070[6] = &TMP824[7];
TMP824[7].kind = 1;
TMP824[7].offset = offsetof(Baselexer191021, linestart);
TMP824[7].typ = (&NTI108);
TMP824[7].name = "lineStart";
TMP1070[7] = &TMP824[8];
TMP824[8].kind = 1;
TMP824[8].offset = offsetof(Baselexer191021, fileopened);
TMP824[8].typ = (&NTI138);
TMP824[8].name = "fileOpened";
TMP824[0].len = 8; TMP824[0].kind = 2; TMP824[0].sons = &TMP1070[0];
NTI191021.node = &TMP824[0];
}

