/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\owner\documents\nim\esfj\nimcache\stdlib_parseopt2.o c:\users\owner\documents\nim\esfj\nimcache\stdlib_parseopt2.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct TY13606 TY13606;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Optparser158007 Optparser158007;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Slice88061 Slice88061;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Optparser158007  {
  TNimObject Sup;
TY13606* cmd;
NI pos;
NimStringDesc* remainingshortoptions;
NU8 kind;
NimStringDesc* key;
NimStringDesc* val;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY77659[32];
typedef NIM_CHAR TY158417[2];
struct  Slice88061  {
NI a;
NI b;
};
struct TY13606 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_158203)(TY13606* x, TY13606* y);
static N_INLINE(void*, seqtoptr_158214)(TY13606* x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(TY13606*, HEX40_158306)(NimStringDesc** a, NI aLen0);
N_NIMCALL(void, initoptparser_158027)(TY13606* cmdline, Optparser158007* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TY13606*, commandlineparams_153805)(void);
N_NIMCALL(void, initoptparser_158375)(NimStringDesc* cmdline, Optparser158007* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(TY13606*, nsuSplitCharSet)(NimStringDesc* s, TY77659 seps);
N_NIMCALL(void, initoptparser_158389)(Optparser158007* Result);
N_NIMCALL(void, nextoption_158411)(Optparser158007* p, NimStringDesc* token, NIM_BOOL allowempty);
N_NIMCALL(NIM_BOOL, contains_99351)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice88061, HEX2EHEX2E_108273)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, nponext)(Optparser158007* p);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(TY13606*, HEX5BHEX5D_158598)(TY13606* s, Slice88061 x);
N_NIMCALL(NimStringDesc*, npocmdLineRest)(Optparser158007* p);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen0, NimStringDesc* sep);
STRING_LITERAL(TMP602, "", 0);
static NIM_CONST TY77659 TMP628 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
NIM_CONST TY158417 TMP629 = {58,
61}
;
STRING_LITERAL(TMP640, "--", 2);
STRING_LITERAL(TMP642, "-", 1);
STRING_LITERAL(TMP655, " ", 1);
extern TFrame* frameptr_17042;
extern TNimType NTI3411; /* RootObj */
TNimType NTI158007; /* OptParser */
extern TNimType NTI13606; /* seq[string] */
extern TNimType NTI108; /* int */
extern TNimType NTI149; /* string */
TNimType NTI158005; /* CmdLineKind */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(void*, seqtoptr_158214)(TY13606* x) {
	void* result;
	nimfr("seqToPtr", "system.nim")
	result = 0;
	nimln(1893, "system.nim");
	result = ((void*) (x));
	popFrame();
	return result;
}

N_NIMCALL(void, initoptparser_158027)(TY13606* cmdline, Optparser158007* Result) {
	nimfr("initOptParser", "parseopt2.nim")
{	nimln(49, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*Result).remainingshortoptions), copyString(((NimStringDesc*) &TMP602)));
	nimln(51, "parseopt2.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = HEX3DHEX3D_158203(cmdline, NIM_NIL);
		if (!LOC3) goto LA4;
		nimln(52, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*Result).cmd), commandlineparams_153805());
		nimln(53, "parseopt2.nim");
		goto BeforeRet;
	}
	LA4: ;
	nimln(57, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*Result).cmd), HEX40_158306(cmdline->data, cmdline->Sup.len));
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, initoptparser_158375)(NimStringDesc* cmdline, Optparser158007* Result) {
	nimfr("initOptParser", "parseopt2.nim")
{	nimln(63, "parseopt2.nim");
	{
		if (!((cmdline) && (cmdline)->Sup.len == 0)) goto LA3;
		nimln(64, "parseopt2.nim");
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI158007));
		(*Result).Sup.m_type = (&NTI158007);
		initoptparser_158027(NIM_NIL, Result);
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		TY13606* LOC6;
		nimln(66, "parseopt2.nim");
		LOC6 = 0;
		LOC6 = nsuSplitCharSet(cmdline, TMP628);
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI158007));
		(*Result).Sup.m_type = (&NTI158007);
		initoptparser_158027(LOC6, Result);
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, initoptparser_158389)(Optparser158007* Result) {
	TY13606* LOC1;
	nimfr("initOptParser", "parseopt2.nim")
{	nimln(71, "parseopt2.nim");
	LOC1 = 0;
	LOC1 = commandlineparams_153805();
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI158007));
	(*Result).Sup.m_type = (&NTI158007);
	initoptparser_158027(LOC1, Result);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x) {
	NimStringDesc* result;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2880, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice88061, HEX2EHEX2E_108273)(NI a, NI b) {
	Slice88061 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(234, "system.nim");
	result.a = a;
	nimln(235, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, nextoption_158411)(Optparser158007* p, NimStringDesc* token, NIM_BOOL allowempty) {
	nimfr("nextOption", "parseopt2.nim")
{	{
		NIM_CHAR splitchar_158455;
		NI i_158490;
		splitchar_158455 = 0;
		nimln(1703, "system.nim");
		i_158490 = ((NI) 0);
		nimln(1704, "system.nim");
		{
			if (!(((NI) (i_158490)) <= ((NI) 1))) goto LA4;
			{
				nimln(1705, "system.nim");
				while (1) {
					NI TMP635;
					nimln(1706, "system.nim");
					splitchar_158455 = TMP629[(i_158490)- 0];
					nimln(77, "parseopt2.nim");
					{
						NIM_BOOL LOC10;
						NI pos;
						NI TMP632;
						Slice88061 LOC13;
						NI TMP633;
						NI TMP634;
						Slice88061 LOC14;
						LOC10 = 0;
						LOC10 = contains_99351(token, splitchar_158455);
						if (!LOC10) goto LA11;
						nimln(78, "parseopt2.nim");
						pos = nsuFindChar(token, splitchar_158455, ((NI) 0));
						nimln(79, "parseopt2.nim");
						TMP632 = subInt(pos, ((NI) 1));
						LOC13 = HEX2EHEX2E_108273(((NI) 0), (NI)(TMP632));
						unsureAsgnRef((void**) (&(*p).key), HEX5BHEX5D_88054(token, LOC13));
						nimln(80, "parseopt2.nim");
						TMP633 = addInt(pos, ((NI) 1));
						TMP634 = subInt((token ? token->Sup.len : 0), ((NI) 1));
						LOC14 = HEX2EHEX2E_108273((NI)(TMP633), (NI)(TMP634));
						unsureAsgnRef((void**) (&(*p).val), HEX5BHEX5D_88054(token, LOC14));
						nimln(81, "parseopt2.nim");
						goto BeforeRet;
					}
					LA11: ;
					nimln(1707, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i_158490)))) goto LA17;
						goto LA6;
					}
					LA17: ;
					nimln(1708, "system.nim");
					TMP635 = addInt(i_158490, ((NI) 1));
					if (TMP635 < 0 || TMP635 > 1) raiseOverflow();
					i_158490 = (NI)(TMP635);
				}
			} LA6: ;
		}
		LA4: ;
	}
	nimln(83, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*p).key), copyString(token));
	nimln(84, "parseopt2.nim");
	{
		if (!allowempty) goto LA21;
		nimln(85, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TMP602)));
	}
	goto LA19;
	LA21: ;
	{
		NI TMP636;
		Slice88061 LOC24;
		nimln(87, "parseopt2.nim");
		TMP636 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		LOC24 = HEX2EHEX2E_108273(((NI) 0), (NI)(TMP636));
		unsureAsgnRef((void**) (&(*p).remainingshortoptions), HEX5BHEX5D_88054(token, LOC24));
		nimln(88, "parseopt2.nim");
		nponext(p);
	}
	LA19: ;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, nponext)(Optparser158007* p) {
	NimStringDesc* token;
	NI TMP638;
	nimfr("next", "parseopt2.nim")
{	nimln(91, "parseopt2.nim");
	{
		Slice88061 LOC5;
		NI TMP637;
		Slice88061 LOC6;
		if (!!((((*p).remainingshortoptions ? (*p).remainingshortoptions->Sup.len : 0) == ((NI) 0)))) goto LA3;
		nimln(92, "parseopt2.nim");
		(*p).kind = ((NU8) 3);
		nimln(93, "parseopt2.nim");
		LOC5 = HEX2EHEX2E_108273(((NI) 0), ((NI) 0));
		unsureAsgnRef((void**) (&(*p).key), HEX5BHEX5D_88054((*p).remainingshortoptions, LOC5));
		nimln(94, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TMP602)));
		nimln(95, "parseopt2.nim");
		TMP637 = subInt(((*p).remainingshortoptions ? (*p).remainingshortoptions->Sup.len : 0), ((NI) 1));
		LOC6 = HEX2EHEX2E_108273(((NI) 1), (NI)(TMP637));
		unsureAsgnRef((void**) (&(*p).remainingshortoptions), HEX5BHEX5D_88054((*p).remainingshortoptions, LOC6));
		nimln(96, "parseopt2.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(98, "parseopt2.nim");
	{
		if (!(((*p).cmd ? (*p).cmd->Sup.len : 0) <= (*p).pos)) goto LA9;
		nimln(99, "parseopt2.nim");
		(*p).kind = ((NU8) 0);
		nimln(100, "parseopt2.nim");
		goto BeforeRet;
	}
	LA9: ;
	nimln(102, "parseopt2.nim");
	if ((NU)((*p).pos) >= (NU)((*p).cmd->Sup.len)) raiseIndexError();
	token = (*p).cmd->data[(*p).pos];
	nimln(103, "parseopt2.nim");
	TMP638 = addInt((*p).pos, ((NI) 1));
	(*p).pos = (NI)(TMP638);
	nimln(105, "parseopt2.nim");
	{
		NIM_BOOL LOC13;
		NI TMP641;
		Slice88061 LOC16;
		NimStringDesc* LOC17;
		LOC13 = 0;
		LOC13 = nsuStartsWith(token, ((NimStringDesc*) &TMP640));
		if (!LOC13) goto LA14;
		nimln(106, "parseopt2.nim");
		(*p).kind = ((NU8) 2);
		nimln(107, "parseopt2.nim");
		TMP641 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		LOC16 = HEX2EHEX2E_108273(((NI) 2), (NI)(TMP641));
		LOC17 = 0;
		LOC17 = HEX5BHEX5D_88054(token, LOC16);
		nextoption_158411(p, LOC17, NIM_TRUE);
	}
	goto LA11;
	LA14: ;
	{
		NIM_BOOL LOC19;
		NI TMP643;
		Slice88061 LOC22;
		NimStringDesc* LOC23;
		nimln(108, "parseopt2.nim");
		LOC19 = 0;
		LOC19 = nsuStartsWith(token, ((NimStringDesc*) &TMP642));
		if (!LOC19) goto LA20;
		nimln(109, "parseopt2.nim");
		(*p).kind = ((NU8) 3);
		nimln(110, "parseopt2.nim");
		TMP643 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		LOC22 = HEX2EHEX2E_108273(((NI) 1), (NI)(TMP643));
		LOC23 = 0;
		LOC23 = HEX5BHEX5D_88054(token, LOC22);
		nextoption_158411(p, LOC23, NIM_TRUE);
	}
	goto LA11;
	LA20: ;
	{
		nimln(112, "parseopt2.nim");
		(*p).kind = ((NU8) 1);
		nimln(113, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).key), copyString(token));
		nimln(114, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TMP602)));
	}
	LA11: ;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, npocmdLineRest)(Optparser158007* p) {
	NimStringDesc* result;
	NI TMP654;
	Slice88061 LOC1;
	TY13606* LOC2;
	nimfr("cmdLineRest", "parseopt2.nim")
{	result = 0;
	nimln(119, "parseopt2.nim");
	TMP654 = subInt(((*p).cmd ? (*p).cmd->Sup.len : 0), ((NI) 1));
	LOC1 = HEX2EHEX2E_108273((*p).pos, (NI)(TMP654));
	LOC2 = 0;
	LOC2 = HEX5BHEX5D_158598((*p).cmd, LOC1);
	result = nsuJoinSep(LOC2->data, LOC2->Sup.len, ((NimStringDesc*) &TMP655));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init)(void) {
	nimfr("parseopt2", "parseopt2.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit)(void) {
static TNimNode* TMP619[6];
static TNimNode* TMP620[4];
NI TMP622;
static char* NIM_CONST TMP621[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode TMP593[12];
NTI158007.size = sizeof(Optparser158007);
NTI158007.kind = 17;
NTI158007.base = (&NTI3411);
TMP619[0] = &TMP593[1];
TMP593[1].kind = 1;
TMP593[1].offset = offsetof(Optparser158007, cmd);
TMP593[1].typ = (&NTI13606);
TMP593[1].name = "cmd";
TMP619[1] = &TMP593[2];
TMP593[2].kind = 1;
TMP593[2].offset = offsetof(Optparser158007, pos);
TMP593[2].typ = (&NTI108);
TMP593[2].name = "pos";
TMP619[2] = &TMP593[3];
TMP593[3].kind = 1;
TMP593[3].offset = offsetof(Optparser158007, remainingshortoptions);
TMP593[3].typ = (&NTI149);
TMP593[3].name = "remainingShortOptions";
TMP619[3] = &TMP593[4];
NTI158005.size = sizeof(NU8);
NTI158005.kind = 14;
NTI158005.base = 0;
NTI158005.flags = 3;
for (TMP622 = 0; TMP622 < 4; TMP622++) {
TMP593[TMP622+5].kind = 1;
TMP593[TMP622+5].offset = TMP622;
TMP593[TMP622+5].name = TMP621[TMP622];
TMP620[TMP622] = &TMP593[TMP622+5];
}
TMP593[9].len = 4; TMP593[9].kind = 2; TMP593[9].sons = &TMP620[0];
NTI158005.node = &TMP593[9];
TMP593[4].kind = 1;
TMP593[4].offset = offsetof(Optparser158007, kind);
TMP593[4].typ = (&NTI158005);
TMP593[4].name = "kind";
TMP619[4] = &TMP593[10];
TMP593[10].kind = 1;
TMP593[10].offset = offsetof(Optparser158007, key);
TMP593[10].typ = (&NTI149);
TMP593[10].name = "key";
TMP619[5] = &TMP593[11];
TMP593[11].kind = 1;
TMP593[11].offset = offsetof(Optparser158007, val);
TMP593[11].typ = (&NTI149);
TMP593[11].name = "val";
TMP593[0].len = 6; TMP593[0].kind = 2; TMP593[0].sons = &TMP619[0];
NTI158007.node = &TMP593[0];
}

